/* Dermaapp – Sektion 20: Dermatologische Pharmakologie (Schweiz). Auto-generiert aus Facharzt-Unterlagen. */
(function () {
  const flash = [
    {s:20, q:"Wirkmechanismus topischer Kortikosteroide und Prinzip der Klasseneinteilung?", a:"Bindung an den zytosolischen Glukokortikoid-Rezeptor → antiinflammatorisch, immunsuppressiv, antiproliferativ und vasokonstriktorisch. Einteilung nach Wirkstärke in Klasse I (schwach) bis IV (sehr stark)."},
    {s:20, q:"Klasse-I-Kortikosteroid (schwach) mit CH-Markenname und bevorzugtem Einsatzort?", a:"Hydrocortison/Hydrocortisonacetat (z.B. Sanadermil, Dermacalm). Mittel der Wahl im Gesicht, in Intertrigines und bei Kindern."},
    {s:20, q:"Klasse-IV-Kortikosteroid (sehr stark) – Wirkstoff, Markenname und Mengenlimit?", a:"Clobetasolpropionat (z.B. Dermovate, Clobex-Shampoo). Maximal 2 Wochen und höchstens 50 g/Woche; nicht im Gesicht."},
    {s:20, q:"Welche Wirkstärkeklasse hat Mometasonfuroat (Elocom) und wie oft wird es appliziert?", a:"Klasse III (stark), einmal täglich ausreichend. Weitere Klasse-III-Vertreter: Methylprednisolonaceponat (Advantan), Fluticasonpropionat (Cutivate), Betamethasondipropionat (Diprosone)."},
    {s:20, q:"Wichtigste lokale UAW topischer Kortikosteroide?", a:"Hautatrophie, Teleangiektasien, Striae distensae, Steroidakne, periorale Dermatitis, Hypopigmentierung. Bei grossflächiger/okklusiver Anwendung HHN-Achsen-Suppression möglich."},
    {s:20, q:"Typische Indikationen für intraläsionales Triamcinolonacetonid (Kenacort)?", a:"Keloide und hypertrophe Narben sowie Alopecia areata; 2.5–10 mg/ml, Wiederholung alle 4–6 Wochen. Lokale UAW: Atrophie/Dellen und Hypopigmentierung."},
    {s:20, q:"Wirkmechanismus von topischem Tretinoin (Airol)?", a:"Vitamin-A-Säure, bindet den Retinsäure-Rezeptor (RAR) → normalisiert die Keratinozyten-Differenzierung, komedolytisch und antiinflammatorisch. UAW: Erythem, Schuppung, Photosensibilisierung."},
    {s:20, q:"Isotretinoin – übliche Tagesdosis und angestrebte kumulative Gesamtdosis?", a:"0.3–0.5 mg/kg/Tag einschleichend, angestrebte kumulative Dosis 120–150 mg/kg über 4–8 Monate. Einnahme zu einer fettreichen Mahlzeit."},
    {s:20, q:"Welche Laborwerte werden unter Isotretinoin überwacht?", a:"Transaminasen und Lipide (v.a. Triglyzeride) vor Therapie, nach 1 Monat und dann alle 3 Monate; bei gebärfähigen Frauen zusätzlich monatliches β-HCG."},
    {s:20, q:"Isotretinoin: Kernpunkte des Schwangerschaftsverhütungsprogramms?", a:"Wegen hoher Teratogenität (Retinoid-Embryopathie) zwei sichere Verhütungsmethoden gleichzeitig von 1 Monat vor bis 1 Monat nach Therapie, monatlicher Schwangerschaftstest (β-HCG) und dokumentierte Aufklärung."},
    {s:20, q:"Warum ist die Kombination Isotretinoin + Tetrazyklin kontraindiziert?", a:"Additiv erhöhtes Risiko eines Pseudotumor cerebri (idiopathische intrakranielle Hypertension). Gleiches gilt für Acitretin und Alitretinoin mit Tetrazyklinen."},
    {s:20, q:"Acitretin (Neotigason) – Hauptindikation und Besonderheit der Kontrazeption?", a:"Schwere Psoriasis und Verhornungsstörungen. Extrem teratogen: sichere Kontrazeption von 1 Monat vor bis 3 Jahre nach Therapieende, strikter Alkoholverzicht (Alkohol fördert die Rückbildung zum langlebigen Etretinat)."},
    {s:20, q:"Alitretinoin systemisch (Toctino) – Indikation und zusätzlich zu kontrollierender Laborwert?", a:"Schweres chronisches, KS-refraktäres Handekzem, maximal 6 Monate. Neben Leberwerten/Lipiden/β-HCG auch TSH kontrollieren (Hypothyreose durch TSH-Senkung möglich)."},
    {s:20, q:"Wirkmechanismus topischer Calcineurin-Inhibitoren (Tacrolimus/Protopic, Pimecrolimus/Elidel)?", a:"Bindung an FKBP12 → Hemmung von Calcineurin → NFAT bleibt zytoplasmatisch → verminderte T-Zell-Aktivierung und IL-2-Produktion. Steroidfreie Option u.a. für Gesicht/Intertrigines."},
    {s:20, q:"Tacrolimus-Salbe: Konzentrationen, proaktives Schema und Box-Warning?", a:"0.03% ab 2 Jahren, 0.1% für Erwachsene; nach Abheilung proaktiv 2×/Woche. UAW: initiales Brennen, Alkohol-Flush. Die FDA-Box-Warnung (Lymphom/NMSC) ist klinisch nicht bestätigt."},
    {s:20, q:"Benzoylperoxid (Lubexyl, Benzac) – Mechanismus und praktischer Vorteil?", a:"Freisetzung freier Radikale → antibakteriell gegen Cutibacterium acnes und komedolytisch. Erzeugt KEINE bakterielle Resistenz, daher idealer Kombipartner topischer Antibiotika. Cave: bleicht Textilien/Haare."},
    {s:20, q:"Warum wird topisches Clindamycin (Dalacin T) bei Akne nie als Monotherapie gegeben?", a:"Zur Vermeidung bakterieller Resistenzen immer mit Benzoylperoxid oder einem Retinoid kombinieren."},
    {s:20, q:"Azelainsäure (Skinoren) – warum bei Akne in der Schwangerschaft bevorzugt?", a:"Wirkt antimikrobiell, antiinflammatorisch und normalisiert die Keratinisierung; gilt als topisches Mittel der Wahl gegen Akne in der Schwangerschaft."},
    {s:20, q:"Brimonidin (Mirvaso) – Wirkprinzip bei Rosazea und typische UAW?", a:"Selektiver α2-Agonist → Vasokonstriktion → Reduktion des persistierenden Erythems. Typisch ist ein Rebound-Erythem nach Nachlassen der Wirkung."},
    {s:20, q:"Wirkmechanismus von Terbinafin und wichtigstes Wirkspektrum?", a:"Allylamin, hemmt die Squalenepoxidase → fungizid, v.a. gegen Dermatophyten. Topisch (Lamisil) und systemisch verfügbar."},
    {s:20, q:"Terbinafin systemisch – Onychomykose-Dosierung und charakteristische UAW?", a:"250 mg/Tag; 6 Wochen bei Fingernägeln, 12 Wochen bei Zehennägeln. Charakteristisch ist eine reversible Geschmacksstörung (~3%); selten Hepatotoxizität (KI bei aktiver Lebererkrankung)."},
    {s:20, q:"Ketoconazol topisch (Terzolin, Nizoral) – häufigste dermatologische Anwendung?", a:"Als 2%-Shampoo beim seborrhoischen Ekzem und bei Pityriasis versicolor. Systemisch wird Ketoconazol wegen Hepato-/Nebennierentoxizität nicht mehr empfohlen."},
    {s:20, q:"Fluconazol – wichtigste Interaktion durch Enzymhemmung?", a:"Starker CYP2C9- und mässiger CYP3A4-Hemmer: erhöht u.a. Warfarin, Sulfonylharnstoffe, Statine, Ciclosporin und Tacrolimus. Bei wiederholter/hoher Dosis teratogen."},
    {s:20, q:"Itraconazol (Sporanox) – zwei wichtige Sicherheitsaspekte?", a:"Negativ inotrope Wirkung → KI bei Herzinsuffizienz; starker CYP3A4- und P-gp-Hemmer mit zahlreichen Interaktionen und QT-Verlängerung."},
    {s:20, q:"Doxycyclin – zentrale Kontraindikationen und eine klassenspezifische UAW?", a:"KI ab der 16. SSW und bei Kindern <8 Jahren (Zahnverfärbung/Knochenanlage). Klassenspezifisch: Photosensibilisierung; selten Pseudotumor cerebri."},
    {s:20, q:"Welche zwei UAW sind für eine Minocyclin-Langzeittherapie charakteristisch?", a:"Schiefergraue Hyperpigmentierung (Haut/Schleimhaut/Narben) und ein medikamenteninduzierter Lupus (DILE) bzw. autoimmune Hepatitis/ANCA-Vaskulitis."},
    {s:20, q:"Wirkmechanismus von Aciclovir/Valaciclovir und Standard-Zosterdosis?", a:"Nukleosidanaloga → Hemmung der viralen DNA-Polymerase (HSV/VZV). Herpes zoster: Valaciclovir 1000 mg 3×/Tag über 7 Tage (oder Aciclovir 800 mg 5×/Tag). Dosisanpassung bei Niereninsuffizienz."},
    {s:20, q:"Warum ist Brivudin zusammen mit 5-Fluorouracil absolut kontraindiziert?", a:"Brivudin hemmt die Dihydropyrimidin-Dehydrogenase → massive Akkumulation von 5-FU/Capecitabin mit potenziell letaler Myelosuppression/Mukositis; Mindestabstand 4 Wochen."},
    {s:20, q:"Permethrin (Scabinol) – Anwendung bei Skabies und Stellenwert in der Schwangerschaft?", a:"5%-Creme ganzkörperlich, 8–12 h einwirken, Wiederholung nach 7–14 Tagen. Mittel der Wahl bei Skabies auch in der Schwangerschaft."},
    {s:20, q:"Methotrexat in der Dermatologie – Dosierung und obligate Begleitmedikation?", a:"7.5–25 mg einmal pro Woche (p.o. oder s.c.), immer mit Folsäure 5 mg 1–2 Tage nach der MTX-Gabe. Hauptindikation ist die schwere Psoriasis."},
    {s:20, q:"Welche Komedikation ist unter Methotrexat wegen Toxizität kontraindiziert?", a:"Trimethoprim/Sulfamethoxazol (Cotrimoxazol) – additive Folatantagonisierung mit Panzytopenie-Risiko. Auch NSAR erhöhen die MTX-Toxizität (renal)."},
    {s:20, q:"Ciclosporin – Wirkmechanismus und wichtigste dosislimitierende UAW?", a:"Bindet Cyclophilin → hemmt Calcineurin → IL-2↓ → T-Zell-Hemmung. Dosislimitierend ist die (ab ~2 Jahren teils irreversible) Nephrotoxizität sowie Hypertonie. Keine gleichzeitige UV-/Phototherapie (NMSC-Risiko)."},
    {s:20, q:"Welche Untersuchung ist vor Azathioprin obligat und welche Interaktion ist gefährlich?", a:"Bestimmung der TPMT-Aktivität (ggf. NUDT15): bei homozygotem Mangel droht schwere Knochenmarksuppression (KI). Allopurinol/Febuxostat → Azathioprin-Dosis um ~75% reduzieren."},
    {s:20, q:"Mycophenolat-Mofetil (CellCept) – Wirkmechanismus und Schwangerschaftsstatus?", a:"IMPDH-Hemmer → selektive Hemmung der de-novo-Purinsynthese in Lymphozyten. Strikt teratogen (KI in der Schwangerschaft); charakteristische UAW ist eine Diarrhoe."},
    {s:20, q:"Welcher Test ist vor Dapson (Disulone) zwingend und welche zwei UAW werden überwacht?", a:"G6PD-Aktivität bestimmen (sonst Hämolyse). Überwachung von Hämolyse und Methämoglobinämie; dosisabhängig Agranulozytose. Klassische Indikation: Dermatitis herpetiformis Duhring."},
    {s:20, q:"Warum braucht Hydroxychloroquin (Plaquenil) ein augenärztliches Monitoring?", a:"Risiko einer irreversiblen Retinopathie/Makulopathie; Dosis ≤5 mg/kg Idealgewicht, ophthalmologische Baseline und jährliche Kontrolle ab dem 5. Therapiejahr. Hauptindikation: kutaner Lupus erythematodes."},
    {s:20, q:"Dimethylfumarat (Skilarence, Fumaderm) – Mechanismus und zwei relevante UAW?", a:"Aktivierung des NRF2-Signalwegs → antiinflammatorisch/immunmodulatorisch. Relevante UAW: initialer Flush und Lymphopenie (Lymphozyten kontrollieren); sehr selten PML."},
    {s:20, q:"Cetirizin/Levocetirizin (Zyrtec, Xyzal) – Besonderheit bei chronischer Urtikaria und in der Schwangerschaft?", a:"Nicht sedierende H1-Antihistaminika der 2. Generation; bei chronischer spontaner Urtikaria bis zur 4-fachen Standarddosis (off-label). Levocetirizin gilt als Mittel der Wahl in der Schwangerschaft."},
    {s:20, q:"Warum wird Hydroxyzin (Atarax) den H1-Antihistaminika der 2. Generation oft nicht vorgezogen?", a:"Als 1.-Generation-Antihistaminikum ist es ZNS-gängig (sedierend, anticholinerg) und kann die QT-Zeit verlängern; nützlich v.a. wegen sedierend-anxiolytischer Wirkung bei Pruritus."},
    {s:20, q:"Dupilumab (Dupixent) – molekulares Ziel und häufigste UAW?", a:"Bindet die IL-4-Rezeptor-α-Kette → Hemmung von IL-4 und IL-13. Häufigste UAW ist die Konjunktivitis. Kein obligates Tbc-Screening (kein erhöhtes Reaktivierungsrisiko)."},
    {s:20, q:"Omalizumab (Xolair) – Wirkmechanismus und wichtige Sicherheitsmassnahme?", a:"Anti-IgE-Antikörper: bindet freies IgE → verhindert dessen Bindung an FcεRI. Bei chronischer spontaner Urtikaria 300 mg alle 4 Wochen. Anaphylaxie-Risiko bei den ersten Injektionen → 2 h Nachbeobachtung."},
    {s:20, q:"Warum ist Certolizumab pegol (Cimzia) bei Kinderwunsch/Schwangerschaft der bevorzugte TNF-Blocker?", a:"Es ist ein PEGyliertes Fab-Fragment ohne Fc-Domäne → praktisch kein aktiver Plazenta- oder Milchübergang."},
    {s:20, q:"Secukinumab (Cosentyx) – Ziel und eine wichtige relative Kontraindikation?", a:"Anti-IL-17A-Antikörper. Vorsicht bei chronisch-entzündlichen Darmerkrankungen (Aggravierung möglich) und erhöhte Anfälligkeit für mukokutane Candida-Infektionen."},
    {s:20, q:"Was unterscheidet Bimekizumab (Bimzelx) von Secukinumab/Ixekizumab?", a:"Bimekizumab blockiert IL-17A UND IL-17F. Preis ist eine höhere Rate oraler Candidiasis (~10–19%)."},
    {s:20, q:"Ustekinumab (Stelara) versus Guselkumab (Tremfya) – welche Zytokinuntereinheiten?", a:"Ustekinumab bindet p40 (gemeinsame Untereinheit von IL-12 und IL-23). Guselkumab (wie Risankizumab und Tildrakizumab) bindet p19, also selektiv IL-23."},
    {s:20, q:"Welches Screening ist vor systemischer Immunsuppression bzw. Biologika obligat?", a:"HBV, HCV, HIV und latente Tuberkulose (IGRA + Rö-Thorax). Bei latenter Tbc INH-Prophylaxe mindestens 1 Monat vor Biologikumstart; unter Therapie keine Lebendimpfungen."},
    {s:20, q:"Welche Boxed Warnings gelten als Klasseneffekt oraler JAK-Inhibitoren und welche Impfung wird vorher empfohlen?", a:"Erhöhtes Risiko für schwere Infektionen, venöse Thromboembolien, MACE und Malignome (v.a. ältere/kardiovaskuläre Risikopatienten) sowie HSV/VZV-Reaktivierung. Vor Beginn wird die rekombinante Herpes-zoster-Impfung (Shingrix) empfohlen."},
    {s:20, q:"Checkpoint-Inhibitoren in der Dermatoonkologie – Zielstrukturen und typisches UAW-Spektrum?", a:"Anti-PD-1 (Nivolumab, Pembrolizumab), Anti-PD-L1 und Anti-CTLA-4 (Ipilimumab) enthemmen die T-Zell-Antwort. Charakteristisch sind immunvermittelte UAW (irAE): Dermatitis, Vitiligo, Colitis, Hepatitis, Pneumonitis, Thyreoiditis/Hypophysitis; schwere irAE werden mit systemischen Steroiden behandelt."},
    {s:20, q:"Warum werden BRAF-Inhibitoren beim Melanom mit MEK-Inhibitoren kombiniert?", a:"BRAF-Inhibitoren (Vemurafenib, Dabrafenib, Encorafenib) wirken bei BRAF-V600-Mutation, können aber paradoxe MAPK-Aktivierung mit kutanen Plattenepithelkarzinomen/Keratoakanthomen auslösen. Die Kombination mit einem MEK-Inhibitor (Trametinib, Cobimetinib, Binimetinib) erhöht die Wirksamkeit und senkt diese kutanen UAW."},
    {s:20, q:"Vismodegib (Erivedge) – Wirkmechanismus, Indikation und wichtige Sicherheitsauflage?", a:"Hemmt Smoothened (SMO) im Hedgehog-Signalweg; zugelassen für fortgeschrittenes/metastasiertes Basalzellkarzinom und beim Gorlin-Syndrom. Typische UAW: Muskelspasmen, Dysgeusie, Alopezie, Gewichtsverlust. Streng teratogen → sichere Kontrazeption obligat."}
  ];
  const mc = [
    {s:20, q:"Welches topische Kortikosteroid ist am besten für die kurzfristige Anwendung im Gesicht eines Kindes geeignet?", o:["Clobetasolpropionat (Dermovate)","Hydrocortison (Dermacalm)","Mometasonfuroat (Elocom)","Betamethasondipropionat (Diprosone)"], c:1, e:"Klasse-I-Steroide wie Hydrocortison sind im Gesicht und bei Kindern Mittel der Wahl; potente Klassen drohen mit Atrophie."},
    {s:20, q:"Welche kumulative Zieldosis wird unter Isotretinoin angestrebt?", o:["30–60 mg/kg","120–150 mg/kg","5–10 mg/kg","300–400 mg/kg"], c:1, e:"120–150 mg/kg kumulativ minimieren die Rezidivrate."},
    {s:20, q:"Welcher Laborbefund ist ein Abbruchkriterium unter Isotretinoin?", o:["Triglyzeride >9 mmol/l","LDL 3 mmol/l","Ferritin 200 µg/l","TSH 2 mU/l"], c:0, e:"Triglyzeride >9 mmol/l (Pankreatitisrisiko) oder Transaminasen >3× ULN sind Abbruchkriterien."},
    {s:20, q:"Wie lange muss eine Frau nach Absetzen von Acitretin sicher verhüten?", o:["1 Monat","6 Monate","1 Jahr","3 Jahre"], c:3, e:"Wegen Rückbildung zum langlebigen Etretinat (v.a. bei Alkohol) sind 3 Jahre erforderlich."},
    {s:20, q:"Wie wirken die topischen Calcineurin-Inhibitoren Tacrolimus und Pimecrolimus?", o:["Hemmung der Squalenepoxidase","FKBP12-Bindung → Calcineurin-Hemmung → NFAT-Block","COX-2-Hemmung","Vitamin-D-Rezeptor-Agonismus"], c:1, e:"Sie binden FKBP12, hemmen Calcineurin und blockieren die NFAT-abhängige T-Zell-Aktivierung."},
    {s:20, q:"Welcher Vorteil zeichnet Benzoylperoxid gegenüber topischen Antibiotika aus?", o:["Es erzeugt keine bakterielle Resistenz","Es wirkt sebosuppressiv über RAR","Es bleicht die Haut dauerhaft","Es ist stark UV-protektiv"], c:0, e:"BPO wirkt über freie Radikale und erzeugt keine Resistenz; daher idealer Kombipartner."},
    {s:20, q:"Terbinafin wirkt über die Hemmung welches Enzyms?", o:["14α-Demethylase","Squalenepoxidase","Dihydrofolat-Reduktase","IMPDH"], c:1, e:"Als Allylamin hemmt Terbinafin die Squalenepoxidase → fungizid v.a. gegen Dermatophyten."},
    {s:20, q:"Welches Enzym hemmen systemische Azol-Antimykotika (Fluconazol/Itraconazol)?", o:["Squalenepoxidase","Lanosterol-14α-Demethylase (CYP)","Beta-Glucan-Synthase","Chitinsynthase"], c:1, e:"Azole hemmen die CYP-abhängige 14α-Demethylase → Ergosterolmangel."},
    {s:20, q:"Welche Aussage zu Fluconazol-Interaktionen trifft zu?", o:["Es induziert CYP3A4 stark","Es ist ein CYP2C9-Hemmer und erhöht Warfarin","Es senkt Ciclosporinspiegel","Es hat keine relevanten Interaktionen"], c:1, e:"Fluconazol hemmt CYP2C9/3A4 → Anstieg von Warfarin, Statinen, Ciclosporin/Tacrolimus."},
    {s:20, q:"Warum ist Itraconazol bei Herzinsuffizienz kontraindiziert?", o:["Es wirkt negativ inotrop","Es verursacht eine Hyperkaliämie","Es ist nephrotoxisch","Es senkt den Blutdruck stark"], c:0, e:"Itraconazol wirkt negativ inotrop und kann eine Herzinsuffizienz verschlechtern."},
    {s:20, q:"Ab welchem Zeitpunkt bzw. welcher Gruppe ist Doxycyclin kontraindiziert?", o:["Ab 16. SSW und bei Kindern <8 Jahren","Nur im 1. Trimenon","Bei allen über 65-Jährigen","Bei Niereninsuffizienz absolut"], c:0, e:"Tetrazykline lagern sich in Zähne und Knochen ein → KI ab 16. SSW und bei Kindern <8 Jahren."},
    {s:20, q:"Welche UAW ist typisch für die Langzeittherapie mit Minocyclin?", o:["Schiefergraue Hyperpigmentierung und Drug-induced Lupus","Gingivahyperplasie","Retinopathie","Isolierte Photoonycholyse"], c:0, e:"Minocyclin verursacht Hyperpigmentierungen und einen medikamenteninduzierten Lupus (DILE)."},
    {s:20, q:"Wodurch wirken Aciclovir und Valaciclovir?", o:["Hemmung der Neuraminidase","Hemmung der viralen DNA-Polymerase","Hemmung der reversen Transkriptase","Blockade des M2-Ionenkanals"], c:1, e:"Nach Phosphorylierung hemmen sie die virale DNA-Polymerase (HSV/VZV)."},
    {s:20, q:"Welche Kombination ist wegen potenziell letaler Toxizität kontraindiziert?", o:["Brivudin + 5-Fluorouracil","Aciclovir + Valaciclovir","Doxycyclin + Benzoylperoxid","Terbinafin + Clotrimazol"], c:0, e:"Brivudin hemmt die DPD → letale 5-FU-Akkumulation; Mindestabstand 4 Wochen."},
    {s:20, q:"Welche Begleitmedikation gehört obligat zur Methotrexat-Therapie?", o:["Allopurinol","Folsäure 1–2 Tage nach der MTX-Gabe","Cotrimoxazol","Probenecid"], c:1, e:"Folsäure reduziert MTX-UAW; Cotrimoxazol und NSAR sind wegen Toxizität zu meiden."},
    {s:20, q:"Welches Antibiotikum ist unter Methotrexat wegen additiver Toxizität kontraindiziert?", o:["Amoxicillin","Cotrimoxazol (Trimethoprim/Sulfamethoxazol)","Cephalexin","Clindamycin"], c:1, e:"Trimethoprim wirkt ebenfalls als Folatantagonist → Panzytopenie-Gefahr."},
    {s:20, q:"Was ist die dosislimitierende Langzeittoxizität von Ciclosporin?", o:["Lungenfibrose","Nephrotoxizität","Retinopathie","Agranulozytose"], c:1, e:"Nierenfunktion und Blutdruck limitieren die Therapie; die Nephrotoxizität ist ab ~2 Jahren teils irreversibel."},
    {s:20, q:"Welche Interaktion erfordert unter Azathioprin eine drastische Dosisreduktion?", o:["Kombination mit Allopurinol/Febuxostat","Kombination mit Vitamin C","Kombination mit Cetirizin","Kombination mit Paracetamol"], c:0, e:"Allopurinol/Febuxostat hemmen die Xanthinoxidase → Anstieg toxischer Metaboliten; Dosis um ~75% senken."},
    {s:20, q:"Mycophenolat-Mofetil hemmt selektiv welches Enzym?", o:["Inosinmonophosphat-Dehydrogenase (IMPDH)","Calcineurin","Dihydrofolat-Reduktase","Phosphodiesterase 4"], c:0, e:"Die IMPDH-Hemmung blockiert die de-novo-Purinsynthese, auf die Lymphozyten angewiesen sind."},
    {s:20, q:"Welcher Test ist vor Beginn einer Dapson-Therapie zwingend?", o:["G6PD-Aktivität","TPMT-Aktivität","HLA-B*57:01","Ausschliesslich Quantiferon"], c:0, e:"Ein G6PD-Mangel prädisponiert für eine schwere Hämolyse unter Dapson."},
    {s:20, q:"Welches Monitoring ist unter Hydroxychloroquin essenziell?", o:["Jährliche Lungenfunktion","Augenärztliche Kontrolle (Retinopathie)","Knochendichtemessung","Schilddrüsen-Szintigrafie"], c:1, e:"Wegen möglicher irreversibler Makulopathie Baseline und jährliche Kontrolle ab dem 5. Jahr."},
    {s:20, q:"Was ist das molekulare Ziel von Dupilumab?", o:["IL-17A","IL-4-Rezeptor-α","IL-23 (p19)","TNF-α"], c:1, e:"Dupilumab blockiert IL-4Rα und damit die IL-4/IL-13-vermittelte Th2-Achse."},
    {s:20, q:"Welche UAW ist unter Dupilumab am häufigsten?", o:["Konjunktivitis","Nephrotoxizität","Hyperpigmentierung","Agranulozytose"], c:0, e:"Die (Blepharo-)Konjunktivitis ist die häufigste UAW unter Dupilumab."},
    {s:20, q:"Welches Screening ist – anders als vor den meisten Biologika/Immunsuppressiva – vor Dupilumab NICHT obligat?", o:["Latente Tuberkulose","HIV","HBV","HCV"], c:0, e:"Dupilumab erhöht das Tbc-Reaktivierungsrisiko nicht; ein Tbc-Screening ist nicht zwingend."},
    {s:20, q:"Wie wirkt Omalizumab bei chronischer spontaner Urtikaria?", o:["Bindung an IL-5","Bindung an freies IgE","Blockade der H1-Rezeptoren","Hemmung der Mastzell-Tryptase"], c:1, e:"Omalizumab bindet freies IgE und verhindert dessen Bindung an FcεRI."},
    {s:20, q:"Warum gilt Certolizumab pegol als bevorzugter TNF-Blocker in der Schwangerschaft?", o:["Es ist oral verfügbar","Es ist ein Fab-Fragment ohne Fc → minimaler Plazentatransfer","Es hat keine UAW","Es ist ein IL-23-Hemmer"], c:1, e:"Ohne Fc-Domäne wird es kaum aktiv über die Plazenta transportiert."},
    {s:20, q:"Bimekizumab unterscheidet sich von Secukinumab dadurch, dass es zusätzlich blockiert:", o:["IL-17F","IL-23 (p19)","TNF-α","IL-4"], c:0, e:"Bimekizumab neutralisiert IL-17A und IL-17F; Preis ist eine höhere Candidiasis-Rate."},
    {s:20, q:"Welche Untereinheit bindet Ustekinumab?", o:["p19 (nur IL-23)","p40 (IL-12 und IL-23)","IL-17A","IL-4Rα"], c:1, e:"Ustekinumab bindet p40, die gemeinsame Untereinheit von IL-12 und IL-23."},
    {s:20, q:"Welche Boxed Warning gilt als Klasseneffekt oraler JAK-Inhibitoren?", o:["Erhöhtes Risiko für MACE, VTE und Malignome","Irreversible Retinopathie","Ausschliesslich teratogene Extremitätenfehlbildungen","Zwingende Lungenfibrose"], c:0, e:"Klasseneffekt: schwere Infektionen, Thromboembolien, kardiovaskuläre Ereignisse und Malignome, v.a. bei Risikopatienten."},
    {s:20, q:"Welches Zielmolekül blockiert der Checkpoint-Inhibitor Ipilimumab?", o:["PD-1","PD-L1","CTLA-4","BRAF"], c:2, e:"Ipilimumab ist ein Anti-CTLA-4-Antikörper; Nivolumab und Pembrolizumab blockieren PD-1."}
  ];
  const tf = [
    {s:20, st:"Klasse-I-Kortikosteroide wie Hydrocortison sind im Gesicht und bei Kindern Mittel der Wahl.", c:true, e:"Korrekt – schwache Steroide minimieren das Atrophierisiko in sensiblen Arealen."},
    {s:20, st:"Clobetasolpropionat (Dermovate) ist ein Kortikosteroid der Wirkstärkeklasse II.", c:false, e:"Falsch – Clobetasolpropionat gehört zur Klasse IV (sehr stark)."},
    {s:20, st:"Die gleichzeitige Gabe von Isotretinoin und einem Tetrazyklin erhöht das Risiko eines Pseudotumor cerebri.", c:true, e:"Korrekt – diese Kombination ist wegen der idiopathischen intrakraniellen Hypertension kontraindiziert."},
    {s:20, st:"Nach Absetzen von Acitretin genügt bei Frauen eine Kontrazeption von einem Monat.", c:false, e:"Falsch – wegen der Etretinat-Bildung sind 3 Jahre sichere Kontrazeption erforderlich."},
    {s:20, st:"Tacrolimus wirkt topisch über die Hemmung der Squalenepoxidase.", c:false, e:"Falsch – Tacrolimus bindet FKBP12 und hemmt Calcineurin; die Squalenepoxidase ist das Ziel von Terbinafin."},
    {s:20, st:"Benzoylperoxid führt bei Cutibacterium acnes zu bakterieller Resistenz.", c:false, e:"Falsch – BPO wirkt über freie Radikale und erzeugt keine Resistenz."},
    {s:20, st:"Cotrimoxazol darf unter Methotrexat bedenkenlos gegeben werden.", c:false, e:"Falsch – Cotrimoxazol wirkt additiv folatantagonistisch und ist unter MTX kontraindiziert (Panzytopenie-Risiko)."},
    {s:20, st:"Die Kombination von Azathioprin mit Allopurinol erfordert eine deutliche Dosisreduktion des Azathioprins.", c:true, e:"Korrekt – Xanthinoxidase-Hemmung erhöht toxische Metaboliten; Dosis um ~75% reduzieren."},
    {s:20, st:"Vor Beginn einer Dapson-Therapie muss die G6PD-Aktivität bestimmt werden.", c:true, e:"Korrekt – bei G6PD-Mangel droht eine schwere Hämolyse."},
    {s:20, st:"Vor Dupilumab ist – wie vor Anti-TNF-Biologika – ein Tuberkulose-Screening zwingend.", c:false, e:"Falsch – Dupilumab erhöht das Tbc-Reaktivierungsrisiko nicht, ein Tbc-Screening ist nicht obligat."},
    {s:20, st:"Certolizumab pegol ist bei Kinderwunsch und Schwangerschaft der bevorzugte TNF-Blocker.", c:true, e:"Korrekt – als Fab-Fragment ohne Fc-Domäne ist der Plazentatransfer minimal."},
    {s:20, st:"Secukinumab kann eine chronisch-entzündliche Darmerkrankung verschlechtern.", c:true, e:"Korrekt – IL-17A-Blockade kann eine CED aggravieren; entsprechende Vorsicht ist geboten."},
    {s:20, st:"Bimekizumab blockiert ausschliesslich IL-17A.", c:false, e:"Falsch – Bimekizumab blockiert IL-17A und IL-17F, mit höherer Candidiasis-Rate."},
    {s:20, st:"Guselkumab bindet die p40-Untereinheit von IL-12 und IL-23.", c:false, e:"Falsch – Guselkumab bindet p19 (selektiv IL-23); p40 ist das Ziel von Ustekinumab."},
    {s:20, st:"Orale JAK-Inhibitoren tragen eine Boxed Warning für venöse Thromboembolien und kardiovaskuläre Ereignisse.", c:true, e:"Korrekt – dies ist ein Klasseneffekt neben Infektionen und Malignomen."},
    {s:20, st:"Vor Beginn eines JAK-Inhibitors wird die rekombinante Herpes-zoster-Impfung (Shingrix) empfohlen.", c:true, e:"Korrekt – JAK-Inhibitoren fördern die VZV-Reaktivierung; die Zoster-Impfung erfolgt vorzugsweise vorher."},
    {s:20, st:"BRAF-Inhibitoren können kutane Plattenepithelkarzinome und Keratoakanthome auslösen.", c:true, e:"Korrekt – durch paradoxe MAPK-Aktivierung; die Kombination mit einem MEK-Inhibitor reduziert dies."},
    {s:20, st:"Vismodegib kann in der Schwangerschaft unbedenklich eingesetzt werden.", c:false, e:"Falsch – der Hedgehog-Inhibitor Vismodegib ist streng teratogen; sichere Kontrazeption ist obligat."}
  ];
  const cloze = [
    {s:20, parts:["Unter Methotrexat wird immer ","BLANK"," (5 mg, 1–2 Tage nach der MTX-Gabe) substituiert."], a:["Folsäure"]},
    {s:20, parts:["Vor Beginn von Azathioprin muss die ","BLANK","-Aktivität bestimmt werden."], a:["TPMT"]},
    {s:20, parts:["Vor einer Dapson-Therapie ist die Bestimmung der ","BLANK","-Aktivität obligat, um eine Hämolyse zu vermeiden."], a:["G6PD"]},
    {s:20, parts:["Isotretinoin erfordert eine sichere Kontrazeption von 1 Monat vor bis ","BLANK"," Monat nach Therapieende."], a:["1"]},
    {s:20, parts:["Nach Acitretin muss über ","BLANK"," Jahre sicher verhütet werden."], a:["3"]},
    {s:20, parts:["Dupilumab hemmt IL-4/IL-13 über die ","BLANK","-Kette; Nemolizumab blockiert den ","BLANK","-Rezeptor A."], a:["IL-4-Rezeptor-α","IL-31"]},
    {s:20, parts:["Ustekinumab richtet sich gegen die Untereinheit ","BLANK",", die IL-12 und IL-23 gemeinsam ist."], a:["p40"]},
    {s:20, parts:["Clobetasolpropionat ist ein Kortikosteroid der Wirkstärkeklasse ","BLANK"," (sehr stark)."], a:["IV"]},
    {s:20, parts:["Bei latenter Tuberkulose wird vor einer Anti-TNF-Therapie eine Prophylaxe mit ","BLANK"," begonnen."], a:["Isoniazid"]},
    {s:20, parts:["Vismodegib hemmt ","BLANK"," im Hedgehog-Signalweg und wird beim fortgeschrittenen Basalzellkarzinom eingesetzt."], a:["Smoothened"]}
  ];
  const match = [
    {s:20, t:"Biologikum ↔ molekulares Ziel", p:[["Dupilumab","IL-4-Rezeptor-α"],["Secukinumab","IL-17A"],["Bimekizumab","IL-17A und IL-17F"],["Ustekinumab","p40 (IL-12/23)"],["Guselkumab","p19 (IL-23)"],["Omalizumab","freies IgE"]]},
    {s:20, t:"Immunsuppressivum ↔ molekulares Target/Enzym", p:[["Methotrexat","Dihydrofolat-Reduktase"],["Ciclosporin","Calcineurin (via Cyclophilin)"],["Azathioprin","Purinsynthese (über 6-Mercaptopurin)"],["Mycophenolat-Mofetil","IMPDH"],["Apremilast","Phosphodiesterase 4"]]},
    {s:20, t:"Wirkstoff ↔ obligate Kontrolle vor/während Therapie", p:[["Azathioprin","TPMT-Aktivität"],["Dapson","G6PD-Aktivität"],["Hydroxychloroquin","augenärztliche Makula-Kontrolle"],["Isotretinoin","monatliches β-HCG"],["Methotrexat","Leberwerte und Tbc/HBV-Screening"]]},
    {s:20, t:"Antimykotikum ↔ Wirkmechanismus", p:[["Terbinafin","Squalenepoxidase-Hemmung"],["Fluconazol / Itraconazol","14α-Demethylase-Hemmung (Azol)"],["Nystatin","Bindung an Ergosterol (Polyen)"],["Amorolfin","Morpholin (Nagellack)"],["Ciclopiroxolamin","Hydroxypyridon"]]},
    {s:20, t:"Topisches Kortikosteroid ↔ Wirkstärkeklasse", p:[["Hydrocortison","Klasse I (schwach)"],["Clobetasolbutyrat (Emovate)","Klasse II (mittelstark)"],["Mometasonfuroat (Elocom)","Klasse III (stark)"],["Fluticasonpropionat (Cutivate)","Klasse III (stark)"],["Clobetasolpropionat (Dermovate)","Klasse IV (sehr stark)"]]},
    {s:20, t:"Zielgerichtetes Molekül ↔ Kinase/Enzym", p:[["Upadacitinib","JAK1"],["Baricitinib","JAK1/2"],["Abrocitinib","JAK1"],["Deucravacitinib","TYK2"],["Ruxolitinib (topisch)","JAK1/2"]]},
    {s:20, t:"Dermatoonkologische Systemtherapie ↔ Target", p:[["Ipilimumab","CTLA-4"],["Nivolumab / Pembrolizumab","PD-1"],["Vemurafenib / Dabrafenib","BRAF (V600)"],["Trametinib / Cobimetinib","MEK"],["Vismodegib","Smoothened (SMO)"]]},
    {s:20, t:"Wirkstoff ↔ charakteristische UAW/Monitoring", p:[["Ciclosporin","Nephrotoxizität und Gingivahyperplasie"],["Minocyclin","Hyperpigmentierung und DILE"],["Hydroxychloroquin","Retinopathie"],["Terbinafin","Geschmacksstörung"],["Dapson","Methämoglobinämie/Hämolyse"],["Isotretinoin","Cheilitis und Hypertriglyzeridämie"]]}
  ];
  const freetext = [
    {s:20, q:"Erläutern Sie das Vorgehen bei einer Isotretinoin-Therapie bei einer gebärfähigen Frau: Teratogenität, Verhütungsprogramm, Laborkontrollen und Abbruchkriterien.", a:"Isotretinoin ist ein hochteratogenes Vitamin-A-Säure-Derivat (Retinoid-Embryopathie mit kraniofazialen, kardialen und ZNS-Fehlbildungen), daher in der Schwangerschaft absolut kontraindiziert. Vor Therapiebeginn erfolgt eine ausführliche Aufklärung und der Start des Schwangerschaftsverhütungsprogramms: zwei sichere Verhütungsmethoden gleichzeitig von 1 Monat vor bis 1 Monat nach Therapie, negativer Schwangerschaftstest vor Beginn und dann monatliches β-HCG, Einnahmebeginn typisch am 2.–3. Zyklustag. Laborchemisch werden Transaminasen und Nüchtern-Lipide (v.a. Triglyzeride) vor Beginn, nach 1 Monat und dann alle 3 Monate kontrolliert. Dosierung 0.3–0.5 mg/kg/Tag mit Ziel-Kumulativdosis 120–150 mg/kg. Abbruch- bzw. Interventionskriterien sind Schwangerschaft, Transaminasen persistierend >3× ULN, Triglyzeride >9 mmol/l (Pankreatitisgefahr) sowie relevante Depression/Suizidalität. Zusätzlich: kein gleichzeitiges Tetrazyklin (Pseudotumor cerebri), keine Blutspende während und 1 Monat nach Therapie, Aufklärung über Cheilitis/Xerose als sehr häufige UAW."},
    {s:20, q:"Welche Abklärungen und Impf-Überlegungen gehören vor Beginn einer systemischen Immunsuppression bzw. Biologika-Therapie in der Dermatologie, und wie geht man mit positiven Befunden um?", a:"Vor konventionellen Immunsuppressiva (MTX, Azathioprin, Ciclosporin, MMF) und den meisten Biologika/JAK-Inhibitoren wird ein Infektions-Screening durchgeführt: HBV (HBsAg, Anti-HBc, ggf. HBV-DNA), HCV, HIV sowie eine latente Tuberkulose mittels IGRA und Röntgen-Thorax. Bei latenter Tbc erfolgt eine INH-Prophylaxe (alternativ Rifampicin oder INH+RIF), begonnen mindestens 1 Monat vor einem Anti-TNF/Biologikum. Bei HBsAg-Positivität ist eine antivirale Therapie (z.B. Entecavir/Tenofovir) mit hepatologischer Anbindung erforderlich, bei HCV eine hepatologische Mitbetreuung. Substanzspezifische Basisuntersuchungen ergänzen: TPMT vor Azathioprin, G6PD vor Dapson, augenärztliche Baseline vor Hydroxychloroquin, Nierenfunktion/Blutdruck vor Ciclosporin, β-HCG bei gebärfähigen Frauen. Impfungen: Totimpfstoffe möglichst vor Therapiebeginn komplettieren; unter laufender Immunsuppression sind Lebendimpfungen kontraindiziert; vor JAK-Inhibitoren wird die rekombinante Zoster-Impfung (Shingrix) empfohlen. Wichtige Ausnahme: Dupilumab benötigt kein obligates Tbc-Screening, da es das Reaktivierungsrisiko nicht erhöht."}
  ];
  const img = [
    {s:20, cap:"Wirkstärkeklassen topischer Kortikosteroide (Breite = Potenz)", q:"Zu welcher Wirkstärkeklasse gehört Clobetasolpropionat (Dermovate)?", o:["Klasse I (schwach)","Klasse II (mittelstark)","Klasse III (stark)","Klasse IV (sehr stark)"], c:3, e:"Clobetasolpropionat ist ein Klasse-IV-Steroid (sehr stark), max. 2 Wochen und ≤50 g/Woche, nicht im Gesicht.", svg:`<svg viewBox="0 0 300 262" xmlns="http://www.w3.org/2000/svg"><text x="14" y="22" font-size="13" fill="#1B1A18" font-family="sans-serif">Topische Kortikosteroide – Wirkstärke</text><rect x="20" y="40" width="90" height="30" fill="#7d9b76" stroke="#374151" stroke-width="1.5"/><text x="26" y="60" font-size="10" fill="#1B1A18" font-family="sans-serif">Klasse I – Hydrocortison</text><rect x="20" y="88" width="140" height="30" fill="#c9a24b" stroke="#374151" stroke-width="1.5"/><text x="26" y="108" font-size="10" fill="#1B1A18" font-family="sans-serif">Klasse II – Clobetasolbutyrat</text><rect x="20" y="136" width="195" height="30" fill="#c26a4a" stroke="#374151" stroke-width="1.5"/><text x="26" y="156" font-size="10" fill="#1B1A18" font-family="sans-serif">Klasse III – Mometason (Elocom)</text><rect x="20" y="184" width="255" height="30" fill="#B43A2E" stroke="#374151" stroke-width="1.5"/><text x="26" y="204" font-size="10" fill="#ffffff" font-family="sans-serif">Klasse IV – Clobetasolpropionat</text><text x="20" y="238" font-size="10" fill="#374151" font-family="sans-serif">Balkenbreite = Wirkstärke (schwach bis sehr stark)</text></svg>`},
    {s:20, cap:"Psoriasis-Zytokinachse und Biologika-Targets", q:"Welche Zytokin-Untereinheit blockiert Ustekinumab (Stelara)?", o:["TNF-α","p40 (IL-12/23)","p19 (IL-23)","IL-17A"], c:1, e:"Ustekinumab bindet p40, die gemeinsame Untereinheit von IL-12 und IL-23; p19-Hemmer sind z.B. Guselkumab/Risankizumab, IL-17A-Hemmer z.B. Secukinumab.", svg:`<svg viewBox="0 0 330 296" xmlns="http://www.w3.org/2000/svg"><text x="12" y="20" font-size="12" fill="#1B1A18" font-family="sans-serif">Psoriasis: Zytokinachse und Biologika</text><rect x="20" y="36" width="130" height="30" rx="4" fill="#3b4a6b" stroke="#1B1A18" stroke-width="1.5"/><text x="30" y="55" font-size="11" fill="#ffffff" font-family="sans-serif">TNF-α</text><text x="160" y="55" font-size="9" fill="#374151" font-family="sans-serif">Adalimumab, Infliximab</text><rect x="20" y="76" width="130" height="30" rx="4" fill="#7d9b76" stroke="#1B1A18" stroke-width="1.5"/><text x="30" y="95" font-size="11" fill="#ffffff" font-family="sans-serif">IL-12/23 (p40)</text><text x="160" y="95" font-size="9" fill="#374151" font-family="sans-serif">Ustekinumab</text><rect x="20" y="116" width="130" height="30" rx="4" fill="#c9a24b" stroke="#1B1A18" stroke-width="1.5"/><text x="30" y="135" font-size="11" fill="#1B1A18" font-family="sans-serif">IL-23 (p19)</text><text x="160" y="135" font-size="9" fill="#374151" font-family="sans-serif">Guselkumab, Risankizumab</text><rect x="20" y="156" width="130" height="30" rx="4" fill="#B43A2E" stroke="#1B1A18" stroke-width="1.5"/><text x="30" y="175" font-size="11" fill="#ffffff" font-family="sans-serif">IL-17A</text><text x="160" y="175" font-size="9" fill="#374151" font-family="sans-serif">Secukinumab, Ixekizumab</text><line x1="85" y1="186" x2="85" y2="214" stroke="#374151" stroke-width="1.5"/><polygon points="85,222 80,212 90,212" fill="#374151"/><rect x="20" y="224" width="230" height="30" rx="4" fill="#e6ddd0" stroke="#1B1A18" stroke-width="1.5"/><text x="30" y="243" font-size="10" fill="#1B1A18" font-family="sans-serif">Keratinozyten-Proliferation / Plaque</text></svg>`}
  ];

  FLASH.push(...flash);
  MC.push(...mc);
  TF.push(...tf);
  CLOZE.push(...cloze);
  MATCH.push(...match);
  FREETEXT.push(...freetext);
  IMG.push(...img);
})();
