/* Dermaapp – Sektion 3: Papulosquamöse und ekzematöse Dermatosen. Auto-generiert aus Facharzt-Unterlagen. */
(function () {
  const flash = [
    {s:3, q:"Wie lange dauert die Transitzeit (Reifung) der Keratinozyten bei Psoriasis im Vergleich zur normalen Epidermis?", a:"Normal ca. 28 Tage (4 Wochen); bei Psoriasis auf ca. 36 Stunden verkürzt als Folge der Hyperproliferation bei gestörter Differenzierung."},
    {s:3, q:"Wofür steht das Akronym SAPHO, das mit der Psoriasis pustulosa palmoplantaris assoziiert ist?", a:"Synovitis, Akne, Pustulose, Hyperostose, Osteitis."},
    {s:3, q:"Wofür stehen DIRA und DITRA im Kontext der pustulösen Psoriasis?", a:"DIRA = Deficiency of IL-1 receptor antagonist; DITRA = Deficiency of IL-36 receptor antagonist; beides autoinflammatorische Syndrome, u.a. mit generalisierter pustulöser Psoriasis assoziiert."},
    {s:3, q:"Was ist die Impetigo herpetiformis?", a:"Eine generalisierte pustulöse Psoriasis, die in der Schwangerschaft auftritt (nicht infektiös, kein Herpes)."},
    {s:3, q:"Wodurch entsteht das Nagel-Pitting (Grübchennägel) bei der Psoriasis unguium?", a:"Durch parakeratotische Foci in der proximalen Nagelmatrix, die als kleine Grübchen in der Nagelplatte sichtbar werden."},
    {s:3, q:"Was ist der häufigste Gelenkbefallstyp der Psoriasis-Arthritis und welche Gelenke sind typisch bzw. ausgespart?", a:"Asymmetrische Oligoarthritis; DIP und PIP betroffen, Daktylitis (Wurstfinger), MCP typischerweise ausgespart."},
    {s:3, q:"Welche Biologika-Klasse zeigt langfristig das beste PASI-Ansprechen bei Plaque-Psoriasis?", a:"Die Anti-IL-23-Antikörper (z.B. Risankizumab, Guselkumab); langsamerer, aber anhaltend bester Effekt gegenüber Anti-IL-17."},
    {s:3, q:"Spesolimab: Target und Indikation?", a:"Anti-IL-36-Rezeptor-Antikörper; eingesetzt beim Schub der generalisierten pustulösen Psoriasis."},
    {s:3, q:"Wie präsentieren sich die follikulären Hyperkeratosen an den Fingerrücken bei Pityriasis rubra pilaris?", a:"Als spitze follikuläre Papeln, die an eine Muskatnuss-Raffel (nutmeg grater) erinnern."},
    {s:3, q:"Was ist die First-Line-Systemtherapie der Pityriasis rubra pilaris?", a:"Orale Retinoide (Acitretin oder Isotretinoin 0.5 bis 2 mg/kg KG); Ansprechen erst nach 3 bis 6 Monaten."},
    {s:3, q:"Wie unterscheidet man Parapsoriasis en petites von en grandes plaques, und welche Form ist eine Präkanzerose?", a:"Petites kleiner als 5 cm, grandes grösser als 5 cm. Die grossherdige Form (en grandes plaques) ist eine Präkanzerose mit ca. 7 bis 14% Übergang in eine Mycosis fungoides."},
    {s:3, q:"Warum wird die Parapsoriasis en grandes plaques wie eine Mycosis fungoides im Stadium IA behandelt?", a:"Weil sie klinisch und histologisch nicht sicher von einer frühen MF abgegrenzt werden kann."},
    {s:3, q:"Nenne die typische Hierarchie der Nahrungsmittelallergene im Rahmen des Atopic March.", a:"Ei > Milch, Erdnuss/Baumnuss, Schalentiere/Fisch > Soja > Weizen."},
    {s:3, q:"Welche zwei Proteasen bauen bei der atopischen Dermatitis Desmoglein-1 ab, und welcher Inhibitor ist vermindert?", a:"Kallikrein 5 und 7 bauen Desmoglein-1 ab; der Protease-Inhibitor LEKTI ist vermindert, wodurch die Korneozyten-Kohäsion gestört wird."},
    {s:3, q:"Was ist das Hertoghe-Zeichen bei atopischer Diathese?", a:"Ausdünnung oder Fehlen der lateralen Augenbrauen."},
    {s:3, q:"Ab welchem Punktwert gelten SCORAD und EASI jeweils als schwere atopische Dermatitis?", a:"SCORAD ≥ 50 (von maximal 103 Punkten); EASI ≥ 21.1."},
    {s:3, q:"Nenne die wichtigsten Kontraindikationen bzw. CAVE für Dupilumab.", a:"Hypereosinophilie (Gefahr von Vaskulitis, eosinophiler Pneumonie, Asthmaexazerbation), Helminthose und unbehandeltes Asthma."},
    {s:3, q:"Nemolizumab: Target und Leitsymptom, das damit adressiert wird?", a:"Anti-IL-31-Antikörper; adressiert vor allem den starken Juckreiz der atopischen Dermatitis."},
    {s:3, q:"Welche wesentlichen Risiken sind bei JAK-Inhibitoren in der AD-Therapie zu beachten?", a:"Erhöhtes Tumorrisiko (Lymphom, NMSC, Lungenkarzinom bei Rauchern) sowie erhöhtes kardiovaskuläres und thromboembolisches Risiko (TVT, LE, Myokardinfarkt, Apoplex); Zulassung ab 18 Jahren."},
    {s:3, q:"Welche Lichen-ruber-Variante führt zu einer vernarbenden Alopezie, und wie heisst die frontale Sonderform?", a:"Lichen planopilaris; die frontale Sonderform ist die Frontal fibrosierende Alopezie (Augenbrauen können mitbetroffen sein)."},
    {s:3, q:"Welche Lichen-ruber-Varianten tragen ein erhöhtes Risiko für ein Plattenepithelkarzinom (SCC)?", a:"Der hypertrophe/verruköse LP sowie der mukosal-erosive LP (maligne Transformation ca. 0.2% pro Jahr)."},
    {s:3, q:"Wie verläuft eine Pityriasis rosea und wie wird sie behandelt?", a:"Selbstlimitierend mit Abheilung nach 6 bis 12 Wochen; Therapie meist nur symptomatisch (rückfettend, Antipruriginosa, ggf. UVBnb)."},
    {s:3, q:"Erreger, Prädilektion und wichtige Assoziationen des seborrhoischen Ekzems?", a:"Malassezia (u.a. M. furfur) in talgdrüsenreichen Arealen (Capillitium, Gesicht, prästernal); ausgeprägt bei HIV, Immunsuppression und M. Parkinson; M>W."},
    {s:3, q:"Dyshidrosiformes Handekzem (Pompholyx): typische Klinik und welche neue topische Therapie?", a:"Tief sitzende, feste Bläschen an den Fingerseiten und palmar; neu der topische JAK-Inhibitor Delgocitinib (Anzupgo), von der KK bei Verlauf über 3 Monate nach TCS übernommen."},
    {s:3, q:"Pathogenese des Stauungsekzems und typische chronische Komplikation?", a:"Venöse Insuffizienz führt zu Mikroangiopathie mit Hämosiderin-Ablagerung und Entzündung; chronisch entsteht eine Lipodermatosklerose mit Wine-bottle-Konfiguration."},
    {s:3, q:"Definition der Erythrodermie und typische systemische Manifestationen?", a:"Generalisierte Rötung und Schuppung über 90% der Körperoberfläche; systemisch periphere Ödeme, Tachykardie und gestörte Thermoregulation."}
  ];
  const mc = [
    {s:3, q:"Welcher Psoriasis-Subtyp ist potenziell lebensbedrohlich und geht mit Fieber, Gelenkschmerzen und Malaise einher?", o:["Psoriasis guttata","Generalisierte pustulöse Psoriasis (Typ von Zumbusch)","Psoriasis inversa","Nagelpsoriasis"], c:1, e:"Der Typ von Zumbusch ist eine generalisierte, schmerzhafte pustulöse Psoriasis mit Fieber und Malaise, lebensbedrohlich und ggf. mit DIRA/DITRA assoziiert."},
    {s:3, q:"Ein Psoriasis-Patient ist HLA-B27-positiv. Welche Assoziation ist dadurch am ehesten erhöht?", o:["Axiale Psoriasis-Arthritis, CED und Uveitis","Nickel-Kontaktallergie","Vitiligo","Rosazea"], c:0, e:"Die axiale PsA ist mit HLA-B27, chronisch-entzündlicher Darmerkrankung und Uveitis assoziiert."},
    {s:3, q:"Welches Präparat bietet langfristig tendenziell das beste PASI-Ansprechen?", o:["Secukinumab","Etanercept","Risankizumab","Apremilast"], c:2, e:"Anti-IL-23 (Risankizumab) zeigt das beste langfristige PASI-Ansprechen; Anti-IL-17 wirkt rascher, ist aber langfristig unterlegen."},
    {s:3, q:"Welche Substanzklasse wird bei Psoriasis derzeit vor allem bei begleitender Psoriasis-Arthritis und nicht als Standard der Plaque-Psoriasis eingesetzt?", o:["JAK-Inhibitoren","Anti-IL-23","Anti-IL-17","Vitamin-D3-Analoga"], c:0, e:"JAK-Inhibitoren werden bei PsA eingesetzt; für die Plaque-Psoriasis laufen noch Phase-III-Studien."},
    {s:3, q:"Was ist die topische First-Line-Therapie der Nagelpsoriasis?", o:["Topische Klasse-III-Kortikosteroide plus Vitamin-D3-Analoga (z.B. Daivobet)","Ketoconazol-Creme","Topisches Aciclovir","Systemisches Terbinafin"], c:0, e:"TCS Klasse III plus Vitamin-D3-Analoga (Daivobet) 2x/Tag sind First Line; intraläsionäres Triamcinolon ist schmerzhaft."},
    {s:3, q:"Mit welchen Malignomen ist eine paraneoplastische Pityriasis rubra pilaris beschrieben?", o:["Nierenzell-, Bronchial- oder hepatozelluläres Karzinom","Kolonkarzinom","Mammakarzinom","Prostatakarzinom"], c:0, e:"Paraneoplastisch bei Nieren-CA, Bronchus-CA oder hepatozellulärem CA; der Typ VI ist HIV-assoziiert."},
    {s:3, q:"Wie hoch ist etwa das Risiko des Übergangs einer Parapsoriasis en grandes plaques in eine Mycosis fungoides?", o:["Unter 1%","ca. 7 bis 14%","ca. 50%","ca. 90%"], c:1, e:"Bei Nachweis monoklonaler CD4+ T-Zellen ca. 7 bis 14% Transformation in eine MF."},
    {s:3, q:"Welches Zytokin treibt neben IL-4 die Th2-Differenzierung und drosselt zusätzlich die Filaggrin-Produktion?", o:["IL-13","IL-17","IFN-γ","IL-23"], c:0, e:"IL-4 und IL-13 fördern die Th2-Differenzierung und IgE-Bildung und supprimieren die Filaggrin-Synthese; Angriffspunkt von Dupilumab, Tralokinumab und Lebrikizumab."},
    {s:3, q:"Ab welchem Alter ist Dupilumab zur Therapie der atopischen Dermatitis zugelassen?", o:["ab 6 Monaten","ab 6 Jahren","ab 12 Jahren","ab 18 Jahren"], c:0, e:"Dupilumab ist ab dem 6. Lebensmonat zugelassen."},
    {s:3, q:"Welcher JAK1-Inhibitor wird bei schwerer atopischer Dermatitis (ab 18 J.) mit 15 mg/Tag eingesetzt?", o:["Upadacitinib","Tralokinumab","Dupilumab","Nemolizumab"], c:0, e:"Upadacitinib (Rinvoq) ist ein JAK1-Inhibitor; Tralokinumab, Dupilumab und Nemolizumab sind Biologika."},
    {s:3, q:"Welcher Antikörper blockiert selektiv IL-13 und ist ab 18 Jahren zugelassen (Handelsname Adtralza)?", o:["Tralokinumab","Dupilumab","Nemolizumab","Omalizumab"], c:0, e:"Tralokinumab (Adtralza) ist ein Anti-IL-13-Antikörper, zugelassen ab 18 Jahren; Dupilumab blockiert IL-4Rα, Nemolizumab IL-31."},
    {s:3, q:"Welche bakterielle Fehlbesiedlung wird durch den gestörten sauren pH-Mantel bei AD begünstigt und verstärkt via Superantigene die Th2-Antwort?", o:["Staphylococcus aureus","Cutibacterium acnes","Malassezia furfur","Streptococcus pyogenes"], c:0, e:"Ohne Filaggrin-Abbauprodukte fehlt der saure pH-Mantel, sodass sich S. aureus vermehrt ansiedelt und dessen Superantigene die Th2-Inflammation anfachen."},
    {s:3, q:"Welche Lichen-ruber-Variante verursacht eine vernarbende Alopezie?", o:["Lichen planopilaris","Lichen ruber anularis","Lichen ruber pigmentosus","Lichen nitidus"], c:0, e:"Der Lichen planopilaris betrifft die Haarfollikel und führt zu einer vernarbenden Alopezie (Sonderform: Frontal fibrosierende Alopezie)."},
    {s:3, q:"Welche Lichen-ruber-Formen bergen das höchste Risiko für ein Plattenepithelkarzinom?", o:["Hypertropher/verruköser und mukosal-erosiver LP","Anularer LP","Linearer LP","LP pigmentosus"], c:0, e:"Der hypertrophe/verruköse und der mukosal-erosive LP können in ein SCC übergehen (mukosal ca. 0.2% pro Jahr)."},
    {s:3, q:"Herald Patch, gefolgt von einem Tannenbaum-Muster entlang der Langer-Linien: welche DD muss serologisch ausgeschlossen werden?", o:["Lues II (Syphilis)","Tinea corporis","Skabies","Erysipel"], c:0, e:"Die Pityriasis rosea ähnelt einer Lues II; eine Syphilis-Serologie ist bei atypischem Verlauf oder Palmoplantarbefall obligat."},
    {s:3, q:"Ein Säugling zeigt Erythem und Schuppung, die auch die Windelregion einbeziehen. Was ist am wahrscheinlichsten?", o:["Seborrhoisches Säuglingsekzem","Atopische Dermatitis","Psoriasis guttata","Skabies"], c:0, e:"Im Gegensatz zur infantilen AD (Aussparung der Windelregion) bezieht das seborrhoische Ekzem die Windelregion typischerweise ein."},
    {s:3, q:"Welche Aussage trifft auf die irritativ-toxische Kontaktdermatitis zu?", o:["Vermittelt durch das angeborene Immunsystem, ohne Streuphänomen","Typ-IV-Reaktion mit ausgeprägtem Streuphänomen","Benötigt zwingend eine vorherige Sensibilisierung","IgE-vermittelte Soforttypreaktion"], c:0, e:"Die irritativ-toxische KD (ca. 80% der Fälle) ist eine direkte zytotoxische Reaktion des angeborenen Immunsystems ohne Streuphänomen; die allergische KD ist Typ IV mit Streuphänomen."},
    {s:3, q:"Epikutantest: Erythem, Infiltrat und konfluierende Vesikel entsprechen welcher Bewertung?", o:["(+)","(++)","(+++)","fraglich (?)"], c:2, e:"+++ bedeutet Erythem, Infiltrat und konfluierende Vesikel (stärkste reguläre Reaktion)."},
    {s:3, q:"Welches Kontaktallergen findet sich typischerweise in Leder und Zement und kreuzreagiert häufig?", o:["Chromat","Kolophonium","Perubalsam","Thiomersal"], c:0, e:"Chromat (Chrom-VI) kommt in Leder und Zement vor; Nickel, Chromat und Kobalt zeigen häufig Kreuzreaktionen."},
    {s:3, q:"Welcher neue topische JAK-Inhibitor ist beim chronischen Handekzem (über 3 Monate, nach TCS) zugelassen?", o:["Delgocitinib (Anzupgo)","Tofacitinib","Baricitinib","Apremilast"], c:0, e:"Delgocitinib (Anzupgo) ist ein topischer JAK-Inhibitor; die KK übernimmt bei Bestehen über 3 Monaten und Vortherapie mit TCS."}
  ];
  const tf = [
    {s:3, st:"Bei der Psoriasis ist die Transitzeit der Keratinozyten auf ca. 36 Stunden verkürzt.", c:true, e:"Statt ca. 28 Tagen reifen die Keratinozyten in ca. 36 Stunden; Hyperproliferation bei gestörter Differenzierung."},
    {s:3, st:"Bei der Psoriasis-Arthritis sind die MCP-Gelenke typischerweise am stärksten betroffen.", c:false, e:"Falsch: MCP sind typischerweise ausgespart; charakteristisch sind DIP/PIP-Befall und Daktylitis."},
    {s:3, st:"Anti-IL-23-Biologika zeigen langfristig ein besseres PASI-Ansprechen als Anti-IL-17-Biologika.", c:true, e:"Anti-IL-17 wirkt rascher, Anti-IL-23 (z.B. Risankizumab) hat aber das beste langfristige Ansprechen."},
    {s:3, st:"Loss-of-function-Mutationen in IL36RN prädisponieren zur generalisierten pustulösen Psoriasis.", c:true, e:"IL36RN codiert den IL-36-Rezeptor-Antagonisten; sein Verlust führt zu ungebremster IL-36-Entzündung mit sterilen Pusteln."},
    {s:3, st:"Die Parapsoriasis en petites plaques ist eine obligate Präkanzerose mit hohem MF-Risiko.", c:false, e:"Falsch: die kleinherdige Form gilt als benigne; die en grandes plaques ist die Präkanzerose (7 bis 14% Übergang in MF)."},
    {s:3, st:"Bei der atopischen Dermatitis dominiert in der akuten Phase eine Th2-, in der chronischen Phase eine Th1-Antwort.", c:true, e:"Biphasische Immunantwort: akut Th2 (IL-4/5/13/31), chronisch Verschiebung Richtung Th1."},
    {s:3, st:"Tralokinumab und Lebrikizumab sind beide gegen IL-13 gerichtet.", c:true, e:"Beide sind Anti-IL-13-Antikörper; Tralokinumab ab 18 Jahren (Adtralza), Lebrikizumab ab 12 Jahren (Ebglyss)."},
    {s:3, st:"Die irritativ-toxische Kontaktdermatitis zeigt typischerweise ein ausgeprägtes Streuphänomen.", c:false, e:"Falsch: die toxische KD bleibt lokalisiert (kein Streuphänomen); das Streuphänomen ist typisch für die allergische Typ-IV-KD."},
    {s:3, st:"Beim Epikutantest spricht eine Crescendo-Reaktion (Zunahme über die Ablesezeit) für eine allergische Genese.", c:true, e:"Crescendo bedeutet allergisch (zunehmende Reaktion), Decrescendo irritativ (abnehmende Reaktion)."},
    {s:3, st:"Das seborrhoische Ekzem des Säuglings spart die Windelregion typischerweise aus.", c:false, e:"Falsch: im Gegensatz zur atopischen Dermatitis bezieht das seborrhoische Ekzem die Windelregion oft mit ein."}
  ];
  const cloze = [
    {s:3, parts:["Die generalisierte pustulöse Psoriasis vom Typ ", "BLANK", " ist lebensbedrohlich und geht mit Fieber und Malaise einher."], a:["Zumbusch"]},
    {s:3, parts:["Eine Systemtherapie der Psoriasis ist ab einer betroffenen Körperoberfläche (BSA) > ", "BLANK", " %, einem PASI > ", "BLANK", " oder einem DLQI > ", "BLANK", " indiziert."], a:["10","10","10"]},
    {s:3, parts:["Bei der atopischen Dermatitis drosseln die Th2-Zytokine IL-4 und ", "BLANK", " zusätzlich die Filaggrin-Produktion."], a:["IL-13"]},
    {s:3, parts:["Nemolizumab richtet sich gegen den juckreizvermittelnden Botenstoff ", "BLANK", "."], a:["IL-31"]},
    {s:3, parts:["Bei der reaktiven Arthritis zeigen sich plantar dicke, gelbe Krusten, das sogenannte ", "BLANK", "."], a:["Keratoderma blennorrhagicum"]},
    {s:3, parts:["Der Lichen planopilaris betrifft die Haarfollikel und führt zu einer ", "BLANK", " Alopezie."], a:["vernarbenden"]}
  ];
  const match = [
    {s:3, t:"Psoriasis-Systemtherapie ↔ Wirkmechanismus", p:[["Apremilast","PDE-4-Hemmer"],["Acitretin","Retinoid"],["Risankizumab","Anti-IL-23"],["Bimekizumab","Anti-IL-17A/F"],["Spesolimab","Anti-IL-36-Rezeptor"],["Dimethylfumarat","Fumarsäureester"]]},
    {s:3, t:"Atopische Dermatitis: Wirkstoff ↔ Zielstruktur", p:[["Dupilumab","IL-4Rα (IL-4/IL-13)"],["Tralokinumab","IL-13"],["Nemolizumab","IL-31"],["Upadacitinib","JAK1"],["Baricitinib","JAK1/2"]]},
    {s:3, t:"Kontaktallergen ↔ typische Quelle", p:[["Nickel","Modeschmuck/Piercing"],["Chromat","Leder und Zement"],["Kolophonium","Geigenharz/Leder"],["Perubalsam","Duftstoffe/Kosmetika"],["Thiomersal","Impfstoffe/Konservierung"],["Kobalt","Keramik/Haarfärbemittel"]]}
  ];
  const freetext = [
    {s:3, q:"Erläutern Sie die immunologische Pathogenese der Plaque-Psoriasis (dendritische Zellen, T-Helfer-Achsen, Schlüsselzytokine) und leiten Sie daraus die Angriffspunkte der modernen Biologika ab.", a:"Ein Trigger (Infekt, Trauma, Medikament) stresst die Keratinozyten, die DNA und RNA freisetzen. Dadurch aktivierte dendritische Zellen produzieren IFN-alpha und wandern in die Lymphknoten, wo sie unter Freisetzung von TNF, IL-12 und IL-23 ein Antigen präsentieren. Naive T-Zellen differenzieren zu Th1, Th17 und Th22. Th1-Zellen sezernieren IFN-gamma und TNF-alpha, Th17-Zellen IL-17A und IL-17F sowie IL-22. IL-17 treibt die Keratinozyten-Proliferation und lockt über Chemokine Neutrophile ins Stratum corneum (Munro-Mikroabszesse); zusätzlich bilden Keratinozyten VEGF (Angiogenese). Es entsteht ein Teufelskreis mit verkürzter Transitzeit von ca. 36 Stunden. Angriffspunkte der Systemtherapie: TNF-alpha (Adalimumab, Etanercept, Infliximab, Certolizumab), IL-12/23-p40 (Ustekinumab), IL-23-p19 (Risankizumab, Guselkumab, Tildrakizumab), IL-17A (Secukinumab, Ixekizumab), IL-17A und F (Bimekizumab), IL-17-Rezeptor (Brodalumab) sowie intrazellulär PDE-4 (Apremilast) und IL-36-Rezeptor (Spesolimab bei pustulöser Form)."},
    {s:3, q:"Ein 55-jähriger Mann stellt sich mit einer Erythrodermie (über 90% der Körperoberfläche) vor. Nennen Sie die wichtigsten Differentialdiagnosen und das diagnostische Vorgehen.", a:"Definition: generalisierte Rötung und Schuppung über 90% der Körperoberfläche mit systemischen Folgen (periphere Ödeme, Tachykardie, gestörte Thermoregulation, Flüssigkeits- und Proteinverlust). Häufige Differentialdiagnosen: Psoriasis, atopische Dermatitis, Arzneimittelreaktionen (DRESS, SJS/TEN, Arzneimittelexanthem u.a. auf Vancomycin oder Ceftriaxon) sowie idiopathische Erythrodermie (v.a. ältere Männer). Seltener: kutanes T-Zell-Lymphom (Sézary-Syndrom vor Mycosis fungoides), allergische Kontaktdermatitis, Pityriasis rubra pilaris, paraneoplastisch, Skabies, GvHD, bullöse und Pemphigus-Erkrankungen, Ichthyose. Diagnostik: Anamnese und Medikamentenanamnese; Labor (Blutbild mit Differenzierung, Elektrolyte, Nieren- und Leberwerte, CRP, Gesamt-IgE); mikrobiologische Abstriche (Bakterien, Pilze); wiederholte Hautbiopsien zum Ausschluss oder Nachweis einer MF; bei Lymphadenopathie Lymphknotenbiopsie, ggf. Sonografie oder PET bei Malignomverdacht. Supportiv Wärme- und Flüssigkeitsmanagement."}
  ];
  const img = [
    {s:3, cap:"Nagelbefund", q:"Welches Nagelzeichen (ölfleckartige, lachsfarbene Verfärbung unter der Nagelplatte) ist hier markiert und spricht für eine Nagelpsoriasis?",
      o:["Ölfleck-Phänomen (salmon patch)","Splitterblutung","Beau-Linie","Koilonychie"], c:0,
      e:"Der lachsfarbene Ölfleck entsteht durch Exozytose von Leukozyten unter die Nagelplatte; daneben sichtbar sind Pitting (proximale Matrix) und distale Onycholyse.",
      svg:`<svg viewBox="0 0 280 220" xmlns="http://www.w3.org/2000/svg"><rect x="0" y="0" width="280" height="220" fill="#f8fafc"/><path d="M90,205 L90,95 Q90,42 140,42 Q190,42 190,95 L190,205 Z" fill="#fde5d3" stroke="#d6a184" stroke-width="2"/><rect x="105" y="60" width="70" height="112" rx="26" ry="30" fill="#fcece0" stroke="#c9a08a" stroke-width="2"/><ellipse cx="140" cy="104" rx="22" ry="15" fill="#e8a04b" opacity="0.55"/><g fill="#9a6b4f"><circle cx="122" cy="80" r="3"/><circle cx="138" cy="76" r="3"/><circle cx="154" cy="82" r="3"/><circle cx="128" cy="92" r="3"/><circle cx="150" cy="94" r="3"/><circle cx="140" cy="86" r="3"/></g><g stroke="#b23b3b" stroke-width="1.5"><line x1="126" y1="120" x2="126" y2="132"/><line x1="140" y1="122" x2="140" y2="134"/><line x1="154" y1="120" x2="154" y2="132"/></g><rect x="105" y="60" width="70" height="16" rx="8" fill="#ffffff" stroke="#c9a08a" stroke-width="1.5"/><text x="60" y="28" font-size="11" fill="#6b7280" font-family="sans-serif">Nagelbefund bei Psoriasis</text></svg>`},
    {s:3, cap:"Hand bei Psoriasis-Arthritis", q:"Wie nennt man die diffuse Schwellung eines gesamten Fingers (Wurstfinger) bei Psoriasis-Arthritis?",
      o:["Daktylitis","Arthritis mutilans","Gichttophus","Heberden-Knoten"], c:0,
      e:"Die Daktylitis (Wurstfinger oder -zehe) ist typisch für die Psoriasis-Arthritis, häufig mit DIP/PIP-Befall.",
      svg:`<svg viewBox="0 0 280 260" xmlns="http://www.w3.org/2000/svg"><rect x="0" y="0" width="280" height="260" fill="#f8fafc"/><rect x="90" y="150" width="110" height="92" rx="24" fill="#fde5d3" stroke="#d6a184" stroke-width="2"/><rect x="96" y="70" width="16" height="90" rx="8" fill="#fde5d3" stroke="#d6a184" stroke-width="2"/><rect x="120" y="55" width="16" height="105" rx="8" fill="#fde5d3" stroke="#d6a184" stroke-width="2"/><rect x="146" y="52" width="30" height="112" rx="15" fill="#e57373" stroke="#c0392b" stroke-width="2"/><rect x="184" y="72" width="16" height="88" rx="8" fill="#fde5d3" stroke="#d6a184" stroke-width="2"/><rect x="196" y="150" width="60" height="18" rx="9" fill="#fde5d3" stroke="#d6a184" stroke-width="2" transform="rotate(20 196 150)"/><text x="140" y="38" font-size="12" fill="#c0392b" font-family="sans-serif" text-anchor="middle">Wurstfinger</text></svg>`},
    {s:3, cap:"Untersuchung am Rücken", q:"Welche Untersuchung ist dargestellt (Testkammern am Rücken, Ablesung nach 48/72 h zur Abklärung einer Typ-IV-Sensibilisierung)?",
      o:["Epikutantest (Patch-Test)","Prick-Test","Intrakutantest","Tzanck-Test"], c:0,
      e:"Der Epikutantest weist eine Typ-IV-Kontaktsensibilisierung nach; Reaktionen werden nach 48/72 h als ?/+/++/+++ abgelesen (Crescendo = allergisch).",
      svg:`<svg viewBox="0 0 280 300" xmlns="http://www.w3.org/2000/svg"><rect x="0" y="0" width="280" height="300" fill="#f8fafc"/><rect x="125" y="18" width="30" height="26" fill="#fde5d3" stroke="#d6a184" stroke-width="2"/><path d="M80,42 L200,42 L215,112 L205,262 L75,262 L65,112 Z" fill="#fde5d3" stroke="#d6a184" stroke-width="2"/><g fill="none" stroke="#4b5563" stroke-width="1.5"><rect x="100" y="90" width="24" height="24"/><rect x="128" y="90" width="24" height="24"/><rect x="156" y="90" width="24" height="24"/><rect x="100" y="118" width="24" height="24"/><rect x="128" y="118" width="24" height="24"/><rect x="156" y="118" width="24" height="24"/><rect x="100" y="146" width="24" height="24"/><rect x="128" y="146" width="24" height="24"/><rect x="156" y="146" width="24" height="24"/></g><rect x="128" y="90" width="24" height="24" fill="#f6c453" opacity="0.7"/><rect x="156" y="118" width="24" height="24" fill="#e57373" opacity="0.8"/><rect x="100" y="146" width="24" height="24" fill="#c0392b" opacity="0.85"/><text x="135" y="106" font-size="10" fill="#3f3f46" font-family="sans-serif">+</text><text x="161" y="134" font-size="10" fill="#ffffff" font-family="sans-serif">++</text><text x="102" y="162" font-size="10" fill="#ffffff" font-family="sans-serif">+++</text><text x="66" y="286" font-size="11" fill="#6b7280" font-family="sans-serif">Testkammern am Rücken, Ablesung 48/72 h</text></svg>`}
  ];

  FLASH.push(...flash);
  MC.push(...mc);
  TF.push(...tf);
  CLOZE.push(...cloze);
  MATCH.push(...match);
  FREETEXT.push(...freetext);
  IMG.push(...img);
})();
