/* Dermaapp – Sektion 5: Blasenbildende / bullöse Erkrankungen. Auto-generiert aus Facharzt-Unterlagen. */
(function () {
  const flash = [
    {s:5, q:"Warum ist ein unbehandelter Pemphigus vulgaris potenziell lebensbedrohlich?", a:"Grossflächige intraepidermale Erosionen führen analog zu einer Verbrennung zu Flüssigkeits- und Eiweissverlust, Elektrolytentgleisung sowie bakterieller Superinfektion bis zur Sepsis."},
    {s:5, q:"In welcher epidermalen Schicht liegt die Akantholyse beim Pemphigus foliaceus und welche klinische Konsequenz hat das?", a:"Subkorneal im Stratum granulosum. Die Blasen sind sehr fragil, klinisch dominieren 'corn-flakes'-artige Krusten/Erosionen in seborrhoischen Arealen, Nikolsky I positiv, keine Schleimhautbeteiligung."},
    {s:5, q:"Was bezeichnet das Senear-Usher-Syndrom?", a:"Pemphigus erythematosus - ein auf Gesicht/seborrhoische Areale begrenzter Subtyp des Pemphigus foliaceus mit erhöhter Photosensitivität und ggf. positiven ANA (LE-Overlap)."},
    {s:5, q:"Was ist Fogo selvagem?", a:"Endemischer Pemphigus foliaceus (Anti-Dsg1), v.a. in Brasilien/Südamerika, assoziiert mit Bissen der schwarzen Kriebelmücke (Simulium); betrifft häufig Kinder und Adoleszente."},
    {s:5, q:"Warum ist die Rattenblase ein sensitives IIF-Substrat für den paraneoplastischen Pemphigus?", a:"Ihr Transitionalepithel ist reich an Plakinen (Envoplakin/Periplakin) und exprimiert kein Desmoglein, wodurch die für den PNP typischen plakingerichteten Auto-Antikörper nachweisbar werden."},
    {s:5, q:"Welche Malignome sind beim paraneoplastischen Pemphigus bei Kindern/Jugendlichen vs. Erwachsenen führend?", a:"Kinder/Jugendliche: M. Castleman. Erwachsene: Non-Hodgkin-Lymphom > CLL > M. Castleman, Thymom."},
    {s:5, q:"Welche pulmonale Komplikation bestimmt massgeblich die hohe Mortalität des paraneoplastischen Pemphigus?", a:"Bronchiolitis obliterans (entzündliche Vernarbung und Verschluss der Bronchiolen) bei ca. 30-40% der Patienten."},
    {s:5, q:"Wie präsentiert sich der Pemphigus herpetiformis und welches Antigen liegt meist vor?", a:"Erythematöse, urtikarielle Plaques mit gruppiert stehenden Vesikobullae (DH-ähnlich), histologisch eosinophile Spongiose; meist Anti-Dsg1. Es handelt sich um eine Pemphigus-Variante."},
    {s:5, q:"Nach welchem Schema wird Rituximab beim Pemphigus vulgaris dosiert?", a:"1 g i.v. an Tag 0 und Tag 14, ggf. Erhaltung mit 500-1000 mg alle 6 Monate; kombiniert mit degressivem Prednisolon."},
    {s:5, q:"Wie unterscheiden sich Nikolsky I und Nikolsky II?", a:"Nikolsky I: tangentialer Druck auf klinisch gesunde Haut löst die Epidermis ab (PV, PF, SSSS, TEN). Nikolsky II (Asboe-Hansen): laterale Verschieblichkeit einer bereits bestehenden Blase."},
    {s:5, q:"Wie entsteht und verläuft ein neonataler Pemphigus?", a:"Durch transplazentare Transmission maternaler Auto-Antikörper (v.a. PV > PF); selbstlimitierend, meist Rückbildung innerhalb von ca. 3 Wochen postpartal."},
    {s:5, q:"Welche Pustelkonfiguration ist typisch für den intraepidermalen neutrophilen IgA-Pemphigus und was ist die Therapie?", a:"'Sunflower'-artige (sonnenblumenartige) Anordnung der Pusteln; Therapie der Wahl ist Dapson."},
    {s:5, q:"Wie kann sich das bullöse Pemphigoid vor der Blasenbildung präsentieren?", a:"Als präbullöses/prodromales Stadium mit oft therapierefraktärem Pruritus, mit oder ohne urtikariell-ekzematöse Plaques, teils über Wochen bis Monate."},
    {s:5, q:"Welches klinische Muster ist bei der kindlichen linearen IgA-Dermatose charakteristisch?", a:"Gruppierte, anuläre/bogenförmige pralle Bullae auf gesunder Haut ('Perlenkette' / 'cluster of jewels'), v.a. periorifiziell und im Genital-/Leistenbereich."},
    {s:5, q:"Mit welchen neurologischen Komorbiditäten ist das bullöse Pemphigoid assoziiert?", a:"Apoplex, Demenz, M. Parkinson und Multiple Sklerose (gemeinsame BP180/BP230-Expression im ZNS); ausserdem Psoriasis."},
    {s:5, q:"Welche kortikosteroid-sparende Kombination ist bei mildem/moderatem bullösem Pemphigoid etabliert?", a:"Doxycyclin 200 mg/Tag plus Nikotinamid (Vit. B3) 1-2 g/Tag; alternativ Azathioprin, MMF oder MTX."},
    {s:5, q:"Welcher histologische Befund ist charakteristisch für Koma-Blasen?", a:"Subepidermale Blasen mit Schweissdrüsennekrose, DIF negativ; typischerweise über Druckstellen bei immobilisierten/komatösen Patienten."},
    {s:5, q:"Nennen Sie die beiden Haupt-Verlaufsformen der Epidermolysis bullosa acquisita (EBA).", a:"Mechanobullöse (klassische) Form mit Hautfragilität an Streckseiten/Akren, Narben und Milien; sowie inflammatorische (BP-artige) Form mit generalisierten Bullae ohne Vernarbung."},
    {s:5, q:"Mit welchen Systemerkrankungen ist die EBA klassisch assoziiert?", a:"Chronisch-entzündliche Darmerkrankung (v.a. M. Crohn), Plasmazell-Dyskrasie/multiples Myelom sowie Kollagenosen wie SLE und rheumatoide Arthritis."},
    {s:5, q:"Welches Auto-Antigen definiert die Dermatitis herpetiformis und wie kommt es dazu?", a:"IgA gegen epidermale Transglutaminase (TG3). Ausgangspunkt ist die Zöliakie mit Anti-tTG (TG2); im Verlauf Epitopausbreitung von TG2 auf TG3."},
    {s:5, q:"Welche HLA-Assoziation und Epidemiologie hat die Dermatitis herpetiformis Duhring?", a:"HLA-DQ2 und DQ8 (wie Zöliakie), Männer > Frauen, gehäuft in der nordeuropäischen Bevölkerung, Erwachsene > Kinder."},
    {s:5, q:"Welche Prädilektionsstellen und Primäreffloreszenz zeigt die Dermatitis herpetiformis?", a:"Symmetrisch herpetiform angeordnete Papulovesikel (meist nur Exkoriationen wegen starkem Juckreiz) an Streckseiten der Ellenbogen/Unterarme, Knie, Gesäss, Nacken und Kopfhaut."},
    {s:5, q:"Was kennzeichnet das Brunsting-Perry-Pemphigoid?", a:"Eine lokalisierte, vernarbende Variante des Schleimhautpemphigoids an Kopf/Nacken mit rezidivierenden Blasen und vernarbender Alopezie, meist ohne oder mit nur minimaler Schleimhautbeteiligung."},
    {s:5, q:"Wie unterscheiden sich SSSS und TEN in Spaltebene und Schleimhautbefall?", a:"SSSS: subkorneale Spaltung (Exfoliativtoxin gegen Dsg1), keine Schleimhautbeteiligung, gute Prognose bei Kindern. TEN: subepidermale Vollhautnekrose mit Schleimhautbefall; Abgrenzung über Biopsie."}
  ];
  const mc = [
    {s:5, q:"Ein Patient hat ausschliesslich enorale Erosionen; serologisch Anti-Dsg3 positiv, Anti-Dsg1 negativ. Welches Verteilungsmuster ist zu erwarten?", o:["Rein mukosaler Befall","Rein kutaner Befall","Mukokutaner Befall","Palmoplantarer Befall"], c:0, e:"Nach der Kompensationstheorie kompensiert Dsg1 den Dsg3-Verlust in der Haut; mukosal fehlt Dsg1 - daher rein mukosaler Pemphigus vulgaris."},
    {s:5, q:"Welches IIF-Substrat wird typischerweise zum Nachweis zirkulierender Auto-Antikörper bei Pemphigus vulgaris/foliaceus eingesetzt?", o:["Affenösophagus","Rattenblase","Salt-split-Humanhaut","HEp-2-Zellen"], c:0, e:"Auf Affenösophagus zeigen sich interzelluläre ('chicken-wire') IgG-Ablagerungen; Rattenblase dient dem PNP (Plakine), HEp-2 den ANA."},
    {s:5, q:"Welche histologische Beschreibung passt am besten zum Pemphigus foliaceus?", o:["Suprabasale Akantholyse mit 'row of tombstones'","Subkorneale Akantholyse im Stratum granulosum","Subepidermale Blase mit Eosinophilen","Vakuoläre Interface-Dermatitis"], c:1, e:"Beim Pemphigus foliaceus liegt die Akantholyse hoch im Stratum granulosum (subkorneal); die suprabasale Spaltung mit Grabsteinreihe ist typisch für den PV."},
    {s:5, q:"Ein 60-Jähriger zeigt therapierefraktäre Stomatitis, Konjunktivitis und lichenoide palmoplantare Läsionen; Verdacht auf Non-Hodgkin-Lymphom. Wahrscheinlichste Diagnose?", o:["Pemphigus vulgaris","Paraneoplastischer Pemphigus","Schleimhautpemphigoid","Epidermolysis bullosa acquisita"], c:1, e:"Schwere, therapierefraktäre Mukositis plus polymorphe (lichenoide, palmoplantare) Läsionen bei Lymphom sprechen für den paraneoplastischen Pemphigus."},
    {s:5, q:"Welches ist das Zielantigen des Anti-p200-Pemphigoids?", o:["Laminin γ1","Laminin-332","Kollagen VII","BP230"], c:0, e:"Das Anti-p200-Pemphigoid richtet sich gegen Laminin γ1; betroffen sind eher jüngere Patienten, häufig mit Psoriasis, IIF-Bindung am Blasenboden."},
    {s:5, q:"Welches Biologikum blockiert bei therapierefraktärem bullösem Pemphigoid die Th2-Achse (IL-4/IL-13)?", o:["Dupilumab","Rituximab","Secukinumab","Ustekinumab"], c:0, e:"Dupilumab hemmt die IL-4Rα-Untereinheit (IL-4/IL-13, Th2), passend zur Th2-/Eosinophilen-Pathogenese des BP; Rituximab zielt auf CD20."},
    {s:5, q:"Welche autoimmune blasenbildende Dermatose ist bei Kindern am häufigsten?", o:["Lineare IgA-Dermatose","Bullöses Pemphigoid","Pemphigus vulgaris","Epidermolysis bullosa acquisita"], c:0, e:"Die lineare IgA-Dermatose (chronic bullous disease of childhood) ist die häufigste kindliche AIBD; klinisch 'Perlenkette', meist Remission nach 2-4 Jahren."},
    {s:5, q:"Welcher Enzymdefekt liegt der Porphyria cutanea tarda zugrunde?", o:["Uroporphyrinogen-Decarboxylase","Ferrochelatase","Porphobilinogen-Desaminase","ALA-Dehydratase"], c:0, e:"PCT beruht auf einem (meist hepatischen) UROD-Mangel; Ferrochelatase-Mangel verursacht die EPP, PBG-Desaminase-Mangel die akute intermittierende Porphyrie."},
    {s:5, q:"Welcher Befund spricht für eine Pseudoporphyrie und gegen eine echte PCT?", o:["Normale Porphyrine in Urin/Plasma","Erhöhte Uroporphyrine","Hypertrichose","Ausgeprägte Fragilität lichtexponierter Haut"], c:0, e:"Die Pseudoporphyrie zeigt PCT-artige Blasen bei normalen Porphyrinwerten; typische Auslöser sind NSAR (Naproxen), Furosemid und Dialyse."},
    {s:5, q:"In welcher Schicht liegt die Spaltbildung bei der junktionalen Epidermolysis bullosa?", o:["In den basalen Keratinozyten","In der Lamina lucida","Unterhalb der Lamina densa","Im Stratum granulosum"], c:1, e:"Die JEB spaltet in der Lamina lucida (Laminin-332/Kollagen XVII/Integrine); EBS intraepidermal (basal), DEB unterhalb der Lamina densa (Kollagen VII)."},
    {s:5, q:"Welches Gen ist bei der dystrophen Epidermolysis bullosa mutiert?", o:["COL7A1","KRT14","LAMB3","PLEC"], c:0, e:"Die DEB beruht auf COL7A1-Mutationen (Kollagen VII/Ankerfibrillen); KRT14/PLEC verursachen die EBS, LAMB3 (Laminin-332) die JEB."},
    {s:5, q:"Welche neuere Therapie der rezessiv dystrophen EB nutzt autologe genkorrigierte Keratinozyten-Transplantate?", o:["Prademagene zamikeracel","Beremagene geperpavec","Birkenrinden-Triterpene","Dabrafenib"], c:0, e:"Prademagene zamikeracel sind autologe, COL7A1-korrigierte Keratinozyten-Grafts; Beremagene geperpavec (B-VEC) ist ein topischer HSV-1-Genvektor."},
    {s:5, q:"Welcher histologische Befund gilt als charakteristisch/pathognomonisch für die junktionale EB?", o:["Überschüssiges Granulationsgewebe","Corps ronds","Grabsteinreihe","Munro-Mikroabszesse"], c:0, e:"Überschüssiges Granulationsgewebe ist charakteristisch für die JEB; Corps ronds finden sich bei M. Darier, die Grabsteinreihe beim PV."},
    {s:5, q:"Welcher histologische Befund ist typisch für die Dermatitis herpetiformis?", o:["Neutrophile Mikroabszesse in den dermalen Papillenspitzen","Eosinophile Spongiose","'Row of tombstones'","Vakuoläre Interface-Dermatitis"], c:0, e:"Charakteristisch sind neutrophile Mikroabszesse in den Papillenspitzen mit subepidermaler Spaltbildung; die DIF zeigt granuläres IgA."},
    {s:5, q:"Was ist das Antidot bei symptomatischer Dapson-induzierter Methämoglobinämie?", o:["Methylenblau i.v.","N-Acetylcystein","Hydroxocobalamin","Vitamin K"], c:0, e:"Methylenblau reduziert Methämoglobin zu Hämoglobin; bei G6PD-Mangel ist es jedoch unwirksam/kontraindiziert."},
    {s:5, q:"Welche Komplikation ist beim okulären vernarbenden Schleimhautpemphigoid besonders gefürchtet?", o:["Symblepharon mit drohender Erblindung","Bronchiolitis obliterans","Glomerulonephritis","Steroid-induzierte Katarakt"], c:0, e:"Die vernarbende Konjunktivitis führt zu Symblepharon, Entropium und Trichiasis bis zur Erblindung; die Konjunktiva ist in ca. 40% betroffen."}
  ];
  const tf = [
    {s:5, st:"Bei der Salt-split-skin-Technik entsteht der Spalt in der Lamina lucida.", c:true, e:"1M NaCl spaltet in der Lamina lucida; Antigene oberhalb erscheinen im Blasendach, unterhalb im Blasenboden."},
    {s:5, st:"Beim paraneoplastischen Pemphigus ist die Bronchiolitis obliterans eine häufige, prognosebestimmende Komplikation.", c:true, e:"Etwa 30-40% entwickeln eine Bronchiolitis obliterans, die massgeblich zur hohen Mortalität beiträgt."},
    {s:5, st:"Pemphigus-Erkrankungen heilen aufgrund der intraepidermalen (suprabasalen) Akantholyse typischerweise ohne Vernarbung ab.", c:true, e:"Da die Spaltbildung intraepidermal erfolgt, bleibt die Basalmembran intakt - im Gegensatz zu MMP/Brunsting-Perry mit subepithelialer Vernarbung."},
    {s:5, st:"Bei der Dermatitis herpetiformis ist die indirekte Immunfluoreszenz (Standardsubstrat) typischerweise negativ/bland.", c:true, e:"Die Diagnose stützt sich auf granuläres IgA in der DIF sowie Anti-TG-/Endomysium-Antikörper; die IIF ist meist bland."},
    {s:5, st:"Das Anti-p200-Pemphigoid betrifft typischerweise Patienten über 70 Jahre.", c:false, e:"Betroffen sind eher jüngere Patienten, häufig mit begleitender Psoriasis; die Bindung erfolgt am Blasenboden (Laminin γ1)."},
    {s:5, st:"Bei der EBA binden die Auto-Antikörper in der Salt-split-skin am Blasendach.", c:false, e:"Das EBA-Antigen Kollagen VII liegt in der Lamina densa unterhalb des Spalts - die Bindung erfolgt am Blasenboden."},
    {s:5, st:"Das bullöse Pemphigoid heilt typischerweise vernarbend und mit Milienbildung ab.", c:false, e:"Das klassische BP heilt nicht vernarbend ab; Narben und Milien sind typisch für die EBA und das vernarbende Schleimhautpemphigoid."},
    {s:5, st:"Beim subkornealen Typ des IgA-Pemphigus ist Desmoglein 3 das Hauptzielantigen.", c:false, e:"Das Zielantigen des subkornealen Pustulose-Typs ist Desmocollin 1; Desmoglein 3 ist das Antigen des Pemphigus vulgaris."}
  ];
  const cloze = [
    {s:5, parts:["Beim bullösen Pemphigoid dient die Anti-","BLANK","-NC16A-Domäne als immundominantes Ziel für das serologische Monitoring der Krankheitsaktivität."], a:["BP180"]},
    {s:5, parts:["Rituximab ist ein monoklonaler Antikörper gegen ","BLANK"," auf B-Zellen und gilt als First-line-Therapie beim mittelschweren bis schweren Pemphigus vulgaris."], a:["CD20"]},
    {s:5, parts:["Vor Einleitung einer Dapson-Therapie muss der ","BLANK","-Status bestimmt werden, da ein Mangel eine dosisabhängige ","BLANK"," auslösen kann."], a:["G6PD","hämolytische Anämie"]},
    {s:5, parts:["Bei den Pemphigoid-Erkrankungen aktiviert der Antigen-Antikörper-Komplex das ","BLANK","-System, dessen Spaltprodukte Neutrophile chemotaktisch in die Basalmembranzone locken."], a:["Komplement"]},
    {s:5, parts:["Morbus Hailey-Hailey beruht auf einer Mutation im Gen ","BLANK",", Morbus Darier auf einer Mutation im Gen ","BLANK","."], a:["ATP2C1","ATP2A2"]}
  ];
  const match = [
    {s:5, t:"Erkrankung ↔ Salt-split-Bindungsort", p:[["Bullöses Pemphigoid","Blasendach"],["Anti-BP180-Schleimhautpemphigoid","Blasendach"],["Epidermolysis bullosa acquisita","Blasenboden"],["Anti-p200-Pemphigoid","Blasenboden"],["Anti-Laminin-332-Pemphigoid","Blasenboden"]]},
    {s:5, t:"Pemphigus-Variante ↔ Merkmal", p:[["Pemphigus erythematosus","Senear-Usher-Syndrom"],["Endemischer P. foliaceus","Fogo selvagem"],["Pemphigus vegetans","Verruköse intertriginöse Plaques"],["Paraneoplastischer Pemphigus","Bronchiolitis obliterans"],["Subkornealer IgA-Pemphigus","Desmocollin 1"]]},
    {s:5, t:"Therapie ↔ Wirkprinzip", p:[["Beremagene geperpavec","Topischer HSV-1-Vektor mit COL7A1"],["Prademagene zamikeracel","Autologe genkorrigierte Keratinozyten-Grafts"],["Rituximab","Anti-CD20-B-Zell-Depletion"],["Dapson","Hemmung der Neutrophilenfunktion"],["Dupilumab","IL-4Rα-Blockade (Th2)"]]}
  ];
  const freetext = [
    {s:5, q:"Erläutern Sie die Desmoglein-Kompensationstheorie und wie das Auto-Antikörperprofil das klinische Verteilungsmuster bei Pemphigus vulgaris und foliaceus bestimmt.", a:"Dsg3 ist die dominante Isoform der Schleimhäute, Dsg1 die der Epidermis. Wo beide koexprimiert werden (Haut), kann die intakte Isoform den Verlust der anderen teilweise kompensieren. Nur Anti-Dsg3: mukosaldominanter PV, da die Haut durch Dsg1 kompensiert wird. Anti-Dsg3 plus Anti-Dsg1: mukokutaner PV. Nur Anti-Dsg1: Pemphigus foliaceus mit rein kutaner, subkornealer Blasenbildung ohne Schleimhautbefall, da Dsg1 mukosal kaum exprimiert wird und dort durch Dsg3 kompensiert ist."},
    {s:5, q:"Ein 70-Jähriger entwickelt pralle subepidermale Blasen. Skizzieren Sie die Stufendiagnostik der autoimmunen blasenbildenden Dermatosen und wie Sie damit ein bullöses Pemphigoid von einer EBA abgrenzen.", a:"Läsionale Biopsie zur Histologie (subepidermale Blase; beim BP eosinophilenreiches Infiltrat). Periläsionale Biopsie für die DIF (lineäre IgG-/C3-Ablagerungen entlang der Basalmembran). Serologie mittels IIF auf Affenösophagus und Salt-split-skin: beim BP bindet der Antikörper am Blasendach (BP180/BP230), bei der EBA am Blasenboden (Kollagen VII in der Lamina densa). Bestätigung per ELISA: Anti-BP180-NC16A/BP230 beim BP versus Anti-Kollagen-VII bei der EBA. Klinisch sprechen Narben und Milien für die EBA."}
  ];
  const img = [
    {s:5, cap:"Verteilungsschema der Läsionen (rot) in seborrhoischen Arealen.", q:"'Corn-flakes'-artige krustöse Erosionen in seborrhoischen Arealen (Gesicht, Kapillitium, oberer Stamm) ohne Schleimhautbeteiligung. Diagnose?", o:["Pemphigus foliaceus","Pemphigus vulgaris","Bullöses Pemphigoid","Dermatitis herpetiformis"], c:0, e:"Seborrhoische Verteilung mit oberflächlichen, 'corn-flakes'-artigen Krusten und ausgesparten Schleimhäuten ist typisch für den Pemphigus foliaceus (Anti-Dsg1, subkorneale Akantholyse).", svg:`<svg viewBox="0 0 280 220" xmlns="http://www.w3.org/2000/svg"><rect x="0" y="0" width="280" height="220" fill="#F4EFE8"/><circle cx="140" cy="30" r="16" fill="#E8DFD3" stroke="#1B1A18" stroke-width="1.5"/><rect x="120" y="48" width="40" height="70" rx="10" fill="#E8DFD3" stroke="#1B1A18" stroke-width="1.5"/><rect x="98" y="52" width="18" height="58" rx="8" fill="#E8DFD3" stroke="#1B1A18" stroke-width="1.5"/><rect x="164" y="52" width="18" height="58" rx="8" fill="#E8DFD3" stroke="#1B1A18" stroke-width="1.5"/><rect x="122" y="118" width="16" height="80" rx="8" fill="#E8DFD3" stroke="#1B1A18" stroke-width="1.5"/><rect x="142" y="118" width="16" height="80" rx="8" fill="#E8DFD3" stroke="#1B1A18" stroke-width="1.5"/><ellipse cx="140" cy="22" rx="7" ry="4" fill="#B43A2E"/><ellipse cx="140" cy="33" rx="6" ry="4" fill="#B43A2E"/><ellipse cx="140" cy="60" rx="9" ry="5" fill="#B43A2E"/><ellipse cx="128" cy="72" rx="5" ry="4" fill="#B43A2E"/><ellipse cx="152" cy="72" rx="5" ry="4" fill="#B43A2E"/><text x="10" y="212" font-family="monospace" font-size="9" fill="#1B1A18">seborrhoisch: Gesicht, Kapillitium, oberer Stamm</text></svg>`},
    {s:5, cap:"Schema der dermoepidermalen Junktionszone; markiert ist Laminin-332 in der Lamina lucida.", q:"Auto-Antikörper gegen die markierte Struktur (Laminin-332) finden sich v.a. bei welcher Erkrankung, die ein obligates Tumorscreening erfordert?", o:["Anti-Laminin-332-Schleimhautpemphigoid","Epidermolysis bullosa acquisita","Dermatitis herpetiformis","Epidermolysis bullosa simplex"], c:0, e:"Anti-Laminin-332-Antikörper definieren eine Variante des vernarbenden Schleimhautpemphigoids mit erhöhter Malignomassoziation (Kolon-CA, HNO-Plattenepithelkarzinom) - Tumorscreening obligat.", svg:`<svg viewBox="0 0 300 240" xmlns="http://www.w3.org/2000/svg"><rect x="0" y="0" width="300" height="240" fill="#F4EFE8"/><rect x="30" y="20" width="180" height="45" fill="#E9C46A" stroke="#1B1A18" stroke-width="1"/><text x="35" y="46" font-family="sans-serif" font-size="11" fill="#1B1A18">Epidermis</text><rect x="30" y="65" width="180" height="20" fill="#CDA349" stroke="#1B1A18" stroke-width="1"/><text x="35" y="79" font-family="sans-serif" font-size="9" fill="#1B1A18">Basalzellen (Hemidesmosom)</text><rect x="30" y="85" width="180" height="16" fill="#F1E7D0" stroke="#1B1A18" stroke-width="1"/><text x="35" y="97" font-family="sans-serif" font-size="9" fill="#1B1A18">Lamina lucida</text><rect x="30" y="101" width="180" height="16" fill="#9DB4A0" stroke="#1B1A18" stroke-width="1"/><text x="35" y="113" font-family="sans-serif" font-size="9" fill="#1B1A18">Lamina densa</text><rect x="30" y="117" width="180" height="55" fill="#B48A78" stroke="#1B1A18" stroke-width="1"/><text x="35" y="147" font-family="sans-serif" font-size="11" fill="#1B1A18">Dermis</text><circle cx="205" cy="93" r="3" fill="#B43A2E"/><line x1="288" y1="93" x2="213" y2="93" stroke="#B43A2E" stroke-width="2"/><polygon points="213,93 221,89 221,97" fill="#B43A2E"/><text x="214" y="83" font-family="monospace" font-size="9" fill="#B43A2E">Laminin-332</text></svg>`}
  ];

  FLASH.push(...flash);
  MC.push(...mc);
  TF.push(...tf);
  CLOZE.push(...cloze);
  MATCH.push(...match);
  FREETEXT.push(...freetext);
  IMG.push(...img);
})();
