/* Dermaapp – Sektion 6: Adnexerkrankungen (Akne, Rosazea, Schweiss-/Talgdrüsen, follikuläre Erkrankungen). Auto-generiert aus Facharzt-Unterlagen. */
(function () {
  const flash = [
    {s:6, q:"Welche Rolle spielt Testosteron in der Aknepathogenese?", a:"In den Sebozyten wird Testosteron durch die 5α-Reduktase zu Dihydrotestosteron (DHT) umgebaut, was Wachstum und Sekretion der Talgdrüsen fördert; zusätzlich begünstigt Testosteron die follikuläre Keratinisierung. Das vermehrte Sebum begünstigt das Wachstum von C. acnes."},
    {s:6, q:"Welche vier Komponenten bilden die Akne-Tetrade (Follikulokklusionstetrade)?", a:"Acne conglobata, Hidradenitis suppurativa, Perifolliculitis capitis abscedens et suffodiens und Pilonidalsinus (die Triade umfasst die ersten drei)."},
    {s:6, q:"Was kennzeichnet die Acne excoriée des jeunes filles und wie wird sie behandelt?", a:"Durch zwanghaftes Manipulieren/Exkoriieren entstandene Läsionen, v.a. bei jungen Frauen; assoziiert mit Zwangs-/Angststörung und Body Dysmorphia. Therapie interdisziplinär über Psychiater/Psychologe."},
    {s:6, q:"Neonatale cephale Pustulose (neonatale Akne) – Merkregel und ein wichtiges Unterscheidungsmerkmal zur infantilen Akne?", a:"Merkregel 2-2-2: ca. 20 % der Neugeborenen, Beginn ~2 Wochen nach Geburt, Abheilung binnen ~2–3 Monaten. Typisch sind Papulopusteln OHNE Komedonen (ggf. Reaktion auf Malassezia), Ansprechen auf topische Antimykotika (z.B. Imazol/Clotrimazol)."},
    {s:6, q:"Infantile Akne – Alter, Klinik und Bedeutung?", a:"Auftreten zwischen 2. und 12. Lebensmonat mit klassischem Aknebild inkl. Komedonen (Vernarbung möglich), getriggert durch die physiologische Androgenproduktion. Erhöhtes Risiko für schwere Akne in der Pubertät; bei Hyperandrogenismus-Zeichen endokrinologische Abklärung."},
    {s:6, q:"Wodurch entsteht die Chlorakne?", a:"Meist berufliche Exposition gegenüber halogenierten aromatischen Kohlenwasserstoffen (Dioxine), u.a. in Herbiziden/Insektiziden. Klinisch komedonenreich."},
    {s:6, q:"Nennen Sie Medikamente/Substanzen, die eine akneiforme Eruption auslösen können.", a:"Kortikosteroide (topisch und peroral) und Anabolika, EGFR-Inhibitoren (Cetuximab, Erlotinib) sowie Lithium, Phenytoin und Isoniazid."},
    {s:6, q:"Isotretinoin bei schwerer Akne – anzustrebende Dosierung und Trade-off niedriger Dosierungen?", a:"Ziel 0,5 mg/kg KG (bzw. höchstmöglich tolerierte Dosis), Behandlung bis (nahezu) Erscheinungsfreiheit, dann 2–3 Monate weiter. Niedrigdosis (0,1–0,3 mg/kg) hat weniger Nebenwirkungen und seltener akute Verschlechterung, aber mehr Rückfälle."},
    {s:6, q:"Wozu werden bei Isotretinoin Omega-3-Fettsäuren (ca. 1 g/Tag) eingesetzt?", a:"Zur Reduktion der mukokutanen Nebenwirkungen (z.B. Cheilitis, Hauttrockenheit)."},
    {s:6, q:"Welches Fehlbildungsmuster droht bei Isotretinoin-Exposition in der Schwangerschaft?", a:"Retinoid-Embryopathie: ZNS (Hydro-/Mikrozephalus, Spina bifida), kraniofazial (Kiefer-Gaumen-Spalte, Ohrfehlbildungen), kardiovaskulär (Fallot-Tetralogie, Septumdefekte), Nebenschilddrüsen-/Thymusfehlbildungen sowie intrauteriner Fruchttod."},
    {s:6, q:"Welche Milben spielen in der Rosazea-Pathogenese eine Rolle?", a:"Demodex folliculorum und Demodex brevis; eine übermässige Besiedlung fördert die Inflammation."},
    {s:6, q:"Wie entsteht ein Rhinophym pathogenetisch?", a:"Durch Hyperplasie der Talgdrüsen und des Bindegewebes (die genaue Ursache ist nicht abschliessend geklärt)."},
    {s:6, q:"Wie werden die Phyme der Rosazea nach Lokalisation benannt?", a:"Rhinophym (Nase), Gnathophym (Kinn) und Metophym (Stirn/Glabella)."},
    {s:6, q:"Brimonidin (Mirvaso) – Wirkmechanismus und Wirkdauer bei Rosazea?", a:"Topischer α2-adrenerger Agonist (Vasokonstriktor) zur kurzfristigen Reduktion des Erythems; Wirkdauer ca. 8–10 h."},
    {s:6, q:"Wie äussert sich eine okuläre Rosazea?", a:"Lidrandteleangiektasien, konjunktivale Injektion, Fremdkörpergefühl/Irritation; kann der Hautbeteiligung vorausgehen."},
    {s:6, q:"Granulomatöse Rosazea – Klinik und Verlauf?", a:"Monomorphe hautfarbene bis bräunliche Papeln zentrofazial (auch extrafazial an Kopfhaut, Hals, oberem Rumpf), bei Kindern und Erwachsenen; oft spontanes Abheilen nach einigen Jahren."},
    {s:6, q:"Immunsuppressions-assoziierte eosinophile pustulöse Follikulitis – wichtigste Assoziationen?", a:"HIV (korreliert mit niedriger CD4-Zellzahl), myeloproliferative Erkrankungen und Stammzelltransplantation; klinisch rezidivierende juckende Papeln/Pusteln an Gesicht, Kopfhaut und oberem Rumpf."},
    {s:6, q:"Wann und womit wird bei rezidivierender/chronischer Follikulitis eine Dekolonisation erwogen?", a:"Bei chronischer Follikulitis, Abszessen und Nachweis von MRSA oder PVL-Gen; systemisch u.a. Ciprofloxacin."},
    {s:6, q:"Ulerythema ophryogenes – Klinik und Syndromassoziation?", a:"Follikuläre Papeln mit zentralem Keratinpfropf v.a. an den Augenbrauen, übergehend in follikuläre Atrophie mit vernarbender Alopezie der lateralen Augenbrauen; Beginn in der Kindheit. Assoziiert u.a. mit dem Noonan-Syndrom."},
    {s:6, q:"Atrophoderma vermiculatum – typische Klinik?", a:"Eingesenkte, atrophische Vertiefungen in wurm-/wabenartigem Muster, meist an den Wangen; Erstmanifestation zwischen 5. und 12. Lebensjahr."},
    {s:6, q:"Acne keloidalis nuchae – typischer Patient und Assoziationen?", a:"V.a. männliche People of Color zwischen Pubertät und 50. LJ; chronisch keloidal vernarbende Follikulitis am Nacken/Okziput. Assoziiert mit Hidradenitis suppurativa, Folliculitis decalvans und metabolischem Syndrom."},
    {s:6, q:"Definieren Sie die Hidradenitis suppurativa.", a:"Meist peripubertär beginnende, chronisch-rezidivierende, neutrophile Inflammation der follikulopilosebazeösen Einheit mit Knoten, Abszessen, Fisteln und Vernarbung in intertriginösen Arealen."},
    {s:6, q:"Was ist die invasive proliferative gelatinous mass bei der Hidradenitis suppurativa?", a:"Eine neutrophilen- und zytokinreiche gelatinöse Masse in den Fistelgängen der HS; sie ist Ausgangspunkt von Rezidiven – deshalb wird beim Deroofing der Boden kürettiert."},
    {s:6, q:"Bromhidrose – Definition und ein spezifischer Auslöser?", a:"Übelriechender Schweiss; fischartiger Geruch bei Trimethylaminurie, behandelt mit Cholin-/Carnitin-armer Diät. Davon abzugrenzen ist die Chromhidrose (gefärbter Schweiss)."},
    {s:6, q:"Charakterisieren Sie die primäre Hyperhidrose.", a:"Häufigste Form; Beginn meist in Kindheit/Adoleszenz, symmetrisch v.a. axillär und palmoplantar (volar), positive Familienanamnese in 60–80 %."},
    {s:6, q:"Miliaria – Pathogenese und Subtypen?", a:"Obstruktion des ekkrinen Ausführungsgangs auf verschiedenen Ebenen mit Schweissretention (Neugeborene, warm-feuchtes Klima). Subtypen: Miliaria crystallina, rubra und profunda; Therapie: Hitze/Okklusion meiden."},
    {s:6, q:"Keratolysis exfoliativa – Klinik und Assoziation?", a:"Sehr häufige, asymptomatische anuläre/collarette-artige Schuppung v.a. palmar (>> plantar), 2–15 mm; Verschlechterung bei warmem Wetter, assoziiert mit palmoplantarer Hyperhidrose. Therapie u.a. Urea 20 %."},
    {s:6, q:"Warum dürfen tiefe Follikulitisläsionen nicht ausgedrückt werden?", a:"Wegen der Gefahr einer Bakteriämie mit Besiedlung von Herzklappen (Endokarditis), Gehirn (Abszess) oder Knochen (Osteomyelitis)."}
  ];
  const mc = [
    {s:6, q:"Welche Substanz ist Erstlinientherapie bei überwiegend komedonaler milder Akne?", o:["Systemisches Isotretinoin","Orales Doxycyclin","Topisches Retinoid (z.B. Adapalen)","Spironolacton"], c:2, e:"Bei milder, v.a. komedonaler Akne sind topische Retinoide mit geringem Irritationspotenzial (Adapalen) Mittel der Wahl; Benzoylperoxid v.a. bei entzündlichen Läsionen, Azelainsäure als Zweitlinie (auch bei Kinderwunsch)."},
    {s:6, q:"Welche Aussage charakterisiert die Acne conglobata?", o:["Schwere Akne mit Zysten und Noduli, Teil der Follikulokklusionstriade","Komedonenreiche Akne durch mechanische Reibung","Neonatale Pusteln ohne Komedonen","Rein prämenstruell aggravierte Akne der Frau"], c:0, e:"Acne conglobata ist eine schwere Form mit Zysten und Noduli und gehört mit HS und Perifolliculitis capitis abscedens et suffodiens zur Follikulokklusionstriade (Tetrade zusätzlich mit Pilonidalsinus)."},
    {s:6, q:"Ab welchem Alter ist systemisches Isotretinoin zur Aknetherapie zugelassen?", o:["Ab 6 Jahren","Ab 12 Jahren","Ab 16 Jahren","Ab 18 Jahren"], c:1, e:"Systemisches Isotretinoin ist ab dem 12. Lebensjahr zugelassen."},
    {s:6, q:"Welcher Laser ist Mittel der Wahl bei hyperpigmentierten Aknenarben bzw. postinflammatorischer Hyperpigmentierung?", o:["Gepulster Farbstofflaser (PDL)","Q-switched Nd:YAG-Laser","Fraktioniert ablativer CO2-Laser","Argon-Laser"], c:1, e:"Der Q-switched Nd:YAG adressiert Pigment/hyperpigmentierte Narben; der Gefässlaser (PDL) erythematöse flache Narben, fraktionierte Laser atrophe Narben."},
    {s:6, q:"Welche hormonelle Kontrazeption ist unter systemischem Isotretinoin ungeeignet?", o:["Kombinierte Östrogen-Gestagen-Pille","Reine Gestagenpräparate (Gestagen-Monopille)","Antiandrogen wirksame Kontrazeptiva","Kupfer-Intrauterinpessar"], c:1, e:"Reine Gestagenprodukte sind ungeeignet, da ihre kontrazeptive Wirkung unter Isotretinoin deutlich reduziert ist."},
    {s:6, q:"Wie lange nach Absetzen einer systemischen Isotretinoin-Therapie sollte mit einer Lasertherapie/Dermabrasion gewartet werden?", o:["2 Wochen","1 Monat","6 Monate","3 Jahre"], c:2, e:"Eine Lasertherapie sollte erst etwa 6 Monate nach Absetzen des systemischen Isotretinoins erfolgen (Wundheilung/Vernarbungsrisiko)."},
    {s:6, q:"Unter Isotretinoin steigen die Triglyceride auf 6 mmol/l (Bereich 4,5–11,3). Welches Vorgehen ist korrekt?", o:["Sofortiges dauerhaftes Absetzen und Statin","Omega-3-Fettsäuren plus Fenofibrat oder Nikotinsäure","Keine Massnahme nötig","Nur die Flüssigkeitszufuhr erhöhen"], c:1, e:"Bei 4,5–11,3 mmol/l werden Omega-3-Fettsäuren (2–4 g/d) mit Fenofibrat (Lipanthyl) oder Nikotinsäure kombiniert; darunter (2,2–4,5) genügen Lifestyle und Omega-3."},
    {s:6, q:"Welche systemische Therapie ist bei Rosazea in-label (antiinflammatorisch, subantimikrobiell dosiert)?", o:["Amoxicillin 1 g/d","Doxycyclin 200 mg/d","Doxycyclin 40 mg/d (Oracea)","Ciprofloxacin 500 mg/d"], c:2, e:"In-label ist Doxycyclin 40 mg/d (Oracea) in subantimikrobieller, antiinflammatorischer Dosierung."},
    {s:6, q:"Welche systemische Substanz ist beim Morbus Morbihan (solides Gesichtsödem) besonders wirksam, spricht aber erst nach 4–6 Monaten an?", o:["Prednisolon","Isotretinoin","Ciclosporin","Methotrexat"], c:1, e:"M. Morbihan wird mit Isotretinoin, Tetracyclinen oder Dapson behandelt und spricht typischerweise erst nach 4–6 Monaten an."},
    {s:6, q:"Mit welchen systemischen Erkrankungen ist die Rosazea gehäuft assoziiert?", o:["Vitiligo und Alopecia areata","Systemische Sklerose und Sjögren-Syndrom","Chronisch-entzündliche Darmerkrankungen, Zöliakie, metabolisches Syndrom","Hämochromatose und M. Wilson"], c:2, e:"Beschrieben sind Assoziationen mit CED, Zöliakie und dem metabolischen Syndrom."},
    {s:6, q:"Welches Zytokin ist ein zentrales Ziel der Biologikatherapie (Adalimumab) bei Hidradenitis suppurativa?", o:["IL-5","TNF-α","IL-4","Interferon-α"], c:1, e:"Adalimumab, ein TNF-α-Inhibitor, adressiert das in der HS-Pathogenese zentrale TNF-α; weitere Ziele sind IL-17 und IL-23."},
    {s:6, q:"Welche Massnahme gehört zur Erstlinientherapie der Hidradenitis suppurativa Hurley I?", o:["Wide surgical excision","Systemisches Adalimumab","Topisches Clindamycin und antiseptische Waschlotionen","Ganzkörper-UVB"], c:2, e:"Hurley I wird u.a. mit antiseptischen Waschlotionen, topischem Clindamycin, ggf. intraläsionalen Steroiden und systemischen Tetrazyklinen behandelt; ausgedehnte Exzisionen sind Hurley III vorbehalten."},
    {s:6, q:"Welcher off-label bei HS eingesetzte Wirkstoff ist ein JAK-Inhibitor?", o:["Upadacitinib","Guselkumab","Secukinumab","Apremilast"], c:0, e:"Upadacitinib ist ein JAK-Inhibitor (15 mg/d, ggf. 30 mg/d). Guselkumab = Anti-IL-23, Secukinumab = Anti-IL-17A, Apremilast = PDE4-Hemmer."},
    {s:6, q:"Welches HS-Biologikum blockiert sowohl IL-17A als auch IL-17F?", o:["Bimekizumab","Adalimumab","Guselkumab","Infliximab"], c:0, e:"Bimekizumab blockiert IL-17A und IL-17F (doppelte Blockade) und ist den Vorgängerbiologika dadurch wahrscheinlich überlegen."},
    {s:6, q:"Warum sollte Rifampicin bei HS nur in Kombination (z.B. mit Clindamycin) und nie als Monotherapie eingesetzt werden?", o:["Gefahr einer Retinopathie","Erhöhtes Risiko einer pseudomembranösen Kolitis/Resistenzentwicklung","Rasche Nephrotoxizität","Auslösung einer Hyperkaliämie"], c:1, e:"Rifampicin-Monotherapie wird wegen Resistenzentwicklung und erhöhtem Risiko einer pseudomembranösen Kolitis vermieden; Clindamycin + Rifampicin ist eine etablierte Kombination."},
    {s:6, q:"Welche Ursache spricht am ehesten für eine sekundäre LOKALISIERTE Hyperhidrose?", o:["Hyperthyreose","Phäochromozytom","Apoplex oder Rückenmarksverletzung","Hodgkin-Lymphom"], c:2, e:"Lokalisierte sekundäre Hyperhidrose entsteht z.B. durch Apoplex, Wirbelsäulenverletzung oder ZNS-Tumor; die anderen Ursachen führen zu generalisierter Hyperhidrose."},
    {s:6, q:"Ein Kind entwickelt im Frühling nach Sport plötzlich schmerzhafte, überwärmte erythematöse Knötchen an den Fusssohlen mit spontaner Remission. Diagnose?", o:["Erythema nodosum","Pernionen","Granuloma anulare","Idiopathische palmoplantare Hidradenitis"], c:3, e:"Die idiopathische palmoplantare (ekkrine) Hidradenitis tritt bei Kindern/Jugendlichen saisonal nach Hitze/Sport auf (Ruptur ekkriner Drüsen). DD: Pseudomonas-Hot-Foot-Syndrom, Druckurtikaria, Perniones."},
    {s:6, q:"Welche Aussage trifft auf die eosinophile pustulöse Follikulitis der Kindheit zu?", o:["Beginn meist vor dem 15. Lebensmonat, Abheilung bis zum 3. Lebensjahr, v.a. am Skalp","Betrifft v.a. asiatische Erwachsene mit M>F","Ist streng HIV-assoziiert","Wird primär mit Indomethacin behandelt"], c:0, e:"Die kindliche Form beginnt meist vor dem 15. Lebensmonat, ist selbstlimitierend (Abheilung bis ins 3. Lebensjahr) und betrifft v.a. den Skalp; Therapie topische Kortikosteroide."},
    {s:6, q:"Welche follikuläre Erkrankung betrifft typischerweise junge japanische Männer mit Erythem, Hyperpigmentierung und feinen follikulären Papeln im Gesicht?", o:["Ulerythema ophryogenes","Atrophoderma vermiculatum","Keratosis pilaris rubra","Erythromelanosis follicularis faciei et colli"], c:3, e:"Die Erythromelanosis follicularis faciei (et colli) beginnt in der 2. Dekade v.a. bei japanischen Männern; Therapie mit Keratolytika, Isotretinoin und PDL/Nd:YAG gegen das Erythem."},
    {s:6, q:"Über welchen Neurotransmitter werden die ekkrinen Schweissdrüsen gesteuert?", o:["Noradrenalin","Dopamin","Histamin","Acetylcholin"], c:3, e:"Die ekkrinen Schweissdrüsen werden – anders als die adrenerg gesteuerten apokrinen Drüsen – cholinerg (Acetylcholin) über das hypothalamische Schwitzzentrum innerviert."},
    {s:6, q:"Welche endokrine/neoplastische Ursache kann eine sekundäre generalisierte Hyperhidrose auslösen?", o:["Phäochromozytom","Hypothyreose","Diabetes insipidus","Hypoparathyreoidismus"], c:0, e:"Ein Phäochromozytom (Katecholaminexzess) verursacht eine generalisierte Hyperhidrose; weitere Ursachen sind u.a. Hyperthyreose, Hodgkin-Lymphom und Menopause."},
    {s:6, q:"Welcher Mechanismus liegt der Pseudofolliculitis barbae zugrunde?", o:["Infektion der Follikel durch Staphylococcus aureus","Autoimmune Zerstörung der Talgdrüsen","Okklusion apokriner Schweissdrüsen","Wiedereintritt gekräuselter Haare extra- oder transfollikulär in die Haut"], c:3, e:"Bei stark gelocktem Haar dringt die scharfe Haarspitze extrafollikulär (Wiedereintritt nach Austritt) oder transfollikulär (durch das Follikelepithel) in die Dermis ein und löst eine Fremdkörperreaktion aus."}
  ];
  const tf = [
    {s:6, st:"Etwa 85 % der 12- bis 24-Jährigen sind von Akne betroffen.", c:true, e:"Korrekt – die Akne ist in dieser Altersgruppe ausserordentlich häufig."},
    {s:6, st:"Die Acne mechanica entsteht durch wiederholte mechanische bzw. reibungsbedingte Verlegung des Ausführungsgangs und ist komedonenreich.", c:true, e:"Korrekt – Druck/Reibung (z.B. Helme, Riemen) führen zu einer komedonenreichen Akne."},
    {s:6, st:"Nach einer Alitretinoin-Therapie (Toctino) muss die Kontrazeption noch 3 Jahre fortgeführt werden.", c:false, e:"Falsch – bei Alitretinoin und Isotretinoin genügt 1 Monat nach Therapieende; die 3-Jahres-Regel gilt für Acitretin (Neotigason)."},
    {s:6, st:"Die Acne tropica wird primär durch Kälte und trockene Luft ausgelöst.", c:false, e:"Falsch – Auslöser sind Hitze und hohe Luftfeuchtigkeit (follikulär gebunden)."},
    {s:6, st:"Die Röntgenakne ist komedonenreich und beginnt typischerweise, wenn die akute Strahlendermatitis abheilt.", c:true, e:"Korrekt – sie tritt nach Strahlentherapie auf, mit Beginn während der Abheilung der Strahlendermatitis."},
    {s:6, st:"Eine niedrig dosierte Isotretinoin-Therapie (0,1–0,3 mg/kg) hat weniger Nebenwirkungen, aber eine höhere Rückfallrate.", c:true, e:"Korrekt – Trade-off zwischen geringerer Toxizität und höherer Rezidivrate."},
    {s:6, st:"Reine Gestagenpräparate sind zur Kontrazeption unter Isotretinoin besonders geeignet.", c:false, e:"Falsch – ihre Wirkung ist unter Isotretinoin deutlich reduziert; sie sollen nicht als alleinige Kontrazeption verwendet werden."},
    {s:6, st:"Die eosinophile pustulöse Follikulitis (Ofuji) betrifft bevorzugt asiatische Frauen.", c:false, e:"Falsch – betroffen sind v.a. asiatische Erwachsene mit männlicher Prädominanz (M>F)."},
    {s:6, st:"Das idiopathische aseptische Granulom des Gesichts heilt meist spontan innerhalb etwa eines Jahres ab.", c:true, e:"Korrekt – ein schmerzloser, akneiform imponierender Knoten des Kleinkindes mit spontaner Abheilung."},
    {s:6, st:"Bei der Rosazea ist der gepulste Farbstofflaser (PDL) den IPL-Geräten zur Behandlung der Teleangiektasien in der Regel überlegen.", c:true, e:"Korrekt – PDL > IPL; beide adressieren die vaskuläre Komponente der Rosazea."}
  ];
  const cloze = [
    {s:6, parts:["Systemische und topische Antibiotika sollten bei Akne nur in Kombination mit topischen ","BLANK"," oder Benzoylperoxid eingesetzt werden."], a:["Retinoiden"]},
    {s:6, parts:["Das Kombinationspräparat Epiduo enthält das Retinoid ","BLANK"," und ","BLANK","."], a:["Adapalen","Benzoylperoxid"]},
    {s:6, parts:["In der HS-Pathogenese dominieren die proinflammatorischen Zytokine TNF-α, IL-1β und ","BLANK","."], a:["IL-17"]},
    {s:6, parts:["Ein Risikofaktor für eine besonders schwere Akne ist der ","BLANK","-Karyotyp."], a:["XYY"]},
    {s:6, parts:["Die Acne tarda der Frau wird u.a. mit antiandrogener Kontrazeption und dem oralen Antidiabetikum ","BLANK"," behandelt."], a:["Metformin"]},
    {s:6, parts:["Gegen anhaltendes Flushing bei Rosazea kann der Betablocker ","BLANK"," (6,25 mg) eingesetzt werden."], a:["Carvedilol"]}
  ];
  const match = [
    {s:6, t:"Akne-Sonderform ↔ Auslöser", p:[["Chlorakne","Halogenierte aromatische Kohlenwasserstoffe"],["Acne mechanica","Mechanische Reibung/Druck"],["Röntgenakne","Ionisierende Strahlung/Strahlentherapie"],["Acne cosmetica","Okkludierende Kosmetika/Öle"],["Acne tropica","Hitze und hohe Luftfeuchtigkeit"]]},
    {s:6, t:"Rosazea-Therapeutikum ↔ Wirkprinzip/Indikation", p:[["Metronidazol (Rosalox)","Topisch antiinflammatorisch/antigranulomatös"],["Brimonidin (Mirvaso)","Vasokonstriktor gegen Erythem"],["Doxycyclin 40 mg (Oracea)","Systemisch antiinflammatorisch"],["Carvedilol","Betablocker gegen Flushing"],["Isotretinoin","Phyme und M. Morbihan"]]},
    {s:6, t:"HS-Systemtherapie ↔ molekulares Target", p:[["Adalimumab","TNF-α"],["Secukinumab","IL-17A"],["Bimekizumab","IL-17A und IL-17F"],["Guselkumab","IL-23"],["Upadacitinib","JAK"]]},
    {s:6, t:"Follikuläre Keratose ↔ Charakteristikum", p:[["Ulerythema ophryogenes","Vernarbende Alopezie der lateralen Augenbrauen"],["Atrophoderma vermiculatum","Wabenartige atrophische Vertiefungen der Wangen"],["Erythromelanosis follicularis faciei","Erythem/Hyperpigmentierung bei japanischen Männern"],["Keratosis pilaris","Follikuläre Hyperkeratose an den Streckseiten"]]}
  ];
  const freetext = [
    {s:6, q:"Erläutern Sie die Pathogenese-Kaskade und die Hurley-Stadien der Hidradenitis suppurativa.", a:"Pathogenese: Am Anfang steht eine Hyperkeratose/Hyperplasie des infundibulären Follikelepithels (getriggert durch Reibung, genetische Prädisposition, Rauchen, Übergewicht), die zu follikulärer Okklusion, Follikeldilatation und schliesslich Follikelruptur führt. Freigesetzte PAMPs/DAMPs, Bakterien und Zelldebris aktivieren das angeborene Immunsystem: IL-1β und TNF-α induzieren Chemokine (u.a. CXCL8, CCL2, CCL20), die Neutrophile und T-Zellen rekrutieren; dendritische Zellen treiben über IL-23/IL-12 eine Th17-/Th1-Polarisation. Im fortgeschrittenen Stadium unterhalten IL-17A/F und TNF-α die Entzündung mit Keratinozytenproliferation, Akanthose und Plugging, während IL-1β Fibroblasten und Matrix-Metalloproteinasen aktiviert und so Fistelbildung und Fibrose fördert. Hurley-Stadien: Grad I = solitäre oder multiple Abszesse ohne Fistelgänge oder Narbenstränge; Grad II = rezidivierende Abszesse mit lokalisierter Fistel-/Strangbildung (eine oder mehrere getrennte Läsionen); Grad III = diffuser, plattenartiger Befall mit multiplen untereinander verbundenen Fistelgängen und Abszessen. Therapieintensität und Chirurgie (Deroofing bis wide excision) richten sich nach dem Hurley-Grad; der Therapieerfolg wird über den HiSCR beurteilt."},
    {s:6, q:"Erläutern Sie Indikation, Dosierung, Monitoring und Sicherheitsaspekte einer systemischen Isotretinoin-Therapie bei schwerer Akne.", a:"Indikation: schwere (noduläre/konglobierende) Akne, Narbenneigung, unzureichendes Ansprechen auf Topika oder starke psychische Belastung; zugelassen ab dem 12. Lebensjahr. Dosierung: anzustreben 0,5 mg/kg KG bzw. die höchstmöglich tolerierte Dosis, Behandlung bis zur (nahezu) Erscheinungsfreiheit, dann 2–3 Monate fortführen; Niedrigdosis (0,1–0,3 mg/kg) hat weniger Nebenwirkungen, aber mehr Rückfälle. Omega-3-Fettsäuren (ca. 1 g/d) reduzieren mukokutane Nebenwirkungen. Monitoring: Labor (Transaminasen, Lipide) vor Start und Kontrolle ~2 Monate nach Beginn; bei Triglyceriden 4,5–11,3 mmol/l Omega-3 plus Fenofibrat/Nikotinsäure, bei LDL > 4,1 mmol/l Statin. Sicherheit/Teratogenität: strikte Kontrazeption (keine reinen Gestagene, da Wirkung reduziert) mit Fortführung 1 Monat nach Therapieende plus Schwangerschaftstests. Bei Exposition drohen ZNS-, kraniofaziale, kardiovaskuläre sowie Thymus-/Nebenschilddrüsenfehlbildungen. Eine Lasertherapie sollte erst ~6 Monate nach Absetzen erfolgen; cave Triggerung einer Acne fulminans zu Behandlungsbeginn."}
  ];
  const img = [
    {s:6, cap:"Zentrofaziales Gesichtsbild", q:"Persistierendes zentrofaziales Erythem mit Teleangiektasien und Papulopusteln, periokulär ausgespart. Welche Diagnose ist am wahrscheinlichsten?", o:["Akne vulgaris","Rosazea (papulopustulöser Subtyp)","Periorale Dermatitis","Systemischer Lupus erythematodes"], c:1, e:"Zentrofaziales Erythem mit Teleangiektasien und Papulopusteln spricht für eine papulopustulöse Rosazea; im Gegensatz zur Akne fehlen Komedonen.", svg:`<svg viewBox="0 0 280 300" xmlns="http://www.w3.org/2000/svg"><ellipse cx="140" cy="150" rx="82" ry="108" fill="#f5d6c6" stroke="#9ca3af" stroke-width="2"/><ellipse cx="58" cy="150" rx="12" ry="22" fill="#f5d6c6" stroke="#9ca3af" stroke-width="2"/><ellipse cx="222" cy="150" rx="12" ry="22" fill="#f5d6c6" stroke="#9ca3af" stroke-width="2"/><path d="M140,118 Q100,130 92,175 Q100,206 140,212 Q180,206 188,175 Q180,130 140,118 Z" fill="#e0846b" opacity="0.55"/><rect x="132" y="120" width="16" height="72" rx="8" fill="#d76a4e" opacity="0.5"/><ellipse cx="110" cy="124" rx="12" ry="7" fill="#ffffff" stroke="#6b7280" stroke-width="1.5"/><ellipse cx="170" cy="124" rx="12" ry="7" fill="#ffffff" stroke="#6b7280" stroke-width="1.5"/><circle cx="110" cy="124" r="3" fill="#374151"/><circle cx="170" cy="124" r="3" fill="#374151"/><g stroke="#b0281c" stroke-width="1" opacity="0.85" fill="none"><path d="M100,158 l10,4 l-6,5"/><path d="M176,164 l-10,3 l6,6"/><path d="M120,186 l8,-3 l-3,7"/></g><g fill="#a8332a"><circle cx="108" cy="170" r="3"/><circle cx="118" cy="181" r="2.5"/><circle cx="165" cy="172" r="3"/><circle cx="176" cy="182" r="2.5"/><circle cx="140" cy="196" r="3"/></g><g fill="#f2e9c9"><circle cx="108" cy="169" r="1.1"/><circle cx="165" cy="171" r="1.1"/><circle cx="140" cy="195" r="1.1"/></g><path d="M120,236 Q140,246 160,236" stroke="#a05a4a" stroke-width="2" fill="none"/><text x="30" y="292" font-size="10" fill="#374151" font-family="sans-serif">Zentrofaziales Erythem, Teleangiektasien, Papulopusteln</text></svg>`},
    {s:6, cap:"Schema: ekkriner Ausführungsgang in den Hautschichten", q:"Die Obstruktion des ekkrinen Ausführungsgangs liegt im Stratum corneum (Ebene 1). Welche Miliaria-Form resultiert?", o:["Miliaria crystallina","Miliaria rubra","Miliaria profunda","Miliaria pustulosa"], c:0, e:"Eine sehr oberflächliche Obstruktion (Stratum corneum) führt zur Miliaria crystallina (dünnwandige Bläschen). Tiefer gelegene Obstruktionen ergeben Miliaria rubra (Epidermis) bzw. profunda (dermoepidermale Junktion).", svg:`<svg viewBox="0 0 300 240" xmlns="http://www.w3.org/2000/svg"><rect x="20" y="28" width="200" height="22" fill="#f3d9c0" stroke="#9ca3af" stroke-width="1"/><rect x="20" y="50" width="200" height="60" fill="#f7c9a8" stroke="#9ca3af" stroke-width="1"/><rect x="20" y="110" width="200" height="92" fill="#efb28d" stroke="#9ca3af" stroke-width="1"/><text x="26" y="43" font-size="9" fill="#4b5563" font-family="sans-serif">Stratum corneum</text><text x="26" y="84" font-size="9" fill="#4b5563" font-family="sans-serif">Epidermis</text><text x="26" y="160" font-size="9" fill="#4b5563" font-family="sans-serif">Dermis</text><path d="M150,50 C150,78 156,96 150,110 C144,146 150,178 150,196" stroke="#3b82f6" stroke-width="3" fill="none"/><circle cx="150" cy="200" r="10" fill="none" stroke="#3b82f6" stroke-width="3"/><circle cx="150" cy="38" r="5" fill="#dc2626"/><text x="230" y="41" font-size="9" fill="#b91c1c" font-family="sans-serif">1 crystallina</text><circle cx="150" cy="80" r="5" fill="#dc2626"/><text x="230" y="83" font-size="9" fill="#b91c1c" font-family="sans-serif">2 rubra</text><circle cx="150" cy="114" r="5" fill="#dc2626"/><text x="230" y="117" font-size="9" fill="#b91c1c" font-family="sans-serif">3 profunda</text><text x="20" y="228" font-size="10" fill="#374151" font-family="sans-serif">Obstruktion des ekkrinen Gangs auf 3 Ebenen</text></svg>`},
    {s:6, cap:"Gesichtsprofil mit Nasenbefund", q:"Knollige Auftreibung der Nase mit Talgdrüsenhyperplasie bei langjähriger Rosazea. Wie lautet der Begriff?", o:["Basalzellkarzinom","Rhinophym","Nasales Angiofibrom","Sarkoidose (Lupus pernio)"], c:1, e:"Die knollige Nasenauftreibung durch Hyperplasie von Talgdrüsen und Bindegewebe ist das Rhinophym; Therapie mittels CO2-Laserablation, Elektrochirurgie oder Exzision.", svg:`<svg viewBox="0 0 260 260" xmlns="http://www.w3.org/2000/svg"><path d="M60,30 C120,30 150,70 150,110 L185,150 C205,165 200,185 175,188 L150,190 C150,215 130,235 95,235 L60,235 Z" fill="#f2d3bf" stroke="#9ca3af" stroke-width="2"/><path d="M150,110 C185,115 220,140 218,170 C216,192 190,201 168,192 C150,186 145,165 150,150 Z" fill="#df9c81" stroke="#9ca3af" stroke-width="2"/><g fill="#c86b4f" opacity="0.85"><circle cx="185" cy="150" r="4"/><circle cx="198" cy="162" r="4"/><circle cx="188" cy="173" r="3.5"/><circle cx="174" cy="160" r="3"/><circle cx="201" cy="150" r="3"/><circle cx="192" cy="182" r="3"/></g><ellipse cx="95" cy="95" rx="10" ry="6" fill="#ffffff" stroke="#6b7280" stroke-width="1.5"/><circle cx="97" cy="95" r="2.5" fill="#374151"/><text x="18" y="252" font-size="10" fill="#374151" font-family="sans-serif">Knollige Nasenauftreibung mit Talgdrüsenhyperplasie</text></svg>`}
  ];

  FLASH.push(...flash);
  MC.push(...mc);
  TF.push(...tf);
  CLOZE.push(...cloze);
  MATCH.push(...match);
  FREETEXT.push(...freetext);
  IMG.push(...img);
})();
