/* Dermaapp – Sektion 2: Pruritus / Psychokutane Erkrankungen. Auto-generiert aus Facharzt-Unterlagen. */
(function () {
  const flash = [
    {s:2, q:"Über welchen Fasertyp wird Pruritus peripher zum ZNS geleitet?", a:"Über langsam leitende, unmyelinisierte C-Fasern (histaminerge und nicht-histaminerge/mechano-insensitive Subpopulationen). Juckreiz und chronischer Schmerz teilen viele Gemeinsamkeiten."},
    {s:2, q:"Nenne die wichtigsten peripheren Mediatoren des Juckreizes.", a:"Histamin, Proteasen (z.B. über PAR-2) und verschiedene Interleukine (v.a. IL-31, IL-4, IL-13)."},
    {s:2, q:"Welche Mediatoren wirken zentral (spinal) beim Juckreiz?", a:"Opioide (μ pro-, κ antipruritisch), Gastrin-Releasing-Peptide (GRP) und das B-natriuretische Peptid (BNP/NPPB)."},
    {s:2, q:"Ab welcher Dauer spricht man von chronischem Pruritus, und welche 3 Ursachengruppen unterscheidet man?", a:"Juckreiz > 6 Wochen. Gruppen: entzündliche Hauterkrankungen; neuropathisch (Erkrankungen des Nervensystems); systemisch/psychiatrisch (z.B. hepatogen, nephrogen). Häufig Personen > 65 LJ."},
    {s:2, q:"Was ist die Prurigo nodularis und wodurch entsteht sie?", a:"Chronische (> 6 Wo), stark juckende, feste kuppelförmige Papeln/Knoten durch wiederholtes gezieltes Kratzen (Juck-Kratz-Zyklus). Erwachsene, f>m. Assoziiert u.a. mit atopischer Dermatitis, Xerosis, Leber-/Nierenerkrankung, psychiatrischen Erkrankungen, Lymphom, selten soliden Tumoren."},
    {s:2, q:"Was beschreibt das 'Butterfly Sign' bei Prurigo nodularis?", a:"Aussparung des zentralen oberen Rückens: Dieses Areal ist mit den Händen schwer erreichbar, wird nicht gekratzt und bleibt daher läsionsfrei (schmetterlingsförmig)."},
    {s:2, q:"Welches Zytokin gilt als zentrales 'Juckreiz-Zytokin', v.a. bei Prurigo nodularis und atopischer Dermatitis?", a:"IL-31, von Th2-Zellen produziert; bindet an den IL-31-Rezeptor A (IL-31RA) auf sensorischen Neuronen und Keratinozyten."},
    {s:2, q:"Wogegen richten sich Dupilumab bzw. Nemolizumab bei Prurigo nodularis?", a:"Dupilumab blockiert die IL-4-Rezeptor-α-Kette (hemmt IL-4 und IL-13). Nemolizumab blockiert den IL-31-Rezeptor A. Beide sind für die PN zugelassen."},
    {s:2, q:"Was ist der Lichen simplex chronicus?", a:"Umschriebene epidermale Hypertrophie mit Lichenifikation durch chronisches, gewohnheitsmäßiges Reiben/Kratzen. Prädisponierend: Xerosis, atopische Diathese, Psoriasis, Stauungsdermatitis, Angst-/Zwangsstörungen, neuropathischer Juckreiz. Typisch: posterolaterale Halsregion, Knöchel, anogenital."},
    {s:2, q:"Aquagener Pruritus: primäre vs. sekundäre Ursache?", a:"Primär idiopathisch (sehr selten). Sekundär v.a. Polycythaemia vera. Klinik: Jucken/Kribbeln/Brennen innerhalb von 30 min nach Wasserkontakt, meist an den unteren Extremitäten beginnend und aufsteigend."},
    {s:2, q:"Nephrogener (CKD-assoziierter) Pruritus – Therapieoptionen?", a:"Emolientien, Capsaicin, Gabapentin/Pregabalin, UVB-nb-Lichttherapie, μ-Opioid-Antagonist Naltrexon (25–100 mg). Difelikefalin (peripherer κ-Opioid-Agonist) ist speziell dafür zugelassen. Bessert meist nach der Dialyse."},
    {s:2, q:"Notalgia paraesthetica – Klinik und Lokalisation?", a:"Umschriebene, oft hyperpigmentierte, stark juckende Stelle am oberen Rücken entlang des medialen Skapularandes (Erwachsene). Häufig degenerative Wirbelsäulenveränderungen; bei Hinweisen Bildgebung."},
    {s:2, q:"Brachioradialer Pruritus – Nerv, Auslöser und ein pathognomonisches Zeichen?", a:"Sensorische Neuropathie des dorsalen kutanen Astes des N. radialis am Unterarm. RF: kumulative UV-Exposition; in > 50% degenerative HWS-Veränderungen (MRT HWS). Klassisch: 'Ice-pack sign' – Kühlung lindert."},
    {s:2, q:"Meralgia paraesthetica – welcher Nerv, welche Lokalisation?", a:"Kompression des N. cutaneus femoris lateralis beim Durchtritt unter dem Leistenband. Missempfindungen anterolateral am Oberschenkel. RF: Adipositas, Schwangerschaft, enge Kleidung, langes Sitzen."},
    {s:2, q:"Trigeminales trophisches Syndrom – typische Klinik?", a:"Selbstinduzierte Ulzeration des zentralen Gesichts, klassisch an der Ala nasi mit Aussparung der Nasenspitze. Ursache: Dysästhesie/Hypästhesie nach Schädigung des sensiblen N. trigeminus (Schlaganfall, Herpes zoster, Trauma, kraniofaziale OP)."},
    {s:2, q:"Burning Mouth Syndrome (Orodynie) – Definition und Klinik?", a:"Brennende Schmerzen der Mundschleimhaut ohne objektivierbare Schleimhautveränderung, typisch bilateral an den vorderen 2/3 der Zunge, Gaumen und Unterlippe. Mittleres/höheres Alter, f>m. Therapie: trizyklische Antidepressiva, Clonazepam, Gabapentin."},
    {s:2, q:"Wahnhafte Infestation (Dermatozoenwahn/Ekbom) – Leitbefund und Therapie?", a:"Fixe, unverrückbare Überzeugung eines Haut-Befalls trotz fehlender Objektivierbarkeit. Klassisch das 'Matchbox-Zeichen' (mitgebrachte Schuppen/Fasern als vermeintlicher Beweis). Erwachsene > 50, f>m; 'Folie à deux' möglich. Therapie: Antipsychotika."},
    {s:2, q:"Trichotillomanie – Definition und was ist Trichophagie?", a:"Zwanghaftes/habituelles Ausreißen von Haaren (Kopfhaut, Augenbrauen, Wimpern, Scham), Gipfel um die Pubertät; Alopezieherde mit Haaren unterschiedlicher Länge. Trichophagie = zusätzliches Verschlucken der Haare (Risiko Trichobezoar). Therapie: Verhaltenstherapie."},
    {s:2, q:"Skin-picking Disorder – Klinik und ein charakteristisches Beispiel?", a:"Repetitives Kratzen/Drücken/Reiben der Haut (Gesicht, Kopfhaut, Handrücken, Unterarme, oberer Rücken), meist Frauen mittleren Alters; Erosionen/Ulzera in linearen, eckigen oder rund-ovalen Formen. Akne excoriée gehört dazu. Häufige Komorbidität: Zwangsstörung, Depression."},
    {s:2, q:"Dermatitis artefacta – wesentliches Merkmal in Abgrenzung zur Skin-picking Disorder?", a:"Selbst verursachte Läsionen zur Erfüllung eines (meist unbewussten) psychologischen Bedürfnisses; die Betroffenen leugnen die Beteiligung. Bizarre, ungewöhnlich geformte Läsionen mit sehr scharfer Begrenzung. f>>m; assoziiert mit Borderline, Dissoziation. Therapie: Wundversorgung + psychiatrische Anbindung."}
  ];
  const mc = [
    {s:2, q:"Bei einer Patientin mit Prurigo nodularis bleibt der zentrale obere Rücken auffällig läsionsfrei. Wie heißt dieses Zeichen?", o:["Butterfly Sign","Nikolski-Zeichen","Köbner-Phänomen","Darier-Zeichen"], c:0, e:"Butterfly Sign: Der zentrale obere Rücken ist schwer erreichbar, wird nicht gekratzt und bleibt frei. Nikolski/Köbner/Darier gehören zu anderen Entitäten."},
    {s:2, q:"Nemolizumab, zur Behandlung der Prurigo nodularis, blockiert welches Zielmolekül?", o:["IL-4-Rezeptor-α","IL-31-Rezeptor A","IL-5","TSLP"], c:1, e:"Nemolizumab ist ein Anti-IL-31-Rezeptor-A-Antikörper. Die IL-4-Rezeptor-α-Kette wird dagegen von Dupilumab blockiert."},
    {s:2, q:"Difelikefalin ist speziell für den nephrogenen Pruritus zugelassen. Welcher Wirkmechanismus liegt zugrunde?", o:["μ-Opioid-Rezeptor-Antagonist","Peripherer κ-Opioid-Rezeptor-Agonist","H1-Antihistaminikum","Substanz-P-Antagonist"], c:1, e:"Difelikefalin ist ein peripher wirkender κ-Opioid-Rezeptor-Agonist (κ-Agonismus wirkt antipruritisch, μ-Agonismus pruritogen)."},
    {s:2, q:"Ein Patient berichtet über Jucken/Brennen innerhalb von Minuten nach jedem Duschen. Welche systemische Erkrankung muss ausgeschlossen werden?", o:["Polycythaemia vera","Hämochromatose","Morbus Addison","Phäochromozytom"], c:0, e:"Aquagener Pruritus ist sekundär v.a. mit Polycythaemia vera assoziiert; ein Blutbild (Hkt/Hb) ist obligat."},
    {s:2, q:"Bei therapierefraktärem brachioradialem Pruritus mit Besserung durch Kühlung – welche Untersuchung ist am ehesten indiziert?", o:["MRT der Halswirbelsäule","Röntgen-Thorax","Abdomensonografie","Kapillarmikroskopie"], c:0, e:"In > 50% liegen degenerative HWS-Veränderungen mit Wurzelkompression vor; die Besserung durch Kälte ('Ice-pack sign') ist typisch. Daher MRT der HWS."},
    {s:2, q:"Welches Areal ist beim trigeminalen trophischen Syndrom klassischerweise ausgespart?", o:["Nasenspitze","Ala nasi","Wange","Oberlippe"], c:0, e:"Betroffen ist typisch die Ala nasi, während die Nasenspitze ausgespart bleibt (unterschiedliche sensible Versorgung)."},
    {s:2, q:"Ein Patient bringt zur Konsultation ein Döschen mit Hautschuppen und Fasern als 'Beweis' für Parasiten mit. Welche Diagnose ist am wahrscheinlichsten?", o:["Skabies","Wahnhafte Infestation","Prurigo nodularis","Pediculosis"], c:1, e:"Das 'Matchbox-Zeichen' ist typisch für die wahnhafte Infestation (Ekbom-Syndrom); objektive Hinweise auf Parasiten fehlen."},
    {s:2, q:"Welcher trichoskopische Befund spricht am ehesten für eine Trichotillomanie?", o:["Ausrufezeichenhaare mit peripilärem Erythem","Flammenhaare und V-Zeichen","Comma hairs","Yellow dots ohne Haarschäfte"], c:1, e:"Flammenhaare, Hakenhaare, V-Zeichen, Tulip Hair, Black dots und Trichoptilose sprechen für mechanischen Zug. Comma hairs = Tinea capitis; Ausrufezeichenhaare = Alopecia areata."},
    {s:2, q:"Dupilumab ist zur Behandlung der Prurigo nodularis zugelassen. Was ist sein molekulares Ziel?", o:["IL-31-Rezeptor A","JAK1","IL-4-Rezeptor-α","IL-17A"], c:2, e:"Dupilumab blockiert die IL-4-Rezeptor-α-Kette und hemmt so die IL-4- und IL-13-Signaltransduktion."},
    {s:2, q:"Eine junge Patientin ist trotz unauffälligem Hautbefund auf einen von ihr wahrgenommenen 'entstellenden' Makel fixiert und sucht wiederholt Korrektur. Welche Diagnose passt?", o:["Wahnhafte Infestation","Dysmorphophobie (körperdysmorphe Störung)","Trichotillomanie","Dermatitis artefacta"], c:1, e:"Die körperdysmorphe Störung (Dysmorphophobie) ist eine übermäßige Beschäftigung mit einem eingebildeten oder minimalen Makel des Aussehens; gehört zum Zwangsspektrum."}
  ];
  const tf = [
    {s:2, st:"Pruritus wird peripher über unmyelinisierte C-Fasern zum ZNS geleitet.", c:true, e:"Korrekt – Juckreiz nutzt langsam leitende C-Fasern; A-δ-Fasern leiten v.a. scharfen Schmerz."},
    {s:2, st:"Beim 'Butterfly Sign' der Prurigo nodularis bleibt der zentrale obere Rücken ausgespart, weil er schwer zu erreichen ist.", c:true, e:"Korrekt – die schlecht erreichbare Zone wird nicht gekratzt und bleibt läsionsfrei."},
    {s:2, st:"Difelikefalin ist ein μ-Opioid-Rezeptor-Antagonist.", c:false, e:"Falsch – Difelikefalin ist ein peripherer κ-Opioid-Rezeptor-Agonist. Ein μ-Antagonist ist z.B. Naltrexon."},
    {s:2, st:"Beim brachioradialen Pruritus bessern sich die Beschwerden typischerweise durch Wärmeanwendung.", c:false, e:"Falsch – klassisch bessert Kühlung ('Ice-pack sign'); Wärme verschlimmert eher."},
    {s:2, st:"Der aquagene Pruritus ist sekundär am häufigsten mit der Polycythaemia vera assoziiert.", c:true, e:"Korrekt – bei aquagenem Pruritus ist eine Polycythaemia vera auszuschließen."},
    {s:2, st:"Beim trigeminalen trophischen Syndrom ist typischerweise die Nasenspitze betroffen und die Ala nasi ausgespart.", c:false, e:"Falsch – es ist umgekehrt: Die Ala nasi ist betroffen, die Nasenspitze bleibt ausgespart."},
    {s:2, st:"Naltrexon wirkt als μ-Opioid-Rezeptor-Antagonist antipruritisch.", c:true, e:"Korrekt – zentrale μ-Opioid-Aktivierung ist pruritogen; ihre Blockade wirkt antipruritisch (u.a. bei nephrogenem Pruritus)."},
    {s:2, st:"Patienten mit Dermatitis artefacta geben die Selbstverletzung in der Regel offen zu.", c:false, e:"Falsch – die Läsionen sind selbst verursacht, die Betroffenen leugnen jedoch meist ihre Beteiligung."}
  ];
  const cloze = [
    {s:2, parts:["Von chronischem Pruritus spricht man ab einer Dauer von mehr als ","BLANK"," Wochen."], a:["6"]},
    {s:2, parts:["Bei der Prurigo nodularis ist das Zytokin ","BLANK"," zentral; der Antikörper ","BLANK"," blockiert dessen Rezeptor (IL-31RA)."], a:["IL-31","Nemolizumab"]},
    {s:2, parts:["Der aquagene Pruritus ist sekundär am häufigsten mit der ","BLANK"," assoziiert."], a:["Polycythaemia vera"]},
    {s:2, parts:["Der ","BLANK"," Pruritus betrifft den dorsalen Ast des N. radialis; als Bildgebung wird ein MRT der ","BLANK"," empfohlen."], a:["brachioradiale","Halswirbelsäule"]},
    {s:2, parts:["Bei der wahnhaften Infestation ist das ","BLANK","-Zeichen typisch (mitgebrachte Schuppen/Fasern als vermeintlicher Beleg)."], a:["Matchbox"]},
    {s:2, parts:["Difelikefalin ist ein peripher wirkender κ-Opioid-Rezeptor-","BLANK"," und ist speziell für den ","BLANK"," Pruritus zugelassen."], a:["Agonist","nephrogenen"]}
  ];
  const match = [
    {s:2, t:"Neuropathischer Pruritus ↔ Nerv / Lokalisation", p:[["Notalgia paraesthetica","Oberer Rücken, medialer Skapularand"],["Brachioradialer Pruritus","Dorsaler Unterarm (N. radialis)"],["Meralgia paraesthetica","Anterolateraler Oberschenkel (N. cut. femoris lat.)"],["Trigeminales trophisches Syndrom","Ala nasi"],["Burning Mouth Syndrome","Vordere 2/3 der Zunge"]]},
    {s:2, t:"Antipruritische Substanz ↔ Target / Mechanismus", p:[["Dupilumab","IL-4-Rezeptor-α"],["Nemolizumab","IL-31-Rezeptor A"],["Naltrexon","μ-Opioid-Antagonist"],["Difelikefalin","κ-Opioid-Agonist"],["Upadacitinib","JAK-Inhibitor"]]},
    {s:2, t:"Psychokutane Erkrankung ↔ Leitbefund", p:[["Wahnhafte Infestation","Matchbox-Zeichen"],["Trichotillomanie","Haare unterschiedlicher Länge / Flammenhaare"],["Skin-picking Disorder","Akne excoriée"],["Dermatitis artefacta","Bizarre Läsionen, scharf begrenzt"]]}
  ];
  const freetext = [
    {s:2, q:"Erläutern Sie Pathogenese, ein klinisches Leitzeichen und die Stufentherapie der Prurigo nodularis.", a:"Pathogenese: Chronischer Pruritus (> 6 Wochen) führt über wiederholtes Kratzen zu einem Juck-Kratz-Zyklus mit neuronaler und Th2-vermittelter Sensibilisierung; das Zytokin IL-31 spielt eine Schlüsselrolle. Assoziationen: atopische Dermatitis, Xerosis cutis, Leber-/Nierenerkrankungen, psychiatrische Erkrankungen, Lymphom, selten solide Tumoren. Klinik: multiple feste, kuppelförmige, stark juckende Papeln/Knoten an Streckseiten, lumbosakral und gluteal; Leitzeichen ist das Butterfly Sign (Aussparung des schwer erreichbaren zentralen oberen Rückens). Therapie in Stufen: (1) Grundkrankheit behandeln, Basispflege/Rückfettung, ggf. Menthol-Cold-Cream zur Kühlung; (2) topische/intraläsionale Kortikosteroide, Calcineurin-Inhibitoren, UV-Therapie; (3) systemisch Gabapentinoide/Antidepressiva; (4) zielgerichtet Dupilumab (Anti-IL-4Rα) oder Nemolizumab (Anti-IL-31RA) sowie JAK-Inhibitoren wie Upadacitinib. Ziel ist die Durchbrechung des Juck-Kratz-Zyklus."},
    {s:2, q:"Beschreiben Sie das Konzept des neuropathischen Pruritus und die drei klassischen sensorischen Mononeuropathien mit Lokalisation und Diagnostik.", a:"Neuropathischer Pruritus entsteht durch Schädigung, Kompression oder Reizung eines Nervs; die Hautveränderungen sind auf dessen Innervationsgebiet begrenzt und oft von Dysästhesien begleitet. (1) Notalgia paraesthetica: umschriebener, häufig hyperpigmentierter Juckreiz am oberen Rücken entlang des medialen Skapularandes; häufig degenerative Wirbelsäulenveränderungen, bei Hinweisen Bildgebung. (2) Brachioradialer Pruritus: dorsaler Unterarm im Versorgungsgebiet des N. radialis; Risikofaktor kumulative UV-Exposition, in > 50% degenerative HWS-Veränderungen – daher MRT der HWS; typisch bessert Kühlung ('Ice-pack sign'). (3) Meralgia paraesthetica: Kompression des N. cutaneus femoris lateralis unter dem Leistenband mit Missempfindungen anterolateral am Oberschenkel; Risikofaktoren Adipositas, Schwangerschaft, enge Kleidung. Therapieprinzip: auslösende Faktoren adressieren, Kühlung, topisches Capsaicin, Gabapentin/Pregabalin, Emolientien."}
  ];
  const img = [
    {s:2, cap:"Läsionsverteilung am Rücken bei chronischem Pruritus", q:"Der zentrale obere Rücken bleibt läsionsfrei. Wie heißt dieses Zeichen und was erklärt die Aussparung?", o:["Butterfly Sign – Areal für die Hände schwer erreichbar","Nikolski-Zeichen – Ausdruck einer Akantholyse","Köbner-Phänomen – isomorpher Reizeffekt","Auspitz-Zeichen – punktförmige Blutung"], c:0, e:"Butterfly Sign der Prurigo nodularis: Der zentrale obere Rücken ist mit den Händen schwer erreichbar, wird nicht gekratzt und bleibt daher läsionsfrei (Schmetterlingsform).", svg:`<svg viewBox="0 0 280 360" xmlns="http://www.w3.org/2000/svg"><ellipse cx="140" cy="42" rx="26" ry="30" fill="#fce7f3" stroke="#9ca3af" stroke-width="2"/><path d="M95,80 L80,110 L78,220 L84,300 L112,300 L118,210 L162,210 L168,300 L196,300 L202,220 L200,110 L185,80 Z" fill="#fce7f3" stroke="#9ca3af" stroke-width="2"/><path d="M80,110 L56,130 L42,232 L54,236 L68,150 L82,134 Z" fill="#fce7f3" stroke="#9ca3af" stroke-width="2"/><path d="M200,110 L224,130 L238,232 L226,236 L212,150 L198,134 Z" fill="#fce7f3" stroke="#9ca3af" stroke-width="2"/><path d="M140,124 L110,100 C98,112 98,142 112,152 Z M140,124 L170,100 C182,112 182,142 168,152 Z" fill="#fdf2f8" stroke="#9ca3af" stroke-width="1.5" stroke-dasharray="4,3"/><g fill="#dc2626" opacity="0.72"><ellipse cx="120" cy="178" rx="7" ry="5"/><ellipse cx="160" cy="178" rx="7" ry="5"/><ellipse cx="128" cy="240" rx="8" ry="6"/><ellipse cx="152" cy="240" rx="8" ry="6"/><ellipse cx="140" cy="268" rx="9" ry="6"/><ellipse cx="114" cy="212" rx="6" ry="5"/><ellipse cx="166" cy="212" rx="6" ry="5"/><ellipse cx="90" cy="128" rx="6" ry="5"/><ellipse cx="190" cy="128" rx="6" ry="5"/><ellipse cx="52" cy="205" rx="6" ry="9"/><ellipse cx="228" cy="205" rx="6" ry="9"/><ellipse cx="132" cy="288" rx="7" ry="5"/><ellipse cx="150" cy="290" rx="6" ry="5"/></g><text x="126" y="130" font-size="9" fill="#374151" font-family="sans-serif">frei</text><text x="44" y="332" font-size="11" fill="#374151" font-family="sans-serif">Butterfly Sign: oberer Rücken ausgespart</text></svg>`}
  ];

  FLASH.push(...flash);
  MC.push(...mc);
  TF.push(...tf);
  CLOZE.push(...cloze);
  MATCH.push(...match);
  FREETEXT.push(...freetext);
  IMG.push(...img);
})();
