/* Dermaapp – Sektion 4: Urtikaria, Erytheme & Purpura / Vaskulitiden & Arzneireaktionen. Auto-generiert aus Facharzt-Unterlagen. */
(function () {
  const flash = [
    {s:4, q:"Welche immunologischen vs. nicht-immunologischen Mechanismen können eine mastzellvermittelte Urtikaria auslösen?", a:"Immunologisch: Autoantikörper gegen FcεRI oder gegen IgE, allergisch via IgE, sowie über Immunkomplexe (z.B. Urtikariavaskulitis). Nicht-immunologisch: direkte Mastzell-Degranulation durch Opioide, Brennnessel-Kontakt oder NSAR (via Leukotrien-Erhöhung)."},
    {s:4, q:"Wie ist der UAS7 aufgebaut und ab welchem Wert gilt die Urtikaria als schwer?", a:"Der Urtikaria-Aktivitätsscore addiert täglich Quaddelzahl (0-3) und Juckreiz (0-3), also max. 6/Tag. Über 7 Tage summiert ergibt sich der UAS7 (Maximum 42). Werte ≥28 gelten als schwer, <7 als gut kontrolliert, 0 als erscheinungsfrei."},
    {s:4, q:"Was weist der autologe Serumtest (ASST) bei chronischer spontaner Urtikaria nach?", a:"Intrakutane Injektion von frischem Eigenserum (50 µL, volarer Unterarm) mit NaCl- und Histamin-Kontrolle, Ablesung nach 15 und 30 min. Eine Quaddel spricht für eine autoreaktive/autoimmune Urtikaria mit funktionellen Auto-AK gegen FcεRI oder IgE."},
    {s:4, q:"Mit welchen Grunderkrankungen ist die chronische spontane Urtikaria assoziiert und welche Basisdiagnostik empfiehlt sich?", a:"Assoziiert v.a. mit Autoimmunthyreoiditis, ferner Zöliakie, H. pylori, Vitiligo, Diabetes und rheumatoider Arthritis. Basislabor: Gesamt-IgE, Anti-TPO, Blutbild und CRP."},
    {s:4, q:"Beschreibe Trigger und Morphologie der cholinergischen Urtikaria.", a:"Auslösung durch Schweißinduktion (Sport, Stress, heiße Bäder, Alkohol, scharfes Essen), meist junge Patienten mit atopischer Diathese oder Hypohidrose. Kleinherdige (2-3 mm), monomorphe Quaddeln der oberen Körperhälfte; cholinerg mit rötlichem Halo um weißliche Urtica."},
    {s:4, q:"Kälteurtikaria: welche systemische Assoziation muss abgeklärt werden?", a:"In ca. 5% besteht eine Kryoglobulinämie; dort sind zusätzlich Raynaud-Symptomatik oder Purpura objektivierbar. Bei familiärer Kältereaktion an CAPS (Cryopyrin-assoziierte periodische Syndrome) denken."},
    {s:4, q:"Skizziere die Stufentherapie der chronischen spontanen Urtikaria.", a:"Stufe 1: nicht-sedierendes H1-Antihistaminikum in Standarddosis. Stufe 2: Dosissteigerung bis 4-fach. Stufe 3: Add-on Omalizumab (Anti-IgE). Stufe 4: Ciclosporin. Zusätzlich Mastzellstimulatoren (NSAR, Opioide) meiden, bei ASS-/NSAR-Intoleranz off-label Montelukast."},
    {s:4, q:"Warum treten beim bradykininvermittelten Angioödem keine Quaddeln auf?", a:"Es liegt keine Mastzellaktivierung vor; das Ödem entsteht durch Bradykinin in tiefer Dermis und Subkutis. Daher fehlen die oberflächlichen, histaminbedingten juckenden Quaddeln, und es zeigt sich nur eine diffuse, meist nicht juckende Schwellung."},
    {s:4, q:"Hereditäres Angioödem Typ III – Genetik und klinische Besonderheit?", a:"F12-Genmutation (Chromosom 12) mit erhöhter Faktor-XII-Aktivität; C4 ist normal, C1-Esterase-Inhibitor weder defizient noch dysfunktional. Betrifft v.a. Frauen (östrogenabhängig), oft vermehrte Gesichts-/Larynxbeteiligung mit hoher Mortalität."},
    {s:4, q:"Warum ist C4 beim hereditären Angioödem Typ I/II erniedrigt?", a:"Der fehlende/dysfunktionale C1-Esterase-Inhibitor kann C1r und C1s nicht mehr hemmen. Die aktive Protease C1s spaltet daraufhin ungebremst C4, das dadurch verbraucht wird – es resultiert eine C4-Hypokomplementämie."},
    {s:4, q:"Welche Optionen gibt es zur Langzeitprophylaxe des hereditären Angioödems Typ I/II?", a:"Regelmäßige C1-Esterase-Inhibitor-Substitution i.v. (Cinryze), attenuierte Androgene p.o. (Danazol, in CH nicht zugelassen), kurzfristig Tranexamsäure, sowie die Kallikrein-gerichteten Antikörper Lanadelumab und Berotralstat."},
    {s:4, q:"Warum verursachen ACE-Hemmer ein Angioödem ohne Urtikaria und wann tritt es auf?", a:"ACE (Kininase II) baut Bradykinin ab; unter ACE-Hemmung akkumuliert Bradykinin, was ein tiefes Ödem ohne Mastzellbeteiligung (keine Quaddeln) auslöst. Das Angioödem kann Tage bis Jahre nach Therapiebeginn erstmals auftreten."},
    {s:4, q:"Anaphylaxie – was ist die Erstlinientherapie und über welchen Applikationsweg?", a:"Adrenalin ist die Erstlinientherapie und wird intramuskulär in den anterolateralen Oberschenkel (M. vastus lateralis) injiziert (Erwachsene ~0,5 mg 1:1000). Ergänzend Lagerung, Sauerstoff, Volumen sowie Antihistaminika und Kortikosteroide als Zweitlinie."},
    {s:4, q:"Erythema anulare centrifugum – Unterschied superfizielle vs. tiefe Form?", a:"Die superfizielle Variante zeigt eine charakteristische innere, nach innen nachziehende Schuppenkrause (trailing scale); die tiefe (profunde) Form ist infiltrierter und weist keine trailing scale auf. Häufigster infektiöser Trigger ist eine Tinea (v.a. Tinea pedis)."},
    {s:4, q:"Nekrolytisches migratorisches Erythem – zugrunde liegender Tumor und Klinik?", a:"Marker des Glukagonoms (langsam wachsender pankreatischer Alphazell-Tumor, 5-Jahres-Mortalität ~50%). Hyperglukagonämie führt zu anulären erythematösen Maculae mit krustösen Erosionen an Stamm/anogenital/Beinen, dazu Zungenatrophie und Lippenfissuren; begleitend Diabetes, Diarrhoe, TVT."},
    {s:4, q:"Erythema gyratum repens – Morphologie und häufigste Assoziation?", a:"Baumring-/holzmaserartige, konzentrisch-anuläre Erytheme mit rascher Ausbreitung (bis 1 cm/Tag). Fast immer paraneoplastisch, v.a. bei Bronchial-/Mammakarzinom, seltener Ösophagus-/Magenkarzinom; vermutlich Kreuzreaktivität von Antikörpern gegen Tumor- und Hautantigen."},
    {s:4, q:"Acrodermatitis chronica atrophicans – Stadium und typischer Erreger?", a:"Kutane Manifestation des Lyme-Spätstadiums (Monate bis Jahre nach unbehandeltem Frühstadium), in Europa v.a. durch Borrelia afzelii. Initial livide, ödematöse, später atrophe, hyperpigmentierte, haarlose Areale an Extremitätenstreckseiten/Handrücken; Therapie Doxycyclin 21-28 Tage."},
    {s:4, q:"Wie unterscheiden sich typische von atypischen Target-Läsionen beim Erythema multiforme?", a:"Typische Kokarden zeigen mindestens drei verschiedene Zonen (zentrale Nekrose/Blase, hellerer Ring, erythematöser Randsaum). Atypische Läsionen sind papulös mit nur zwei Zonen und/oder unscharfer Begrenzung."},
    {s:4, q:"Erythema multiforme Minor vs. Major – Hauptunterschied?", a:"Beim Minor-Typ fehlt eine relevante Schleimhautbeteiligung und es bestehen keine Systemsymptome. Der Major-Typ zeigt moderate bis schwere mukosale Beteiligung (oral >> anogenital > okulär) plus Fieber, Arthralgien und AZ-Reduktion – aber KEINEN Übergang in eine TEN."},
    {s:4, q:"Rezidivierendes Erythema multiforme (>6 Schübe/Jahr) – Therapie?", a:"Antivirale Dauerprophylaxe für mindestens 6 Monate (z.B. Valaciclovir/Aciclovir), auch ohne nachgewiesenen HSV-Bezug; bei schwerem Verlauf höher dosiert. Bei Versagen: Thalidomid, Azathioprin, Dapson, Ciclosporin oder MMF."},
    {s:4, q:"Welches lösliche Molekül gilt als Schlüsselmediator der Keratinozytenapoptose bei SJS/TEN?", a:"Granulysin, freigesetzt von aktivierten CD8+-T-Zellen, NK- und NKT-Zellen, gilt als wichtigster Mediator des ausgedehnten Keratinozytentods. Beteiligt sind zudem der Fas/FasL-Weg sowie Perforin/Granzym B."},
    {s:4, q:"Nikolski-Zeichen I und II – Definition?", a:"Nikolski I: Blasenbildung bzw. Epidermisverschiebung in scheinbar intakter Haut auf tangentialen Schiebedruck. Nikolski II: seitliche Verschieblichkeit einer bereits bestehenden Blase (Asboe-Hansen). Positiv u.a. bei SJS/TEN, Pemphigus und SSSS."},
    {s:4, q:"Wie lange nach Beginn der auslösenden Medikation tritt SJS/TEN typischerweise auf?", a:"Meist 7-28 Tage nach Beginn der culprit-Medikation; bei Antikonvulsiva kann die Latenz bis zu 2 Monate betragen. Prodromal 1-3 Tage vor dem Exanthem oft Fieber, brennende Augen und Schluckbeschwerden."},
    {s:4, q:"DRESS – typische Latenz und wichtigste Organbeteiligung?", a:"Beginn spät, ca. 2-8 Wochen nach Medikamentenexposition. Führende Organbeteiligung ist die Hepatitis (Hauptursache der ~10% Mortalität), daneben Nephritis, Myokarditis, Pneumonitis und Thyreoiditis; charakteristisch sind Gesichtsödem und Eosinophilie."},
    {s:4, q:"AGEP – wichtigste Differentialdiagnose und wegweisender Laborbefund?", a:"Wichtigste DD ist die pustulöse Psoriasis (Typ von Zumbusch); ferner subkorneale Pustulose (Sneddon-Wilkinson) und disseminierte Follikulitis. Laborchemisch typisch ist eine ausgeprägte Leukozytose mit Neutrophilie."},
    {s:4, q:"Fixes Arzneiexanthem – Klinik, typische Auslöser und Rezidivverhalten?", a:"Eine oder wenige runde, scharf begrenzte erythematös-livide Plaques (ggf. bullös) v.a. an Lippen, Genital, Händen/Füßen. Auslöser: Sulfonamide, Tetrazykline, Betalaktame, NSAR, Pseudoephedrin, Barbiturate. Bei Reexposition Rezidiv an identischer Stelle innerhalb ~24 h, oft mit Aggravation."},
    {s:4, q:"Kumarin-(Warfarin-)Nekrose – Pathomechanismus und Prädilektionsstellen?", a:"Paradoxe transiente Hyperkoagulabilität durch rascheren Abfall von Protein C (und Faktor VII) als der prokoagulatorischen Faktoren, mit Mikrothrombosen und Hautnekrose. Beginn ~2-5 Tage nach Start, bevorzugt an fettreichen Arealen: Mammae, Abdomen, Hüfte, Gesäß."},
    {s:4, q:"Erythema nodosum – Pannikulitis-Typ, Abheilung und wichtige Auslöser?", a:"Septale Pannikulitis ohne Vaskulitis; druckschmerzhafte, erythematöse Knoten prätibial, die kontusiform (blau-grün-gelb) und stets narben- und ulzerationsfrei abheilen. Auslöser: Streptokokken, Sarkoidose (Löfgren), Medikamente (OK, Sulfonamide), CED, Tuberkulose, Behçet, Schwangerschaft."}
  ];
  const mc = [
    {s:4, q:"Welcher Autoantikörper liegt der autoimmunen Form der chronischen spontanen Urtikaria zugrunde?", o:["Auto-AK gegen den hochaffinen IgE-Rezeptor (FcεRIα)","Anti-Dsg3","Anti-BP180","Anti-C1q"], c:0, e:"Die autoreaktive/autoimmune chronische Urtikaria beruht auf funktionellen Auto-AK gegen FcεRIα oder gegen membrangebundenes IgE. Anti-C1q findet sich bei der Urtikariavaskulitis."},
    {s:4, q:"Was ist der molekulare Angriffspunkt von Omalizumab?", o:["IL-4-Rezeptor-α","Freies IgE","IL-5","Bradykinin-B2-Rezeptor"], c:1, e:"Omalizumab ist ein humanisierter Anti-IgE-Antikörper, der freies IgE bindet und so die Mastzell-/Basophilen-Aktivierung reduziert; Standardoption bei antihistaminika-refraktärer chronischer Urtikaria."},
    {s:4, q:"Icatibant, eingesetzt bei der akuten Attacke des hereditären Angioödems, wirkt wie?", o:["C1-Esterase-Inhibitor-Substitution","Bradykinin-B2-Rezeptor-Antagonist","Kallikrein-Antikörper","H1-Antihistaminikum"], c:1, e:"Icatibant blockiert als Antagonist den Bradykinin-B2-Rezeptor ('I cat ban – bannt Bradykinin vom Rezeptor'). C1-INH-Substitution erfolgt mit Berinert/Cinryze, Kallikrein-AK ist Lanadelumab."},
    {s:4, q:"Welches Gen ist beim hereditären Angioödem Typ III (normaler C1-Esterase-Inhibitor) klassisch mutiert?", o:["SERPING1 (C1NH)","F12 (Faktor XII)","UBA1","SERPINA1"], c:1, e:"Typ III beruht klassisch auf einer F12-Mutation mit gesteigerter Faktor-XII-Aktivität; C4 und C1-INH sind normal. SERPING1/C1NH ist bei Typ I/II betroffen."},
    {s:4, q:"Ein Patient entwickelt binnen Minuten nach Wespenstich generalisierte Urtikaria, Bronchospasmus und Hypotonie. Was ist die sofortige Erstlinientherapie?", o:["Intravenöses Antihistaminikum","Intramuskuläres Adrenalin","Orales Prednison","Inhalatives Salbutamol"], c:1, e:"Bei Anaphylaxie ist intramuskuläres Adrenalin (anterolateraler Oberschenkel) die lebensrettende Erstlinie. Antihistaminika, Steroide und Bronchodilatatoren sind nur adjuvant."},
    {s:4, q:"Das nekrolytische migratorische Erythem ist ein Hautmarker welches Tumors?", o:["Insulinom","Glukagonom","Gastrinom","Phäochromozytom"], c:1, e:"Das nekrolytische migratorische Erythem ist paraneoplastischer Marker des Glukagonoms (pankreatischer Alphazell-Tumor) mit Hyperglukagonämie, Diabetes und Gewichtsverlust."},
    {s:4, q:"Erythema gyratum repens ist am häufigsten mit welchem Malignom assoziiert?", o:["Bronchialkarzinom","Prostatakarzinom","Malignes Melanom","Nierenzellkarzinom"], c:0, e:"Erythema gyratum repens ist ein hochgradig paraneoplastisches Phänomen, am häufigsten beim Bronchial- und Mammakarzinom, seltener Ösophagus-/Magenkarzinom."},
    {s:4, q:"Welches von zytotoxischen Zellen freigesetzte Molekül gilt als wichtigster Mediator der ausgedehnten Keratinozytenapoptose bei der TEN?", o:["Histamin","Granulysin","Bradykinin","IL-31"], c:1, e:"Granulysin (aus CD8+-T-, NK- und NKT-Zellen) gilt als Schlüsselmediator der Keratinozytennekrose bei SJS/TEN; ergänzend wirken Fas/FasL sowie Perforin/Granzym B."},
    {s:4, q:"Welches HLA-Allel ist bei Europäern mit Carbamazepin-induziertem DRESS/SJS assoziiert?", o:["HLA-A*31:01","HLA-B*27","HLA-DQB1*02:01","HLA-C*06:02"], c:0, e:"Bei Europäern (und Japanern) ist HLA-A*31:01 mit Carbamazepin-Hypersensitivität assoziiert. HLA-B*15:02 ist dagegen der Risikomarker bei Han-Chinesen/Südostasiaten."},
    {s:4, q:"Vor Beginn welcher Substanz wird HLA-B*57:01 zum Ausschluss einer schweren Hypersensitivität getestet?", o:["Allopurinol","Abacavir","Carbamazepin","Dapson"], c:1, e:"HLA-B*57:01 prädisponiert für die Abacavir-Hypersensitivität; ein Screening vor Therapiestart ist Standard. Allopurinol-SCAR ist mit HLA-B*58:01 assoziiert."},
    {s:4, q:"Welcher Befund spricht am ehesten für eine AGEP und gegen eine TEN?", o:["Zahlreiche nicht-follikuläre sterile Pusteln (<5 mm), Beginn <4 Tage","Ausgedehnte epidermale Ablösung >30% KOF","Positives Nikolski-Zeichen der gesamten Haut","Fibrinbelegte Schleimhauterosionen"], c:0, e:"Für AGEP typisch sind viele kleine sterile, nicht-follikuläre Pusteln auf Erythem mit sehr raschem Beginn (<4 Tage) und Leukozytose; ausgedehnte Epidermolyse und Schleimhauterosionen sprechen für SJS/TEN."},
    {s:4, q:"Ein Patient entwickelt nach erneuter Sulfonamid-Einnahme innerhalb eines Tages eine livide Plaque genau an der Stelle einer früheren Läsion. Diagnose?", o:["Erythema multiforme","Fixes Arzneiexanthem","Urtikaria","AGEP"], c:1, e:"Charakteristisch für das fixe Arzneiexanthem ist das Rezidiv an identischer Stelle innerhalb von ~24 h nach Reexposition; klassische Auslöser sind Sulfonamide, Tetrazykline und NSAR."},
    {s:4, q:"Welche der folgenden Vaskulitiden gehört zu den ANCA-assoziierten Kleingefäßvaskulitiden?", o:["Mikroskopische Polyangiitis","Polyarteriitis nodosa","Takayasu-Arteriitis","Riesenzellarteriitis"], c:0, e:"Die mikroskopische Polyangiitis ist eine pauci-immune ANCA-assoziierte Kleingefäßvaskulitis (meist MPO/pANCA). PAN ist eine Vaskulitis mittelgroßer, Takayasu und Riesenzellarteriitis große Gefäße."},
    {s:4, q:"Was trifft auf den Begriff 'leukozytoklastische Vaskulitis' zu?", o:["Es ist eine eigenständige klinische Diagnose","Es ist ein rein histologischer Terminus","Er beweist einen systemischen Organbefall","Er schließt eine ANCA-Vaskulitis aus"], c:1, e:"Leukozytoklastische Vaskulitis ist ein rein histologischer Befund (Kernstaub, Fibrinoidnekrose der Kleingefäße) und keine Diagnose; er kommt bei zahlreichen Vaskulitiden vor, auch systemischen."},
    {s:4, q:"Welche verzögert (bis 6 Monate) auftretende Organkomplikation ist bei der IgA-Vaskulitis prognosebestimmend?", o:["Glomerulonephritis","Myokarditis","Pneumonitis","Optikusneuritis"], c:0, e:"Die IgA-vermittelte Glomerulonephritis (in ~50%) kann sich bis zu 6 Monate nach Beginn entwickeln und bestimmt die Langzeitprognose; Erwachsene sind häufiger und schwerer betroffen."},
    {s:4, q:"Wie lautet die klassische (Meltzer-)Trias der kryoglobulinämischen Vaskulitis (Typ II/III)?", o:["Purpura, Arthralgien, Fatigue","Fieber, Arthritis, Karditis","Purpura, Bauchschmerz, Hämaturie","Livedo, Raynaud, Nekrose"], c:0, e:"Die klassische Trias der gemischten kryoglobulinämischen Vaskulitis besteht aus palpabler Purpura, Arthralgien und Fatigue/Schwäche; sie ist – anders als Typ I – nicht kälteabhängig."},
    {s:4, q:"Welches Organ bleibt bei der systemischen (klassischen) Polyarteriitis nodosa typischerweise verschont?", o:["Nieren","Lunge","Herz","Gastrointestinaltrakt"], c:1, e:"Die klassische PAN kann potenziell alle Organe befallen, spart aber typischerweise die Lunge aus. Die Nierenbeteiligung erfolgt über Ischämie/renovaskuläre Hypertonie, NICHT als Glomerulonephritis."},
    {s:4, q:"Welche drei Antikörper-Tests gehören zu den Laborkriterien (revidierte Sapporo) des Antiphospholipidsyndroms?", o:["ANA, anti-dsDNA, anti-Sm","Lupus-Antikoagulans, Anticardiolipin, Anti-β2-Glykoprotein-I","cANCA, pANCA, anti-MPO","Anti-Ro/SSA, anti-La/SSB, RF"], c:1, e:"Die Laborkriterien umfassen Lupus-Antikoagulans, Anticardiolipin-AK (IgG/IgM) und Anti-β2-Glykoprotein-I-AK (IgG/IgM), positiv bei zwei Anlässen im Abstand von ≥12 Wochen."},
    {s:4, q:"Ein Dialysepatient entwickelt sehr schmerzhafte retiforme Purpura mit Nekrosen an den Oberschenkeln. Welche Diagnose und welche spezifische Therapie sind am ehesten indiziert?", o:["Kryoglobulinämie Typ I – Plasmapherese","Kalziphylaxie – Natriumthiosulfat","IgA-Vaskulitis – Prednisolon","Cholesterinembolie – Statin"], c:1, e:"Bild und Terminalniereninsuffizienz sprechen für eine Kalziphylaxie (kalzifizierende urämische Arteriolopathie); neben Optimierung des Kalzium-Phosphat-Haushalts wird Natriumthiosulfat eingesetzt."},
    {s:4, q:"Welches Gen ist beim VEXAS-Syndrom somatisch mutiert?", o:["MEFV","UBA1","NLRP3","TNFRSF1A"], c:1, e:"VEXAS beruht auf einer erworbenen somatischen UBA1-Mutation (X-chromosomal), die das E1-Enzym der Ubiquitinierung betrifft; betroffen sind fast ausschließlich Männer >50 Jahre."},
    {s:4, q:"Bei welcher malignen Erkrankung tritt das paraneoplastische Sweet-Syndrom am häufigsten auf?", o:["Akute myeloische Leukämie","Basalzellkarzinom","Prostatakarzinom","Hodgkin-Lymphom"], c:0, e:"Das malignom-assoziierte Sweet-Syndrom ist am häufigsten mit der akuten myeloischen Leukämie assoziiert; klinisch sukkulente, schmerzhafte Plaques mit Fieber und Neutrophilie."},
    {s:4, q:"Ein Patient mit TEN: welcher Parameter erhöht den SCORTEN-Punktwert?", o:["Herzfrequenz > 120/min","Thrombozyten < 50 G/L","Kreatinin < 50 µmol/L","Körpertemperatur > 38 °C"], c:0, e:"SCORTEN-Variablen sind u.a. Alter >40 J, Malignom, Herzfrequenz >120/min, abgelöste KOF >10%, Harnstoff >10 mmol/L, Glukose >14 mmol/L und Bikarbonat <20 mmol/L. Thrombozytenzahl und Temperatur gehören nicht dazu."}
  ];
  const tf = [
    {s:4, st:"Beim bradykininvermittelten Angioödem sind Antihistaminika, Steroide und Adrenalin weitgehend wirkungslos, da keine Mastzellaktivierung vorliegt.", c:true, e:"Korrekt – da das Ödem bradykinin- und nicht histaminvermittelt ist, greift die klassische antiallergische Therapie nicht; nötig sind C1-INH-Substitution, Icatibant oder Kallikrein-Hemmer."},
    {s:4, st:"Omalizumab ist ein Anti-IL-5-Antikörper und wird bei chronischer spontaner Urtikaria eingesetzt.", c:false, e:"Falsch – Omalizumab ist ein Anti-IgE-Antikörper. Anti-IL-5-Antikörper (z.B. Mepolizumab) wirken auf eosinophile Erkrankungen."},
    {s:4, st:"Bei der verzögerten Druckurtikaria können Quaddeln erst nach mehreren Stunden (bis ca. 12 h) an druckbelasteten Stellen auftreten.", c:true, e:"Korrekt – die verzögerte Druckurtikaria manifestiert sich charakteristisch mit Latenz von bis zu 12 h nach Druckexposition und zählt zu den DD der Persistenz >24 h."},
    {s:4, st:"Ein negativer Borrelien-IgM-Titer schließt in der Frühphase ein Erythema chronicum migrans sicher aus.", c:false, e:"Falsch – das ECM ist eine klinische Diagnose; spezifisches IgM wird erst nach 3-6 Wochen positiv und ist häufig falsch-negativ. Eine Serologie ist im Frühstadium nicht wegweisend."},
    {s:4, st:"Der wichtigste infektiöse Auslöser des rezidivierenden Erythema multiforme ist das Herpes-simplex-Virus.", c:true, e:"Korrekt – HSV ist der häufigste Trigger; bei >6 Rezidiven/Jahr ist eine antivirale Dauerprophylaxe (≥6 Monate) indiziert, auch ohne beweisbaren HSV-Bezug."},
    {s:4, st:"Bei SJS/TEN ist eine Schleimhautbeteiligung fakultativ und fehlt in den meisten Fällen.", c:false, e:"Falsch – SJS/TEN geht praktisch immer mit mukosaler Beteiligung einher (fibrinbelegte Erosionen an mindestens zwei Schleimhäuten)."},
    {s:4, st:"Die AGEP beginnt typischerweise innerhalb von 4 Tagen nach Einnahme des auslösenden Medikaments.", c:true, e:"Korrekt – die akute generalisierte exanthematische Pustulose hat einen sehr kurzen Onset (<4 Tage) und heilt nach ~2 Wochen mit collarette-artiger Desquamation ab."},
    {s:4, st:"Im Gegensatz zur Granulomatose mit Polyangiitis zeigt die mikroskopische Polyangiitis histologisch keine granulomatöse Entzündung.", c:true, e:"Korrekt – die MPA ist eine rein nekrotisierende Vaskulitis ohne Granulome; die granulomatöse Gewebeentzündung ist charakteristisch für die GPA."},
    {s:4, st:"Die klassische (systemische) Polyarteriitis nodosa befällt typischerweise auch die Lunge.", c:false, e:"Falsch – die klassische PAN spart die Lunge typischerweise aus und befällt mittelgroße Arterien anderer Organe (Niere, Herz, GIT, Haut, Nerven)."},
    {s:4, st:"Die Kalziphylaxie betrifft fast ausschließlich Patienten mit normaler Nierenfunktion.", c:false, e:"Falsch – die Kalziphylaxie ist eine kalzifizierende urämische Arteriolopathie und tritt ganz überwiegend bei terminaler Niereninsuffizienz/Dialyse auf; weitere Risikofaktoren sind Warfarin und Adipositas."}
  ];
  const cloze = [
    {s:4, parts:["Beim hereditären Angioödem Typ I und II ist der ","BLANK"," vermindert oder funktionslos; laborchemisch findet sich typischerweise ein erniedrigtes ","BLANK","."], a:["C1-Esterase-Inhibitor","C4"]},
    {s:4, parts:["Der UAS7 summiert täglich Quaddelzahl und Juckreiz (je 0-3) über sieben Tage und hat einen Maximalwert von ","BLANK","."], a:["42"]},
    {s:4, parts:["Die Erstlinientherapie der Anaphylaxie ist ","BLANK",", das ","BLANK"," in den anterolateralen Oberschenkel injiziert wird."], a:["Adrenalin","intramuskulär"]},
    {s:4, parts:["Das kutane Lyme-Spätstadium mit haarloser, atropher Haut an den Extremitätenstreckseiten heißt ","BLANK","."], a:["Acrodermatitis chronica atrophicans"]},
    {s:4, parts:["Bei den ANCA-Vaskulitiden erkennt cANCA typischerweise die ","BLANK",", pANCA typischerweise die ","BLANK","."], a:["Proteinase 3","Myeloperoxidase"]},
    {s:4, parts:["Die klassische (Meltzer-)Trias der kryoglobulinämischen Vaskulitis lautet Purpura, ","BLANK"," und Fatigue/Schwäche."], a:["Arthralgien"]}
  ];
  const match = [
    {s:4, t:"HAE-Medikament ↔ Wirkmechanismus", p:[["Berinert / Cinryze","C1-Esterase-Inhibitor-Substitution"],["Icatibant","Bradykinin-B2-Rezeptor-Antagonist"],["Ecallantide","Kallikrein-Inhibitor"],["Lanadelumab","Kallikrein-Antikörper"],["Danazol","attenuiertes Androgen"]]},
    {s:4, t:"Figuriertes Erythem ↔ Assoziation", p:[["Nekrolytisches migratorisches Erythem","Glukagonom"],["Erythema gyratum repens","Bronchialkarzinom"],["Erythema marginatum","Rheumatisches Fieber"],["Erythema chronicum migrans","Borrelia burgdorferi"],["Erythema anulare centrifugum","Tinea pedis"]]},
    {s:4, t:"Vaskulitis ↔ Gefäßkaliber (Chapel Hill)", p:[["Kutane leukozytoklastische Vaskulitis","kleine Gefäße"],["IgA-Vaskulitis","kleine Gefäße"],["Polyarteriitis nodosa","mittelgroße Arterien"],["Riesenzellarteriitis","große Arterien"],["Takayasu-Arteriitis","Aorta / große Arterien"]]}
  ];
  const freetext = [
    {s:4, q:"Erläutern Sie den Stufentherapie-Algorithmus der chronischen spontanen Urtikaria.", a:"Grundlage ist ein nicht-sedierendes H1-Antihistaminikum der 2. Generation in Standarddosierung (Stufe 1). Bei unzureichendem Ansprechen wird die Dosis bis auf das 4-Fache gesteigert (Stufe 2). Persistieren die Symptome, wird Omalizumab (Anti-IgE) als Add-on eingesetzt (Stufe 3); bei Versagen folgt Ciclosporin A (Stufe 4). Begleitend werden Mastzellstimulatoren gemieden (NSAR, Codein/Morphin), Trigger eliminiert und Assoziationen (v.a. Autoimmunthyreoiditis) abgeklärt. Bei ASS-/NSAR-Intoleranz kann off-label ein Leukotrien-Antagonist (Montelukast) ergänzt werden. Kurzfristige systemische Steroidstöße sind nur zur Kupierung schwerer Schübe, nicht als Dauertherapie sinnvoll."},
    {s:4, q:"Beschreiben Sie Pathomechanismus, klinische Warnzeichen und Therapie der toxischen epidermalen Nekrolyse (TEN).", a:"Pathomechanismus: In genetisch prädisponierten Individuen (u.a. HLA-B*15:02, HLA-B*58:01, HLA-A*31:01) löst das Medikament eine T-Zell-vermittelte, überwiegend CD8-getragene zytotoxische Reaktion aus. Medikamentenspezifische CD8+-T-Zellen sowie NK-/NKT-Zellen setzen Perforin/Granzym B, den Fas/FasL-Weg und v.a. Granulysin frei, was zu ausgedehnter Keratinozytenapoptose/-nekroptose führt. Warnzeichen/Klinik: 7-28 Tage nach Beginn der culprit-Medikation Prodromi mit Fieber, brennenden Augen und Schluckbeschwerden; danach schmerzhafte erythematös-livide Maculae, positives Nikolski-Zeichen, großflächige Epidermolyse (TEN >30% KOF) und obligate mukosale Beteiligung. Red Flags sind Hautschmerz, gräuliches Kolorit, Blasen/Epidermolyse und Schleimhauterosionen. Prognose per SCORTEN. Therapie: sofortiges Absetzen des Auslösers, intensivmedizinische supportive Therapie (Flüssigkeit, Elektrolyte, Wundmanagement, Temperatur, Infekt-/Thromboseprophylaxe, Refeeding beachten). Spezifisch IVIG 3-5 g/kg oder Ciclosporin 3-5 mg/kg (blockiert die Keratinozytenapoptose), sofern kein Malignom/Infekt vorliegt."},
    {s:4, q:"Grenzen Sie die drei ANCA-assoziierten Vaskulitiden (GPA, MPA, EGPA) klinisch, serologisch und histologisch voneinander ab.", a:"Alle drei sind pauci-immune Kleingefäßvaskulitiden. GPA (ehem. Wegener): granulomatöse Entzündung des oberen und unteren Respirationstrakts plus nekrotisierende Vaskulitis und pauci-immune Glomerulonephritis; typisch HNO-Befall (Sattelnase, Epistaxis, subglottische Stenose), Erdbeer-Gingivitis; serologisch cANCA/Anti-PR3 (~90%); Histologie mit Granulomen. MPA: nekrotisierende Vaskulitis OHNE Granulome; führend rasch progrediente Glomerulonephritis (~99%) und alveoläre Hämorrhagie; serologisch überwiegend pANCA/Anti-MPO; überlappt klinisch mit GPA. EGPA (ehem. Churg-Strauss): drei Phasen mit allergischer Rhinitis/Asthma, Bluteosinophilie/eosinophiler Organinfiltration und schließlich granulomatöser Vaskulitis; kardiale Beteiligung ist Hauptletalitätsgrund; nur ~40% ANCA-positiv (meist pANCA/MPO). Therapie aller: Remissionsinduktion mit Steroiden plus Cyclophosphamid oder Rituximab, bei EGPA zusätzlich Mepolizumab (Anti-IL-5)."}
  ];
  const img = [
    {s:4, cap:"Druckschmerzhafte Knoten an den Schienbeinen", q:"Welcher Pannikulitis-Typ liegt vor und wie heilen die Läsionen typischerweise ab?", o:["Septale Pannikulitis, narben- und ulzerationsfreie Abheilung","Lobuläre Pannikulitis mit Ulzeration und Vernarbung","Vaskulitische Pannikulitis mit retiformer Nekrose","Kalzifizierende Pannikulitis mit Verkalkung"], c:0, e:"Das Erythema nodosum ist eine septale Pannikulitis ohne Vaskulitis; die prätibialen, druckdolenten Knoten heilen kontusiform (blau-grün-gelb) und stets narben-/ulzerationsfrei ab.", svg:`<svg viewBox="0 0 280 240" xmlns="http://www.w3.org/2000/svg"><rect x="0" y="0" width="280" height="240" fill="#F4EFE8"/><path d="M70,24 L96,24 L92,208 L74,208 Z" fill="#f2d7c2" stroke="#9ca3af" stroke-width="2"/><path d="M176,24 L202,24 L198,208 L180,208 Z" fill="#f2d7c2" stroke="#9ca3af" stroke-width="2"/><path d="M74,208 L92,208 L98,228 L58,228 Z" fill="#f2d7c2" stroke="#9ca3af" stroke-width="2"/><path d="M180,208 L198,208 L204,228 L164,228 Z" fill="#f2d7c2" stroke="#9ca3af" stroke-width="2"/><g fill="#b43a2e" opacity="0.82"><ellipse cx="83" cy="92" rx="9" ry="7"/><ellipse cx="85" cy="122" rx="10" ry="8"/><ellipse cx="80" cy="152" rx="8" ry="7"/><ellipse cx="188" cy="100" rx="9" ry="7"/><ellipse cx="186" cy="134" rx="10" ry="8"/><ellipse cx="190" cy="166" rx="8" ry="6"/></g><text x="18" y="18" font-size="11" fill="#374151" font-family="sans-serif">prätibiale, druckdolente Knoten</text></svg>`},
    {s:4, cap:"Verzweigte, sternförmige Hautläsion mit zentraler Schwärzung", q:"Diese verzweigte (retiforme) Purpura mit zentraler Nekrose weist primär auf welchen Mechanismus hin?", o:["Oberflächliche Gefäßverletzung","Gefäßokklusion/Thrombose","Einfache Stase","Aktinische Hautschädigung"], c:1, e:"Die retiforme (astförmig-verzweigte) Purpura mit Nekrose entsteht durch Gefäßokklusion (Thrombose, Embolie, Proteinausfällung) oder okklusive Vaskulitis; die Purpura fulminans ist die ausgedehnte, lebensbedrohliche Variante.", svg:`<svg viewBox="0 0 260 220" xmlns="http://www.w3.org/2000/svg"><rect x="0" y="0" width="260" height="220" fill="#f2d7c2"/><g stroke="#6b1f4d" stroke-width="5" fill="none" stroke-linecap="round" opacity="0.85"><path d="M130,108 L92,70"/><path d="M130,108 L176,72"/><path d="M130,108 L86,150"/><path d="M130,108 L180,150"/><path d="M92,70 L70,46"/><path d="M92,70 L102,42"/><path d="M176,72 L202,56"/><path d="M176,72 L170,44"/><path d="M86,150 L60,170"/><path d="M86,150 L96,186"/><path d="M180,150 L206,166"/><path d="M180,150 L172,188"/></g><ellipse cx="130" cy="108" rx="23" ry="18" fill="#1b1a18"/><text x="14" y="206" font-size="11" fill="#374151" font-family="sans-serif">zentrale Nekrose, verzweigte (retiforme) Purpura</text></svg>`},
    {s:4, cap:"Schema der Gefäßkaliber (Chapel-Hill-Klassifikation)", q:"Welche Vaskulitis betrifft klassischerweise die markierten mittelgroßen Arterien?", o:["IgA-Vaskulitis","Polyarteriitis nodosa","Takayasu-Arteriitis","Kutane leukozytoklastische Vaskulitis"], c:1, e:"Die Polyarteriitis nodosa ist die prototypische Vaskulitis mittelgroßer (und kleiner) Arterien. IgA-Vaskulitis und kutane leukozytoklastische Vaskulitis betreffen kleine Gefäße, Takayasu die Aorta/großen Arterien.", svg:`<svg viewBox="0 0 300 200" xmlns="http://www.w3.org/2000/svg"><rect x="0" y="0" width="300" height="200" fill="#F4EFE8"/><circle cx="60" cy="96" r="42" fill="#f6d9cb" stroke="#9ca3af" stroke-width="3"/><circle cx="60" cy="96" r="22" fill="#F4EFE8" stroke="#9ca3af" stroke-width="2"/><text x="34" y="164" font-size="12" fill="#374151" font-family="sans-serif">groß</text><circle cx="162" cy="96" r="27" fill="#f2b39c" stroke="#b43a2e" stroke-width="4"/><circle cx="162" cy="96" r="12" fill="#F4EFE8" stroke="#b43a2e" stroke-width="2"/><text x="118" y="164" font-size="12" fill="#b43a2e" font-family="sans-serif">mittelgroß</text><circle cx="248" cy="96" r="13" fill="#f6d9cb" stroke="#9ca3af" stroke-width="2"/><circle cx="248" cy="96" r="5" fill="#F4EFE8"/><text x="228" y="164" font-size="12" fill="#374151" font-family="sans-serif">klein</text></svg>`}
  ];

  FLASH.push(...flash);
  MC.push(...mc);
  TF.push(...tf);
  CLOZE.push(...cloze);
  MATCH.push(...match);
  FREETEXT.push(...freetext);
  IMG.push(...img);
})();
