/* Dermaapp – Sektion 13: Erkrankungen durch physikalische Einwirkungen / Disorders Due to Physical Agents. Auto-generiert aus Facharzt-Unterlagen. */
(function () {
  const flash = [
    {s:13, q:"Nach welchem Kriterium werden thermische Verbrennungen (Combustio) klassisch eingeteilt und wie viele Grade unterscheidet man?", a:"Nach der Eindringtiefe: Grad 1 (Epidermis), Grad 2a (oberflächlich dermal), Grad 2b (tief dermal), Grad 3 (gesamte Dermis/Vollhaut), Grad 4 (bis Muskel/Sehne/Knochen). Grad 2a und 2b sind initial schwer zu unterscheiden, oft Aggravation im Verlauf ('Nachbrennen')."},
    {s:13, q:"Wie unterscheiden sich Grad-2a- und Grad-2b-Verbrennung klinisch und prognostisch?", a:"2a (oberflächlich dermal): rosa, feucht, Blasen, gute Rekapillarisierung, stark schmerzhaft, Heilung in ca. 7-21 Tagen ohne Narbe. 2b (tief dermal): blasser, verminderte Schmerzempfindung und Rekapillarisierung, verzögerte Heilung mit Narbe, ab 2b chirurgisches Débridement und Spalthauttransplantat."},
    {s:13, q:"Warum ist eine Verbrennung 3. Grades typischerweise schmerzlos?", a:"Bei der Vollhautverbrennung (Grad 3) sind auch die dermalen Nervenendigungen zerstört, daher besteht Analgesie im Zentrum. Klinik: lederartige, wachsartig-trockene, weiss-braun-schwarze Haut ohne Rekapillarisierung; keine Spontanheilung."},
    {s:13, q:"Wie wird die verbrannte Körperoberfläche (BSA) abgeschätzt und welche Faustregel gilt für kleine Areale?", a:"Erwachsene: Neuner-Regel nach Wallace (Kopf 9%, Arm je 9%, Bein je 18%, Rumpf je 18% vorne/hinten, Genitale 1%). Handfläche des Patienten inkl. Finger ca. 1% BSA. Bei Kindern ist die Lund-Browder-Chart genauer (grösserer Kopfanteil)."},
    {s:13, q:"Ab welcher verbrannten Körperoberfläche wird beim Erwachsenen eine Hospitalisation nötig und was droht bei schwerer Verbrennung?", a:"Ab ca. > 10% BSA Hospitalisation. Schwere Verbrennung (> 25% Adult, > 20% Kind): über Zytokinsturm und vasoaktive Substanzen droht ein hypovolämer (Verbrennungs-)Schock (Capillary Leak)."},
    {s:13, q:"Welche pathophysiologischen Vorgänge laufen bei einer thermischen Verletzung ab?", a:"Denaturierung und Koagulation zellulärer Proteine; interstitielles Ödem durch veränderten osmotischen Druck und erhöhte Kapillarpermeabilität; Freisetzung vasoaktiver/gewebeschädigender Mediatoren: Prostaglandine, Bradykinin, Serotonin, Histamin, Lipidperoxide und Sauerstoffradikale."},
    {s:13, q:"Wie wird eine Grad-2a-Verbrennung konservativ behandelt?", a:"Okklusivverbände (z.B. silberhaltige Schaumverbände wie Mepilex Ag, Hydrokolloid- oder Hyaluronsäure-Verbände) mit Wechsel alle 5-10 Tage, oder täglicher Wechsel mit topischem Antibiotikum (z.B. Mupirocin) und Gaze bis zur Re-Epithelialisierung. Ab Grad 2b: Débridement + Spalthaut."},
    {s:13, q:"Was ist ein Erythema ab igne und wodurch entsteht es?", a:"Retikuläre, erythematöse und im Verlauf hyperpigmentierte, nicht wegdrückbare Makulae durch chronische Hitze-/Infrarotexposition unterhalb der Verbrennungsschwelle. Typische Lokalisationen: lumbosakral (Wärmekissen/Wärmflasche) oder Oberschenkel-Streckseite ('Laptop-Dermatitis')."},
    {s:13, q:"Welches Risiko besteht bei langjährig persistierendem Erythema ab igne und was ist die wichtigste DD?", a:"Erhöhtes Risiko für ein Plattenepithelkarzinom (SCC) bei Persistenz (histologisch Plattenepithel-Atypien); Therapie mit topischem 5-Fluorouracil bei atypischen Keratinozyten. Wichtigste DD: Livedo reticularis, Cutis marmorata, Poikilodermie. Wärmequelle meiden."},
    {s:13, q:"Welche drei Komponenten liegen der Gewebeschädigung bei Erfrierungen (Congelatio) zugrunde?", a:"Kombination aus (1) direkter Gewebsgefrierung mit Eiskristallbildung, (2) vaskulärer Insuffizienz (Vasokonstriktion und Gefässverschluss/Thrombose) und (3) Schädigung durch entzündliche Mediatoren bei Reperfusion."},
    {s:13, q:"Wie werden Erfrierungen in vier Grade eingeteilt?", a:"Grad 1: Erythem, Ödem, Anästhesie, vollständige Heilung. Grad 2: Hyperämie, Ödem, klare Blasen; oft bleibende Sensibilitätsstörung/Kälteempfindlichkeit. Grad 3: hämorrhagische Blasen oder wachsig-mumifizierte Haut, Dermisverlust. Grad 4: Vollnekrose mit Muskel/Sehne/Knochen, meist Amputation."},
    {s:13, q:"Wie werden Erfrierungen therapiert und welche Rolle spielt Iloprost?", a:"Schnelles Wiedererwärmen im Wasserbad bei 37-39 °C (schmerzhaft, unter Analgesie), Vermeidung erneuter Kälte. Iloprost i.v. ist Erstlinientherapie bei Grad 3-4 (ab ca. 48 h nach Auftauen, Vasodilatation/Reperfusion)."},
    {s:13, q:"Warum darf gefrorenes Gewebe nicht gerieben werden und wann wird amputiert?", a:"Reiben verursacht durch Eiskristalle zusätzlichen mechanischen Gewebeschaden. Amputation nur bei Sepsis oder erst nach vollständiger Demarkation der Nekrose, die 1-3 Monate dauern kann ('frostbite in January, amputate in July')."},
    {s:13, q:"Was sind Perniones (Frostbeulen/Chilblains) und wann treten sie auf?", a:"Abnorme, entzündliche Gefässreaktion auf Kälte- und Feuchtigkeitsexposition (nicht Gefriertemperaturen). Beginn meist ca. 12-24 h nach Exposition, Abheilung in 1-3 Wochen. Klinik: schmerzhafte/juckende erythematös-livide Makulae, Papeln, Plaques an Akren (Finger, Zehen, Nase, Ohren)."},
    {s:13, q:"Wie unterscheidet man primäre von sekundären Perniones und welche Ursachen sind wichtig?", a:"Primär: idiopathisch, häufiger, meist im Winter, ohne Grunderkrankung. Sekundär: Autoimmun/Kollagenosen (Chilblain-Lupus, Antiphospholipidsyndrom), hämatologisch (Kryoglobulinämie, Kryofibrinogenämie) oder Infektionen ('COVID-Zehen'). Primäre Pernio ist Ausschlussdiagnose."},
    {s:13, q:"Wie werden Perniones therapiert?", a:"Kälte-/Feuchtigkeitsschutz (warme Kleidung, Rauchstopp), symptomatisch topische Steroide; bei Bedarf der Kalziumantagonist Nifedipin bis 3x20 mg/Tag p.o. (Vasodilatation). Sekundäre Formen: Grunderkrankung abklären/behandeln."},
    {s:13, q:"Was ist die Kältepannikulitis (Popsicle Panniculitis) und wer ist typischerweise betroffen?", a:"Kälteinduzierte Nekrose/Entzündung des subkutanen Fettgewebes, das bei Säuglingen/Kleinkindern mehr gesättigte Fettsäuren enthält und leichter erstarrt. Klassisch: gerötete, indurierte Plaques an Wange/Kinn nach Lutschen eines Eis am Stiel, Rückbildung über Wochen."},
    {s:13, q:"Wie unterscheiden sich Livedo reticularis und Livedo racemosa?", a:"Livedo reticularis: regelmässiges, geschlossenes, netzartiges livides Muster, oft physiologisch/kältebedingt (Cutis marmorata), reversibel. Livedo racemosa: unregelmässig, blitzfigurenartig, offene/unterbrochene Ringe, persistierend und pathologisch (Sneddon-Syndrom, Antiphospholipidsyndrom, Vaskulitis)."},
    {s:13, q:"Was ist die Cutis marmorata?", a:"Physiologische, reversible, netzartige bläulich-livide Marmorierung der Haut als vasomotorische Reaktion auf Kälte, v.a. bei Säuglingen und jungen Frauen; verschwindet bei Erwärmung. Abzugrenzen von der persistierenden Cutis marmorata teleangiectatica congenita."},
    {s:13, q:"Wie wird die UV-Strahlung nach Wellenlänge eingeteilt und welcher Anteil erreicht die Erde?", a:"UVC 200-290 nm (durch Ozon absorbiert), UVB 290-320 nm, UVA 320-400 nm. Über 95% der die Erde erreichenden UV-Strahlung ist UVA; UVA durchdringt im Gegensatz zu UVB auch Fensterglas."},
    {s:13, q:"Was ist die Hauptwirkung der UVB-Strahlung und welche Zielstruktur betrifft sie?", a:"UVB verursacht die direkte DNA-Schädigung mit Bildung von Pyrimidin-Dimeren (Cyclobutan-Dimere). Zielstruktur sind die Keratinozyten der Epidermis. Folgen: Sonnenbrand (Dermatitis solaris) und heller Hautkrebs (NMSC). DNA-Schäden werden repariert; gelingt das nicht, droht Karzinogenese."},
    {s:13, q:"Was ist die Hauptwirkung der UVA-Strahlung und welche Zielstruktur betrifft sie?", a:"UVA verursacht indirekte DNA-Schädigung über reaktive Sauerstoffspezies (ROS). Zielstruktur ist die Dermis (Fibroblasten, Kollagen, Elastin). Folge: Photoaging mit Faltenbildung und Elastose durch Kollagenabbau. UVA benötigt höhere Dosen; seine DNA-Schäden werden schlecht repariert."},
    {s:13, q:"Wie unterscheiden sich Sofort- und Spätbräune?", a:"Sofortbräune (immediate pigment darkening): via UVA innerhalb Minuten bis Stunden durch Oxidation/Umverteilung vorhandenen Melanins, KEINE Schutzwirkung. Spätbräune: via UVB nach Tagen durch Neusynthese von Melanin, echter Schutzmechanismus. Solarien (primär UVA) bieten daher keinen protektiven Effekt."},
    {s:13, q:"Was sind 'sunburn cells' und welche Strahlung verursacht sie hauptsächlich?", a:"Sunburn cells sind apoptotische, dyskeratotische Keratinozyten mit pyknotischem Kern und eosinophilem Zytoplasma, histologisch nach Sonnenbrand nachweisbar. Sie entstehen v.a. durch UVB, wenn die DNA-Schädigung die Reparaturkapazität überschreitet."},
    {s:13, q:"Was ist die minimale Erythemdosis (MED)?", a:"Die kleinste UV-Dosis, die gerade noch ein sichtbares, scharf begrenztes Erythem erzeugt. Sie wird in der Lichttreppe bestimmt, dient als Startdosis für das Light Hardening und erlaubt die Verlaufskontrolle der Photosensitivität."},
    {s:13, q:"Welche kutanen Zeichen sprechen für chronische UV-Schädigung (Photoaging)?", a:"Solare Elastose mit gelblicher, lederartig verdickter, gefurchter Haut, im Nacken als Cutis rhomboidalis nuchae; senile/aktinische (Bateman-)Purpura; Hautatrophie; Teleangiektasien und Lentigines. Neben Photoaging auch Photokarzinogenese."},
    {s:13, q:"Was ist das Favre-Racouchot-Syndrom?", a:"Noduläre solare Elastose mit multiplen offenen Komedonen und Pseudozysten periorbital/temporal, insbesondere bei älteren, sonnenexponierten Männern und Rauchern (Elastosis cutanea nodularis cystica et comedonica)."},
    {s:13, q:"Was ist die Bateman-Purpura (Purpura senilis/actinica)?", a:"Aktinisch/altersbedingte Purpura durch Fragilität der dermalen Gefässe bei solarer Elastose und Bindegewebsatrophie; scharf begrenzte, düster-rote Ekchymosen an Unterarmen/Handrücken nach Bagatelltrauma. Risikofaktor: topische oder systemische Steroide."},
    {s:13, q:"Was ist die polymorphe Lichtdermatose (PLD/PMLE) und welcher Trigger dominiert?", a:"Häufigste Photodermatose; immunvermittelte, verzögerte Hypersensitivitätsreaktion auf ein unbekanntes, photoinduziertes endogenes Antigen. Trigger meist UVA (ca. 75-90%) > UVB. Junge Frauen, Hauttyp I-II. Klinik: Stunden nach erster intensiver Sonnenexposition juckende Papeln/Papulovesikel, fleckig verteilt in lichtexponierten Arealen."},
    {s:13, q:"Was versteht man unter 'Light Hardening' bei der PLD und was ist die juvenile Frühlingseruption?", a:"Light Hardening: durch repetitive, langsam gesteigerte UV-Exposition (natürlich oder UVB-nb) nimmt die PLD im Saisonverlauf ab ('Abhärtung'). Juvenile spring eruption: klinische PLD-Subvariante mit Papulovesikeln an den Ohrhelices, v.a. bei Jungen im Frühjahr."},
    {s:13, q:"Was kennzeichnet die aktinische Prurigo?", a:"Persistierende Variante der PLD mit genetischer Prädisposition (HLA-DR4/DRB1*0407), v.a. bei indigener Bevölkerung Amerikas. Erstmanifestation im Kindesalter mit chronischem, im Sommer aggraviertem Verlauf; erythematöse, lichenifizierte, krustös belegte Papulonoduli, oft mit aktinischer Cheilitis und Konjunktivitis. Refraktär: Thalidomid."},
    {s:13, q:"Was ist die Hydroa vacciniforme und womit ist sie assoziiert?", a:"Sehr seltene Photodermatose (Trigger UVA), assoziiert mit latenter EBV-Infektion. Erstmanifestation im Kindesalter (m>f), meist selbstlimitierend in der Adoleszenz. Klinik: juckend-schmerzhafte Papulovesikel/Bullae mit zentraler Nabelung und hämorrhagischen Krusten, vernarbende (varioliforme) Abheilung. CAVE: HV-like LPD kann in EBV-positives T-/NK-Zell-Lymphom übergehen."},
    {s:13, q:"Was ist die solare Urtikaria und wie schnell tritt sie auf?", a:"Physikalische Urtikaria durch IgE-vermittelte Reaktion gegen ein photoinduziertes körpereigenes Antigen. Trigger UVA > UVB > sichtbares Licht. 5-10 Minuten nach Exposition juckende Urticae an sonnenexponierten Arealen, innerhalb 24 h flüchtig; schwer: Schwindel, Übelkeit, Bronchospasmus, Synkope. Therapie: Antihistaminika, Light Hardening, Omalizumab."},
    {s:13, q:"Was kennzeichnet die chronische aktinische Dermatitis (CAD)?", a:"Kontaktallergie-ähnliche, verzögerte Typ-IV-Reaktion gegen durch Licht induzierte endogene Hautantigene. Ältere Männer > 50 J, Trigger UVB > UVA. Chronische, scharf auf lichtexponierte Haut begrenzte, lichenifizierte ekzematöse Plaques, im Verlauf pseudolymphomatös. Umfasst Photosensitives Ekzem und Aktinisches Retikuloid. DD: kutanes T-Zell-Lymphom."},
    {s:13, q:"Wodurch unterscheidet sich eine phototoxische von einer photoallergischen Reaktion grundsätzlich?", a:"Phototoxisch: keine vorherige Sensibilisierung nötig, dosisabhängig, tritt schon beim Erstkontakt auf (Minuten-Stunden), sonnenbrandartig, direkte zytotoxische Zellschädigung, häufig. Photoallergisch: Sensibilisierung nötig, dosisunabhängig, verzögerte Typ-IV-Reaktion, ekzematös mit Streuherden, seltener."},
    {s:13, q:"Nennen Sie typische Auslöser phototoxischer Reaktionen.", a:"Systemisch: Tetrazykline, Fluorchinolone, NSAR, Amiodaron (mit Hyperpigmentierung), Hydrochlorothiazid, Vemurafenib (BRAF-Inhibitor), Retinoide, Psoralene, Johanniskraut. Topisch/exogen: Furocoumarine, Teerpräparate, 5-FU. Charakteristisch: Photoonycholyse (Tetrazykline, Psoralene, Taxane) und Pseudoporphyrie (NSAR, v.a. Naproxen)."},
    {s:13, q:"Wie wird eine photoallergische Reaktion diagnostiziert?", a:"Photopatch-Test ('belichtete Epikutantestung'): Duplikatauftrag der Allergene, eine Seite wird mit UVA (ca. 5 J/cm2) belichtet; eine nur belichtet auftretende Reaktion spricht für Photoallergie. Crescendo-Reaktion = allergisch, Decrescendo = irritativ. Bei systemischen Auslösern ggf. systemische Photoprovokation."},
    {s:13, q:"Was ist Xeroderma pigmentosum und welcher Defekt liegt zugrunde?", a:"Seltene autosomal-rezessive Genodermatose mit Defekt der Nukleotid-Exzisionsreparatur (NER), wodurch UV-induzierte Pyrimidin-Dimere nicht repariert werden. Folge: extreme Photosensitivität, frühe Poikilodermie, vielfache NMSC und Melanome im Kindesalter, häufig okuläre und neurologische Beteiligung. Konsequenter UV-Schutz essenziell."},
    {s:13, q:"Was ist die Phytophotodermatitis und welche Substanzklasse ist verantwortlich?", a:"Phototoxische Kontaktdermatitis nach Kontakt zu Furocoumarin-haltigen Pflanzen (Psoralene, Angelicine) plus UVA. Als Wiesengräserdermatitis (Dermatitis pratensis) mit streifig-bizarren Erythemen/Blasen und postinflammatorischer Hyperpigmentierung. Quellen: Riesenbärenklau, Sellerie, Pastinake, Limette, Bergamotte, Feige."},
    {s:13, q:"Wie unterscheidet sich die akute von der chronischen Radiodermatitis?", a:"Akut (Wochen nach Bestrahlung): Erythem, Ödem, trockene bis feuchte Desquamation, bei hohen Dosen Ulzeration. Chronisch (Monate-Jahre): Poikilodermie, Teleangiektasien, Fibrose/Sklerose, Atrophie, Pigmentstörungen, schlecht heilende Ulzera und erhöhtes Risiko für SCC/BCC in bestrahlter Haut."},
    {s:13, q:"Wie unterscheiden sich Clavus (Hühnerauge) und Callus (Schwiele)?", a:"Callus/Schwiele: diffuse, flächige Hyperkeratose ohne zentralen Kern durch chronische Reibung/Druck. Clavus/Hühnerauge: umschriebene Hyperkeratose mit zentralem, nach innen gerichtetem Hornkegel über Knochenvorsprüngen, druckschmerzhaft; Clavus durus (hart, dorsal) vs. Clavus mollis (weich, interdigital, mazeriert)."},
    {s:13, q:"Wie wird der Dekubitus (Druckulkus) stadieneingeteilt?", a:"Nach EPUAP/NPUAP: Grad 1 = nicht wegdrückbares Erythem intakter Haut; Grad 2 = Teilverlust der Haut (Blase/Erosion, bis Dermis); Grad 3 = Vollhautverlust bis subkutanes Fett; Grad 4 = Verlust mit freiliegendem Muskel/Sehne/Knochen. Prädilektion über Knochenvorsprüngen (Sakrum, Ferse, Trochanter)."},
    {s:13, q:"Welche Formen der Miliaria gibt es und wodurch entstehen sie?", a:"Durch Verschluss der ekkrinen Schweissdrüsengänge auf verschiedener Höhe: Miliaria crystallina (subkorneal, klare asymptomatische Bläschen), Miliaria rubra ('prickly heat', intraepidermal, juckende rote Papeln), Miliaria profunda (dermoepidermal, hautfarbene Papeln) und Miliaria pustulosa. Auslöser: Hitze, Okklusion, Schwitzen."},
    {s:13, q:"Was ist die Chondrodermatitis nodularis helicis (Winkler) und wie wird sie behandelt?", a:"Druck-/ischämie- und lichtbedingte schmerzhafte Entzündung von Haut und Ohrknorpel (Helix bei Männern, Anthelix bei Frauen), ältere Menschen. Klinik: schmerzhafte, hautfarben-erythematöse, kuppelförmige Papel mit zentraler Kruste/Krater. DD: BCC, SCC, aktinische Keratose. Therapie: Druckentlastung (Spezialkissen), sonst Kryotherapie, intraläsionale Steroide, Exzision."},
    {s:13, q:"Was ist eine chemische Verätzung durch Säure vs. Lauge und welche Rolle spielt Flusssäure?", a:"Säuren erzeugen eine Koagulationsnekrose, deren Schorf die Tiefenpenetration begrenzt. Laugen/Basen erzeugen eine Kolliquationsnekrose (verflüssigend, dringt tiefer, schwerer). Sofortmassnahme: ausgiebiges Spülen mit Wasser. Flusssäure (HF) dringt tief ein und bindet Kalzium/Magnesium (Hypokalzämie!); spezifisches Antidot ist Kalziumglukonat (topisch/intraläsional/i.a.)."}
  ];
  const mc = [
    {s:13, q:"Ein Patient zeigt nach einem Verbrühungsunfall eine lederartige, wachsartig-trockene, weisslich-braune und auffällig schmerzlose Läsion. Welcher Verbrennungsgrad liegt am ehesten vor?", o:["Grad 1","Grad 2a","Grad 2b","Grad 3"], c:3, e:"Lederartige, trockene, schmerzlose Haut ohne Rekapillarisierung spricht für eine Vollhautverbrennung (Grad 3) mit Zerstörung auch der Nervenendigungen."},
    {s:13, q:"Welche Aussage zur Grad-2a-Verbrennung trifft zu?", o:["Sie ist schmerzlos wegen Zerstörung der Nerven","Sie heilt typischerweise in ca. 7-21 Tagen ohne Narbe","Sie erfordert immer ein Spalthauttransplantat","Sie betrifft ausschliesslich die Epidermis"], c:1, e:"Die oberflächlich dermale Verbrennung (2a) ist stark schmerzhaft, rekapillarisiert gut und heilt in ca. 7-21 Tagen ohne Narbe. Grafting wird erst ab 2b nötig."},
    {s:13, q:"Etwa wie viel Prozent der Körperoberfläche entspricht die Handfläche des Patienten (inkl. Finger) bei der Abschätzung der Verbrennungsausdehnung?", o:["Ca. 1%","Ca. 5%","Ca. 9%","Ca. 18%"], c:0, e:"Die Handfläche des Patienten inklusive Finger entspricht etwa 1% der Körperoberfläche und dient der Abschätzung kleiner/verstreuter Areale."},
    {s:13, q:"Welche Mediatoren werden bei einer thermischen Verletzung typischerweise freigesetzt und tragen zum Ödem bei?", o:["Prostaglandine, Bradykinin, Histamin und Sauerstoffradikale","Ausschliesslich Immunglobulin E","Nur Komplementfaktor C1-Esterase","Kollagenase und Elastin"], c:0, e:"Freigesetzt werden vasoaktive/gewebeschädigende Mediatoren wie Prostaglandine, Bradykinin, Serotonin, Histamin, Lipidperoxide und Sauerstoffradikale; sie erhöhen die Kapillarpermeabilität."},
    {s:13, q:"Eine 30-jährige Frau zeigt an der linken Oberschenkel-Streckseite eine retikuläre, bräunliche Hyperpigmentierung. Sie arbeitet täglich stundenlang mit dem Laptop auf den Oberschenkeln. Welche Diagnose ist am wahrscheinlichsten?", o:["Livedo racemosa","Erythema ab igne","Erythema chronicum migrans","Necrobiosis lipoidica"], c:1, e:"Retikuläre Hyperpigmentierung durch chronische Wärme unterhalb der Verbrennungsschwelle ('Laptop-Dermatitis') ist typisch für ein Erythema ab igne."},
    {s:13, q:"Welches Langzeitrisiko besteht bei persistierendem Erythema ab igne?", o:["Malignes Melanom","Plattenepithelkarzinom","Basalzellkarzinom","Merkelzellkarzinom"], c:1, e:"Bei langjähriger Persistenz können sich Plattenepithel-Atypien und ein Plattenepithelkarzinom (SCC) entwickeln; Wärmequelle meiden, ggf. topisches 5-FU."},
    {s:13, q:"Was ist die Erstlinientherapie bei einer schweren Erfrierung Grad 3-4 (ca. 48 h nach Auftauen)?", o:["Iloprost i.v.","Sofortige Amputation","Systemische Glukokortikoide","Orales Isotretinoin"], c:0, e:"Iloprost i.v. ist Erstlinie bei Grad-3-4-Erfrierungen (Vasodilatation/Reperfusion). Amputation erst nach vollständiger Demarkation oder bei Sepsis."},
    {s:13, q:"Welche Massnahme ist bei der Erfrierung KONTRAINDIZIERT?", o:["Schnelles Wiedererwärmen im Wasserbad bei 37-39 °C","Reiben des gefrorenen Areals mit Schnee","Analgesie während der Erwärmung","Vermeidung erneuter Kälteexposition"], c:1, e:"Reiben verursacht durch Eiskristalle zusätzlichen Gewebeschaden und ist kontraindiziert. Korrekt ist rasches, kontrolliertes Wiedererwärmen bei 37-39 °C unter Analgesie."},
    {s:13, q:"Bei einer Patientin mit Perniones an den Zehen fallen zusätzlich Gelenkbeschwerden und eine positive ANA auf. An welche sekundäre Ursache ist zu denken?", o:["Lupus erythematodes (Chilblain-Lupus)","Psoriasis vulgaris","Rosazea","Lichen planus"], c:0, e:"Perniones mit Autoimmunmarkern sprechen für sekundäre Frostbeulen im Rahmen eines Lupus erythematodes (Chilblain-Lupus); auch Antiphospholipidsyndrom und Kryoglobulinämie sind mögliche Ursachen."},
    {s:13, q:"Welches Medikament wird bei therapiebedürftigen Perniones eingesetzt?", o:["Nifedipin","Propranolol","Doxycyclin","Metformin"], c:0, e:"Der Kalziumantagonist Nifedipin (bis 3x20 mg/Tag) wirkt vasodilatatorisch und wird bei Perniones eingesetzt; Basis ist der Kälte-/Feuchtigkeitsschutz."},
    {s:13, q:"Ein Kleinkind entwickelt einige Tage nach dem Lutschen eines Eis am Stiel eine indurierte, gerötete Plaque an der Wange. Welche Diagnose passt am besten?", o:["Kältepannikulitis","Erysipel","Kontaktdermatitis","Angioödem"], c:0, e:"Die Kältepannikulitis (Popsicle Panniculitis) entsteht durch Kälteschädigung des an gesättigten Fettsäuren reichen Säuglings-/Kleinkindfetts, klassisch an der Wange nach Eiskontakt."},
    {s:13, q:"Eine persistierende, unregelmässige, blitzfigurenartige Livedo racemosa sollte am ehesten an welche Assoziation denken lassen?", o:["Physiologische Kältereaktion","Sneddon-Syndrom bzw. Antiphospholipidsyndrom","Erythema ab igne","Miliaria rubra"], c:1, e:"Die Livedo racemosa ist im Gegensatz zur reversiblen Livedo reticularis pathologisch und mit Sneddon-Syndrom, Antiphospholipidsyndrom oder Vaskulitis assoziiert."},
    {s:13, q:"In welchem Wellenlängenbereich liegt die UVA-Strahlung?", o:["100-200 nm","200-290 nm","290-320 nm","320-400 nm"], c:3, e:"UVA umfasst 320-400 nm, UVB 290-320 nm, UVC 200-290 nm (durch Ozon absorbiert). UVA macht über 95% der die Erde erreichenden UV-Strahlung aus."},
    {s:13, q:"Welcher Mechanismus beschreibt die Hauptwirkung der UVB-Strahlung?", o:["Direkte DNA-Schädigung mit Pyrimidin-Dimeren in Keratinozyten","Indirekte Schädigung über ROS in Fibroblasten","Vasodilatation durch Histaminfreisetzung","IgE-vermittelte Mastzelldegranulation"], c:0, e:"UVB verursacht die direkte DNA-Schädigung mit Pyrimidin-Dimeren in Keratinozyten der Epidermis und führt zu Sonnenbrand und NMSC."},
    {s:13, q:"Welche Aussage zur UVA-Strahlung ist korrekt?", o:["Sie verursacht Photoaging über reaktive Sauerstoffspezies in der Dermis","Sie wird vollständig von der Ozonschicht absorbiert","Sie kann Fensterglas nicht durchdringen","Sie erzeugt die schützende Spätbräune"], c:0, e:"UVA schädigt indirekt über ROS die Dermis (Fibroblasten, Kollagen, Elastin) und verursacht Photoaging; es durchdringt Glas und erzeugt die nicht-protektive Sofortbräune."},
    {s:13, q:"Warum bietet die durch Solarien induzierte Bräune (primär UVA) keinen Sonnenschutz?", o:["Weil sie auf Neusynthese von Melanin beruht","Weil sie nur auf Oxidation vorhandenen Melanins beruht (Sofortbräune)","Weil sie die Hornschicht verdickt","Weil sie die DNA-Reparatur aktiviert"], c:1, e:"Die UVA-vermittelte Sofortbräune beruht auf Oxidation/Umverteilung bereits vorhandenen Melanins ohne Neusynthese und hat daher keine Schutzwirkung, anders als die UVB-Spätbräune."},
    {s:13, q:"Eine 28-jährige Frau (Hauttyp II) entwickelt jeden Frühling wenige Stunden nach der ersten intensiven Sonne juckende Papeln und Papulovesikel an Dekolleté und Armen, die im Sommerverlauf abnehmen. Welche Diagnose ist am wahrscheinlichsten?", o:["Polymorphe Lichtdermatose","Chronische aktinische Dermatitis","Xeroderma pigmentosum","Porphyria cutanea tarda"], c:0, e:"Junge Frau, Frühjahrsbeginn nach erster Sonne, juckende polymorphe Effloreszenzen mit 'Light Hardening' im Verlauf: typische polymorphe Lichtdermatose (Trigger meist UVA)."},
    {s:13, q:"Welche Behandlung ist bei therapierefraktärer aktinischer Prurigo klassisch beschrieben?", o:["Thalidomid","Isotretinoin","Terbinafin","Aciclovir"], c:0, e:"Bei therapierefraktärer aktinischer Prurigo ist Thalidomid (50-100 mg/d) klassisch etabliert; Basis sind Lichtschutz, topische Steroide und Photohardening."},
    {s:13, q:"Mit welchem Erreger ist die Hydroa vacciniforme assoziiert und welche Komplikation ist gefürchtet?", o:["Latente EBV-Infektion mit Risiko eines T-/NK-Zell-Lymphoms","Latente HSV-Infektion mit Risiko eines Ekzema herpeticatum","HPV mit Risiko eines Plattenepithelkarzinoms","HHV-8 mit Risiko eines Kaposi-Sarkoms"], c:0, e:"Die Hydroa vacciniforme ist mit latenter EBV-Infektion assoziiert; die HV-like lymphoproliferative Erkrankung kann in ein EBV-positives T-/NK-Zell-Lymphom übergehen."},
    {s:13, q:"Welche Aussage zur solaren Urtikaria trifft zu?", o:["Sie ist eine physikalische, IgE-vermittelte Urtikaria mit Auftreten binnen 5-10 Minuten","Sie ist eine verzögerte Typ-IV-Reaktion nach 24-48 Stunden","Sie hinterlässt regelhaft Narben","Sie tritt nur an nicht-lichtexponierter Haut auf"], c:0, e:"Die solare Urtikaria ist eine physikalische, IgE-vermittelte Urtikaria; Urticae erscheinen 5-10 Minuten nach Lichtexposition und sind innerhalb von 24 h flüchtig."},
    {s:13, q:"Welche Aussage charakterisiert eine phototoxische (im Gegensatz zur photoallergischen) Reaktion?", o:["Dosisabhängig und schon beim Erstkontakt ohne Sensibilisierung","Immer eine verzögerte Typ-IV-Reaktion","Dosisunabhängig nach vorheriger Sensibilisierung","Nachweis mittels Prick-Test"], c:0, e:"Phototoxische Reaktionen sind dosisabhängig und treten ohne vorherige Sensibilisierung bereits beim Erstkontakt auf; photoallergische Reaktionen sind dosisunabhängige Typ-IV-Reaktionen nach Sensibilisierung."},
    {s:13, q:"Welcher immunologische Mechanismus liegt der photoallergischen Reaktion zugrunde?", o:["Typ-I-Soforttyp (IgE)","Typ-II-zytotoxisch","Typ-III-Immunkomplex","Typ-IV-Spättyp (T-Zell-vermittelt)"], c:3, e:"Die Photoallergie ist eine T-Zell-vermittelte, verzögerte Typ-IV-Hypersensitivitätsreaktion: UV wandelt das Agens in ein Hapten um, das zum Vollantigen wird."},
    {s:13, q:"Welches Medikament ist ein typischer Auslöser einer phototoxischen Reaktion mit begleitender Hyperpigmentierung an UV-exponierten Arealen?", o:["Amiodaron","Paracetamol","Amoxicillin","Ranitidin"], c:0, e:"Amiodaron verursacht phototoxische Reaktionen und typische schiefergraue Hyperpigmentierungen an UV-exponierten Arealen; weitere klassische Auslöser sind Tetrazykline und Fluorchinolone."},
    {s:13, q:"Eine Pseudoporphyrie wird am häufigsten durch welche Substanzgruppe ausgelöst?", o:["NSAR (v.a. Naproxen)","Betablocker","Protonenpumpenhemmer","Orale Kontrazeptiva"], c:0, e:"Die Pseudoporphyrie (PCT-ähnliche Blasen ohne Porphyrinstörung) wird häufig durch NSAR, insbesondere Naproxen, ausgelöst."},
    {s:13, q:"Welche Patientengruppe ist von der chronischen aktinischen Dermatitis typischerweise betroffen?", o:["Ältere Männer > 50 Jahre","Neugeborene","Junge Frauen im Wochenbett","Ausschliesslich Kinder < 5 Jahre"], c:0, e:"Die chronische aktinische Dermatitis betrifft typischerweise ältere Männer (> 50 J), Trigger UVB > UVA; sie kann klinisch einem kutanen T-Zell-Lymphom ähneln."},
    {s:13, q:"Welcher molekulare Defekt liegt dem Xeroderma pigmentosum zugrunde?", o:["Defekt der Nukleotid-Exzisionsreparatur (NER)","Defekt des Kollagen Typ VII","Defekt der Uroporphyrinogen-Decarboxylase","Defekt des Filaggrin-Gens"], c:0, e:"Xeroderma pigmentosum beruht auf einem autosomal-rezessiven Defekt der Nukleotid-Exzisionsreparatur, sodass UV-induzierte Pyrimidin-Dimere nicht repariert werden; Folge sind früh multiple Hauttumoren."},
    {s:13, q:"Welche Pflanze bzw. Substanz löst klassisch eine Phytophotodermatitis aus?", o:["Furocoumarin-haltige Pflanzen wie Riesenbärenklau oder Limette","Brennnessel (Urtica dioica)","Efeu-Kontaktallergen","Latexproteine"], c:0, e:"Die Phytophotodermatitis ist eine phototoxische Reaktion auf Furocoumarine (Psoralene) in Pflanzen wie Riesenbärenklau, Sellerie, Pastinake, Limette oder Bergamotte plus UVA."},
    {s:13, q:"Ein Badegast wird von einer Qualle genesselt. Welche Erstmassnahme ist am ehesten korrekt?", o:["Spülen mit Süsswasser und kräftiges Abreiben","Spülen mit Meerwasser/Essig und Entfernen anhaftender Tentakel ohne Reiben","Sofortiges Auftragen von Kortikoidsalbe unter Okklusion","Abdecken mit einem trockenen Verband ohne weitere Massnahme"], c:1, e:"Süsswasser und Reiben lösen weitere Nematozysten aus. Korrekt: mit Meerwasser (bei bestimmten Arten Essig) spülen, anhaftende Tentakel vorsichtig entfernen; für manche Arten heisses Wasser."},
    {s:13, q:"Warum ist eine Verätzung durch Laugen (Basen) tendenziell gefährlicher als durch Säuren?", o:["Laugen erzeugen eine oberflächliche Koagulationsnekrose","Laugen erzeugen eine Kolliquationsnekrose und dringen tiefer ein","Säuren verflüssigen das Gewebe stärker","Säuren binden Kalzium und verursachen Hypokalzämie"], c:1, e:"Basen erzeugen eine verflüssigende Kolliquationsnekrose und dringen dadurch tiefer ein, während Säuren eine Koagulationsnekrose bilden, deren Schorf die Penetration begrenzt."},
    {s:13, q:"Welches spezifische Antidot wird bei einer Flusssäure(HF)-Verätzung eingesetzt?", o:["Kalziumglukonat","Natriumbicarbonat oral","Dimercaprol","Physostigmin"], c:0, e:"Flusssäure bindet Kalzium/Magnesium und kann eine Hypokalzämie verursachen; spezifisches Antidot ist Kalziumglukonat (topisch als Gel, intraläsional oder intraarteriell)."},
    {s:13, q:"Ein älterer Mann klagt über eine sehr druckschmerzhafte, kuppelförmige Papel mit zentraler Kruste am oberen Rand der Ohrhelix, die ihn nachts beim Liegen auf dieser Seite weckt. Welche Diagnose ist am wahrscheinlichsten?", o:["Chondrodermatitis nodularis helicis","Basalzellkarzinom","Gichttophus","Keloid"], c:0, e:"Schmerzhafte Papel mit zentraler Kruste an der Helix eines älteren Mannes mit Druck-/Lagerungsbezug spricht für die Chondrodermatitis nodularis helicis; wichtigste DD sind BCC/SCC/aktinische Keratose. Therapie: Druckentlastung."},
    {s:13, q:"Ein Waldarbeiter, der seit Jahren täglich mit der Kettensäge arbeitet, berichtet über anfallsweise weisse, taube Finger bei Kälte. Welche berufsbedingte Erkrankung ist am wahrscheinlichsten?", o:["Hand-Arm-Vibrationssyndrom (sekundäres Raynaud)","Erythromelalgie","Physiologische Akrozyanose","Erythema ab igne"], c:0, e:"Chronische Vibrationsexposition (Kettensäge, Presslufthammer) führt zum Hand-Arm-Vibrationssyndrom mit vibrationsbedingtem sekundärem Raynaud-Phänomen ('vibration white finger'), oft mit zusätzlicher neurologischer und muskuloskelettaler Komponente."}
  ];
  const tf = [
    {s:13, st:"Eine Verbrennung 3. Grades ist im Zentrum typischerweise schmerzlos, weil auch die Nervenendigungen zerstört sind.", c:true, e:"Korrekt - bei der Vollhautverbrennung sind die dermalen Nervenendigungen zerstört, daher besteht zentrale Analgesie."},
    {s:13, st:"UVA-Strahlung dringt tiefer in die Haut ein als UVB und kann auch Fensterglas durchdringen.", c:true, e:"Korrekt - UVA (320-400 nm) erreicht die Dermis und durchdringt Glas, während UVB grösstenteils in der Epidermis absorbiert wird."},
    {s:13, st:"Die UVA-vermittelte Sofortbräune bietet einen wirksamen Schutz vor weiteren UV-Schäden.", c:false, e:"Falsch - die Sofortbräune beruht nur auf Oxidation vorhandenen Melanins ohne Neusynthese und hat keine Schutzwirkung. Schutz bietet erst die UVB-Spätbräune."},
    {s:13, st:"UVB verursacht die direkte DNA-Schädigung mit Bildung von Pyrimidin-Dimeren.", c:true, e:"Korrekt - UVB schädigt die DNA direkt unter Bildung von Cyclobutan-Pyrimidin-Dimeren, v.a. in Keratinozyten."},
    {s:13, st:"Bei einer Erfrierung soll das betroffene Areal zur schnelleren Erwärmung kräftig mit Schnee gerieben werden.", c:false, e:"Falsch - Reiben verursacht durch Eiskristalle zusätzlichen Gewebeschaden. Korrekt ist rasches Wiedererwärmen im Wasserbad bei 37-39 °C unter Analgesie."},
    {s:13, st:"Iloprost i.v. ist Erstlinientherapie bei schweren Erfrierungen Grad 3-4.", c:true, e:"Korrekt - Iloprost wird ab ca. 48 h nach Auftauen bei Grad-3-4-Erfrierungen zur Verbesserung der Mikrozirkulation eingesetzt."},
    {s:13, st:"Perniones (Frostbeulen) sind immer Ausdruck einer zugrundeliegenden Autoimmunerkrankung.", c:false, e:"Falsch - die primäre (idiopathische) Form ist häufiger. Sekundäre Formen (Lupus, Antiphospholipidsyndrom, Kryoglobulinämie, COVID-Zehen) müssen aber ausgeschlossen werden."},
    {s:13, st:"Eine phototoxische Reaktion erfordert eine vorherige Sensibilisierung des Patienten.", c:false, e:"Falsch - phototoxische Reaktionen sind dosisabhängig und treten ohne Sensibilisierung bereits beim Erstkontakt auf. Eine Sensibilisierung braucht die photoallergische Reaktion."},
    {s:13, st:"Die photoallergische Reaktion ist eine T-Zell-vermittelte, verzögerte Typ-IV-Hypersensitivitätsreaktion.", c:true, e:"Korrekt - UV wandelt das Agens in ein Hapten um; nach Bildung des Vollantigens erfolgt eine T-Zell-vermittelte Typ-IV-Reaktion."},
    {s:13, st:"Bei der polymorphen Lichtdermatose ist regelhaft das gesamte UV-exponierte Integument betroffen.", c:false, e:"Falsch - typisch ist eine fleckige Verteilung; nicht das gesamte lichtexponierte Areal ist betroffen, oft mit Aussparung des Gesichts (Gewöhnung)."},
    {s:13, st:"Die solare Urtikaria zählt zu den physikalischen Urtikariaformen.", c:true, e:"Korrekt - die solare Urtikaria ist eine physikalische, IgE-vermittelte Urtikaria mit Auftreten binnen Minuten nach Lichtexposition."},
    {s:13, st:"Die Hydroa vacciniforme ist mit einer latenten EBV-Infektion assoziiert.", c:true, e:"Korrekt - die Assoziation mit latenter EBV-Infektion ist etabliert; die HV-like Form kann in ein EBV-positives Lymphom übergehen."},
    {s:13, st:"Das Erythema ab igne ist stets harmlos und ohne jedes Malignitätsrisiko.", c:false, e:"Falsch - bei langjähriger Persistenz können Plattenepithel-Atypien und ein SCC entstehen; die Wärmequelle ist zu meiden."},
    {s:13, st:"Xeroderma pigmentosum wird autosomal-dominant vererbt.", c:false, e:"Falsch - Xeroderma pigmentosum wird autosomal-rezessiv vererbt und beruht auf einem Defekt der Nukleotid-Exzisionsreparatur."},
    {s:13, st:"Der Dekubitus entsteht bevorzugt über Knochenvorsprüngen wie Sakrum, Ferse und Trochanter.", c:true, e:"Korrekt - über Knochenvorsprüngen ist der Auflagedruck am höchsten, dort entstehen Druckulzera bevorzugt."},
    {s:13, st:"Die Miliaria crystallina ist die am tiefsten reichende Form der Miliaria.", c:false, e:"Falsch - die Miliaria crystallina ist die oberflächlichste Form (subkornealer Verschluss); tiefer liegen Miliaria rubra und Miliaria profunda."},
    {s:13, st:"Nach Quallenkontakt sollte die Haut mit reichlich Süsswasser gespült werden.", c:false, e:"Falsch - Süsswasser löst durch osmotische Reize weitere Nematozysten aus. Man spült mit Meerwasser bzw. bei bestimmten Arten mit Essig."},
    {s:13, st:"Ein Clavus (Hühnerauge) besitzt im Gegensatz zur Schwiele einen zentralen, nach innen gerichteten Hornkegel.", c:true, e:"Korrekt - der Clavus zeigt einen umschriebenen zentralen Hornkegel, während der Callus/die Schwiele eine diffuse, flächige Hyperkeratose ohne Kern ist."}
  ];
  const cloze = [
    {s:13, parts:["UVB umfasst den Wellenlängenbereich ","BLANK"," nm, UVA den Bereich ","BLANK"," nm."], a:["290-320","320-400"]},
    {s:13, parts:["Histologisch nach Sonnenbrand nachweisbare apoptotische Keratinozyten heissen ","BLANK"," cells und entstehen vorwiegend durch ","BLANK","-Strahlung."], a:["sunburn","UVB"]},
    {s:13, parts:["Die polymorphe Lichtdermatose wird überwiegend durch ","BLANK","-Strahlung ausgelöst; die saisonale Besserung durch repetitive Exposition heisst ","BLANK","."], a:["UVA","Light Hardening"]},
    {s:13, parts:["Die Erstbehandlung der Erfrierung besteht im schnellen Wiedererwärmen im Wasserbad bei ","BLANK"," °C."], a:["37-39"]},
    {s:13, parts:["Bei therapiebedürftigen Perniones wird der Kalziumantagonist ","BLANK"," eingesetzt."], a:["Nifedipin"]},
    {s:13, parts:["Bei therapierefraktärer aktinischer Prurigo ist ","BLANK"," die klassische systemische Therapie."], a:["Thalidomid"]},
    {s:13, parts:["Die Hydroa vacciniforme ist mit einer latenten ","BLANK","-Infektion assoziiert."], a:["EBV"]},
    {s:13, parts:["Die kleinste UV-Dosis, die gerade noch ein sichtbares Erythem erzeugt, heisst minimale ","BLANK","."], a:["Erythemdosis"]},
    {s:13, parts:["Die Phytophotodermatitis ist eine phototoxische Reaktion auf ","BLANK","-haltige Pflanzen plus UVA-Licht."], a:["Furocoumarin"]},
    {s:13, parts:["Flusssäure bindet ","BLANK"," im Gewebe; spezifisches Antidot ist ","BLANK","."], a:["Kalzium","Kalziumglukonat"]},
    {s:13, parts:["Eine Verbrennung Grad ","BLANK"," heilt typischerweise ohne Narbe innerhalb von ca. 7-21 Tagen."], a:["2a"]},
    {s:13, parts:["Die solare Urtikaria tritt bereits ","BLANK"," Minuten nach Lichtexposition auf und ist innerhalb von 24 h flüchtig."], a:["5-10"]}
  ];
  const match = [
    {s:13, t:"Verbrennungsgrad ↔ Merkmal", p:[["Grad 1","Erythem, Epidermis, Heilung ca. 7 Tage"],["Grad 2a","Blasen, feucht, schmerzhaft, Heilung ohne Narbe"],["Grad 2b","Blasser, verminderte Schmerzempfindung, Narbe"],["Grad 3","Lederartig, schmerzlos, keine Spontanheilung"]]},
    {s:13, t:"UV-Typ ↔ Wirkung / Zielstruktur", p:[["UVB","Direkte DNA-Schäden, Pyrimidin-Dimere, Keratinozyten"],["UVA","ROS, Dermis, Photoaging, durchdringt Glas"],["UVC","200-290 nm, durch Ozon absorbiert"],["Sichtbares Licht","Trigger u.a. der solaren Urtikaria"]]},
    {s:13, t:"Photodermatose ↔ Schlüsselmerkmal", p:[["Polymorphe Lichtdermatose","Junge Frauen, fleckig, Light Hardening"],["Aktinische Prurigo","HLA-DR4, aktinische Cheilitis, Thalidomid"],["Hydroa vacciniforme","EBV, vernarbende Vesikel mit Nabelung"],["Solare Urtikaria","IgE-vermittelt, Urticae binnen Minuten"],["Chronische aktinische Dermatitis","Ältere Männer, chronisch ekzematös"]]},
    {s:13, t:"Auslöser ↔ typische Photoreaktion", p:[["Amiodaron","Phototoxizität mit Hyperpigmentierung"],["Naproxen (NSAR)","Pseudoporphyrie"],["Tetrazykline","Phototoxizität, Photoonycholyse"],["Riesenbärenklau","Phytophotodermatitis"],["Topika (z.B. Duftstoffe)","Photoallergische Reaktion"]]},
    {s:13, t:"Kälteschaden ↔ Merkmal", p:[["Erfrierung Grad 4","Vollnekrose bis Knochen, meist Amputation"],["Perniones","Akren, Kälte+Feuchte, Nifedipin"],["Kältepannikulitis","Kleinkind, Wange, Eis am Stiel"],["Livedo racemosa","Persistierend, Sneddon/Antiphospholipidsyndrom"]]},
    {s:13, t:"Mechanisch/physikalische Läsion ↔ Ursache / Ort", p:[["Chondrodermatitis nodularis helicis","Druck/Ischämie am Ohrknorpel"],["Aurikuläres Hämatom (Cauliflower Ear)","Wiederholtes Ohrtrauma, Perichondriumablösung"],["Clavus","Zentraler Hornkegel über Knochenvorsprung"],["Dekubitus","Anhaltender Auflagedruck über Knochenvorsprung"],["Miliaria rubra","Verschluss ekkriner Schweissdrüsengänge"]]}
  ];
  const freetext = [
    {s:13, q:"Erläutern Sie die Gradeinteilung thermischer Verbrennungen sowie die Grundzüge von Schweregradabschätzung und Erstversorgung.", a:"Die Einteilung erfolgt nach Eindringtiefe. Grad 1 betrifft nur die Epidermis (Erythem, schmerzhaft, Heilung ca. 7 Tage, keine Narbe). Grad 2a (oberflächlich dermal) zeigt Blasen, ist feucht/rosa, rekapillarisiert gut, ist stark schmerzhaft und heilt in ca. 7-21 Tagen ohne Narbe. Grad 2b (tief dermal) ist blasser, mit verminderter Schmerzempfindung und Rekapillarisierung, heilt verzögert mit Narbe. Grad 3 (Vollhaut) ist lederartig, trocken, weiss-braun-schwarz und schmerzlos (Nervenzerstörung), ohne Spontanheilung. Grad 4 reicht bis Muskel/Sehne/Knochen. 2a und 2b sind initial schwer zu trennen, oft Aggravation im Verlauf. Schweregrad: Ausdehnung über die Neuner-Regel (Wallace), Handfläche des Patienten ca. 1% BSA; bei Kindern ist die Lund-Browder-Chart genauer. Ab ca. > 10% BSA Hospitalisation; schwere Verbrennungen können über Zytokinsturm zum hypovolämen Schock führen. Erstversorgung: Kühlung, Analgesie, Volumensubstitution; Grad 1 und 2a konservativ mit Okklusiv-/Silberverbänden bzw. topischem Antibiotikum bis zur Re-Epithelialisierung; ab Grad 2b chirurgisches Débridement der Nekrose und Spalthauttransplantat."},
    {s:13, q:"Vergleichen Sie UVA- und UVB-Strahlung hinsichtlich Wellenlänge, Wirkmechanismus, Zielstruktur und klinischer Konsequenz.", a:"UVB (290-320 nm) wird überwiegend in der Epidermis absorbiert und verursacht die direkte DNA-Schädigung mit Bildung von Pyrimidin-Dimeren in Keratinozyten. Klinisch führt UVB zu Sonnenbrand (Dermatitis solaris), zur schützenden Spätbräune durch Melanin-Neusynthese und zu hellem Hautkrebs (NMSC); die Induktion von DNA-Schäden ist obligat, wird aber meist repariert, sonst droht Karzinogenese. UVA (320-400 nm) macht über 95% der die Erde erreichenden UV-Strahlung aus, dringt tiefer in die Dermis ein und durchdringt Fensterglas. Es schädigt die DNA indirekt über reaktive Sauerstoffspezies und trifft Fibroblasten, Kollagen und Elastin; Folge ist v.a. Photoaging (Falten, solare Elastose) durch Kollagenabbau sowie die nicht-protektive Sofortbräune durch Oxidation vorhandenen Melanins. UVA benötigt höhere Dosen; seine DNA-Schäden werden schlechter repariert. Für die kutane Karzinogenese ist v.a. UVB, für die Hautalterung v.a. UVA verantwortlich. Sunburn cells (apoptotische Keratinozyten) entstehen überwiegend durch UVB."},
    {s:13, q:"Grenzen Sie phototoxische und photoallergische Reaktion hinsichtlich Pathogenese, Klinik, Auslösern und Diagnostik voneinander ab.", a:"Phototoxische Reaktion: Der Photosensibilisator wird durch UV (meist UVA) in einen angeregten Zustand versetzt und gibt die Energie an Sauerstoff/Nachbarmoleküle ab, es entstehen ROS und toxische Produkte mit direkter zytotoxischer Zellschädigung. Sie ist dosisabhängig, benötigt keine Sensibilisierung und tritt schon beim Erstkontakt binnen Minuten bis Stunden auf, klinisch als überschiessender Sonnenbrand mit Erythem, Ödem, Brennen, ggf. Blasen und postinflammatorischer Hyperpigmentierung, nur auf lichtexponierte Areale begrenzt. Auslöser meist systemische Medikamente: Tetrazykline, Fluorchinolone, NSAR, Amiodaron, Vemurafenib, Psoralene, Johanniskraut; charakteristisch sind Photoonycholyse und Pseudoporphyrie. Photoallergische Reaktion: UV wandelt das Agens chemisch in ein Hapten um, das kovalent an Protein bindet und zum Vollantigen wird; nach Antigenpräsentation resultiert eine T-Zell-vermittelte, verzögerte Typ-IV-Reaktion. Sie ist dosisunabhängig, benötigt eine vorherige Sensibilisierung, ist seltener und klinisch ekzematös mit Streuherden bis zur Generalisierung, Auslöser meist Topika (Duftstoffe, UV-Filter, Antiseptika). Diagnostik: Photopatch-Test (belichtete Epikutantestung mit UVA ca. 5 J/cm2), ggf. systemische Photoprovokation; Crescendo-Reaktion spricht für Allergie, Decrescendo für Irritation. Therapie beider: Auslöser meiden/absetzen, konsequenter Lichtschutz, topische oder systemische Kortikosteroide."},
    {s:13, q:"Schildern Sie Pathophysiologie, Gradeinteilung und Therapieprinzipien der Erfrierung (Congelatio).", a:"Pathophysiologie: Die Schädigung entsteht durch direkte Gewebsgefrierung mit Eiskristallbildung, vaskuläre Insuffizienz (Vasokonstriktion, Gefässverschluss/Thrombose) und einen entzündlichen Reperfusionsschaden. Gradeinteilung: Grad 1 mit Erythem, Ödem, Anästhesie und vollständiger Heilung; Grad 2 mit Hyperämie, Ödem und klaren Blasen, oft mit bleibender Sensibilitätsstörung/Kälteempfindlichkeit; Grad 3 mit hämorrhagischen Blasen oder wachsig-mumifizierter Haut und Dermisverlust; Grad 4 mit Vollnekrose unter Beteiligung von Muskel, Sehne und Knochen, meist Amputation. Therapie: schnelles Wiedererwärmen im Wasserbad bei 37-39 °C unter Analgesie (schmerzhaft), Vermeidung erneuter Kälte und keinesfalls Reiben (zusätzlicher Eiskristallschaden). Bei Grad 3-4 ist Iloprost i.v. Erstlinientherapie (ab ca. 48 h nach Auftauen). Eine Amputation erfolgt nur bei Sepsis oder erst nach vollständiger Demarkation der Nekrose, die 1-3 Monate dauern kann; das definitive chirurgische Vorgehen wird daher zeitlich hinausgezögert."}
  ];
  const img = [
    {s:13, cap:"Schematischer Hautquerschnitt mit Eindringtiefe verschiedener Verbrennungsgrade", q:"Der rechte Pfeil (III) reicht durch die gesamte Dermis bis in die Subkutis. Welche klinische Eigenschaft ist für diese Verbrennungstiefe typisch?", o:["Stark schmerzhaft mit rascher Rekapillarisierung","Schmerzlos und ohne Spontanheilung","Nur Rötung ohne Blasen, Heilung in 7 Tagen","Ausschliesslich Epidermisbeteiligung"], c:1, e:"Der Pfeil III markiert eine Vollhautverbrennung (Grad 3): lederartig, schmerzlos durch Zerstörung der Nervenendigungen und ohne Spontanheilung, daher Débridement und Spalthaut nötig.", svg:`<svg viewBox="0 0 320 240" xmlns="http://www.w3.org/2000/svg"><rect x="18" y="34" width="220" height="24" fill="#f7d9b8" stroke="#9ca3af" stroke-width="1.5"/><rect x="18" y="58" width="220" height="44" fill="#f6c6c0" stroke="#9ca3af" stroke-width="1.5"/><rect x="18" y="102" width="220" height="44" fill="#ef9f97" stroke="#9ca3af" stroke-width="1.5"/><rect x="18" y="146" width="220" height="40" fill="#fde9a9" stroke="#9ca3af" stroke-width="1.5"/><text x="22" y="50" font-size="10" fill="#374151" font-family="sans-serif">Epidermis</text><text x="22" y="84" font-size="10" fill="#374151" font-family="sans-serif">Dermis (papillär)</text><text x="22" y="128" font-size="10" fill="#374151" font-family="sans-serif">Dermis (retikulär)</text><text x="22" y="170" font-size="10" fill="#374151" font-family="sans-serif">Subkutis</text><g stroke-width="3" fill="none"><line x1="250" y1="30" x2="250" y2="56" stroke="#f59e0b"/><line x1="272" y1="30" x2="272" y2="98" stroke="#ea9b3c"/><line x1="292" y1="30" x2="292" y2="142" stroke="#c2410c"/><line x1="310" y1="30" x2="310" y2="182" stroke="#7f1d1d"/></g><g font-size="9" fill="#374151" font-family="sans-serif"><text x="244" y="26">I</text><text x="264" y="26">IIa</text><text x="284" y="26">IIb</text><text x="305" y="26">III</text></g></svg>`},
    {s:13, cap:"Eindringtiefe von UVB und UVA in die Haut", q:"Welche Strahlung entspricht dem tiefer bis in die Dermis reichenden Pfeil und ist hauptverantwortlich für das Photoaging?", o:["UVB","UVA","UVC","Infrarot"], c:1, e:"Der tiefere Pfeil ist UVA (320-400 nm): Es erreicht die Dermis, schädigt über ROS Fibroblasten und Kollagen und verursacht Photoaging. UVB bleibt oberflächlicher (Epidermis) und macht v.a. Sonnenbrand und DNA-Dimere.", svg:`<svg viewBox="0 0 300 240" xmlns="http://www.w3.org/2000/svg"><rect x="20" y="60" width="260" height="30" fill="#f7d9b8" stroke="#9ca3af" stroke-width="1.5"/><rect x="20" y="90" width="260" height="90" fill="#f6c6c0" stroke="#9ca3af" stroke-width="1.5"/><rect x="20" y="180" width="260" height="40" fill="#fde9a9" stroke="#9ca3af" stroke-width="1.5"/><text x="24" y="79" font-size="10" fill="#374151" font-family="sans-serif">Epidermis (Keratinozyten)</text><text x="24" y="140" font-size="10" fill="#374151" font-family="sans-serif">Dermis (Fibroblasten, Kollagen)</text><text x="24" y="204" font-size="10" fill="#374151" font-family="sans-serif">Subkutis</text><g stroke-width="3"><line x1="110" y1="20" x2="110" y2="86" stroke="#2563eb"/><polygon points="110,92 105,80 115,80" fill="#2563eb"/><line x1="190" y1="20" x2="190" y2="150" stroke="#7c3aed"/><polygon points="190,156 185,144 195,144" fill="#7c3aed"/></g><g font-size="11" font-family="sans-serif"><text x="96" y="16" fill="#2563eb">UVB</text><text x="176" y="16" fill="#7c3aed">UVA</text></g></svg>`},
    {s:13, cap:"Retikuläres Hautmuster am Unterschenkel", q:"Ein Patient zeigt nach monatelangem Gebrauch einer Wärmflasche dieses nicht wegdrückbare, retikulär-hyperpigmentierte Muster. Welche Diagnose und welches Risiko sind zu bedenken?", o:["Erythema ab igne - Risiko eines Plattenepithelkarzinoms","Erythema migrans - Risiko einer Neuroborreliose","Miliaria rubra - Risiko einer Superinfektion","Vitiligo - Risiko einer Autoimmunthyreoiditis"], c:0, e:"Ein retikuläres, nicht wegdrückbares, hyperpigmentiertes Muster nach chronischer Wärmeexposition ist ein Erythema ab igne; bei Persistenz besteht ein Risiko für ein Plattenepithelkarzinom (SCC).", svg:`<svg viewBox="0 0 220 300" xmlns="http://www.w3.org/2000/svg"><path d="M70,20 C66,80 60,150 74,230 C78,260 82,278 96,290 L120,290 C110,270 108,250 110,230 C118,150 120,80 116,20 Z" fill="#f4d3c0" stroke="#9ca3af" stroke-width="2"/><g stroke="#8a5a3b" stroke-width="2" fill="none" opacity="0.8"><path d="M74,60 L110,80"/><path d="M110,60 L74,84"/><path d="M74,96 L112,116"/><path d="M112,96 L74,120"/><path d="M76,132 L112,152"/><path d="M112,132 L76,156"/><path d="M78,168 L112,188"/><path d="M112,168 L78,192"/><path d="M82,204 L112,224"/><path d="M112,204 L82,228"/></g><text x="20" y="288" font-size="11" fill="#374151" font-family="sans-serif">retikuläres Muster</text></svg>`}
  ];

  FLASH.push(...flash);
  MC.push(...mc);
  TF.push(...tf);
  CLOZE.push(...cloze);
  MATCH.push(...match);
  FREETEXT.push(...freetext);
  IMG.push(...img);
})();
