/* Auto-extracted Dermaapp learning content */
const FLASH = [
  // Section 3
  {s:3, q:"Wichtigste genetische Region der Psoriasis vulgaris?", a:"PSORS1 auf Chromosom 6p21 (enthält HLA-Cw6). HLA-B27 zusätzlich axiale Psoriasisarthritis."},
  {s:3, q:"Definition PASI > 10?", a:"Schwere Psoriasis. Bewertet Erythem, Induration, Schuppung in 4 Körperregionen × % betroffener BSA."},
  {s:3, q:"Drei klassische klinische Zeichen der Psoriasis?", a:"1) Kerzenwachsphänomen 2) Phänomen des letzten Häutchens 3) Auspitz-Phänomen (blutiger Tau)."},
  {s:3, q:"Fünf Befunde der Psoriasis unguium?", a:"Pitting, distale Onycholyse, Leukonychie, Splinter-Hämorrhagien, lachsfarbener Ölfleck."},
  {s:3, q:"Welches Biologikum ist erste Wahl bei Psoriasis-Patientin mit Kinderwunsch?", a:"Certolizumab pegol (Cimzia) – pegyliert, daher nicht plazentagängig."},
  {s:3, q:"Welche Mutation bei Psoriasis Zumbusch & ILVEN?", a:"Loss-of-function im IL36RN-Gen (Zumbusch). CARD14-Gain-of-function (ILVEN, familiär)."},
  {s:3, q:"Drei Akne-fördernde Topika im Säuglingsalter mit NW?", a:"Povidon-Jod → Hypothyreose · Salicylsäure → metabol. Azidose · Prilocain (EMLA) → Methämoglobinämie."},
  {s:3, q:"Trias der reaktiven Arthritis?", a:"Urethritis · Arthritis · Konjunktivitis (can't see, can't pee, can't climb a tree). HLA-B27."},
  {s:3, q:"Pathogenese atopische Dermatitis (Schlüsselgen)?", a:"Filaggrin-LoF-Mutation → gestörte Hautbarriere. Th2-Antwort mit IL-4/IL-13/IL-31. S. aureus-Besiedlung."},
  {s:3, q:"Dupilumab Wirkmechanismus & Zulassung?", a:"Anti-IL-4Rα blockiert IL-4/IL-13. Atopische Dermatitis ab 6 Monaten."},
  {s:3, q:"Wickham-Streifung – wo, wodurch?", a:"Feine weißliche Streifung auf Lichen ruber-Papeln. Histologisch Hyperkeratose & Hypergranulose."},
  {s:3, q:"PLEVA vs PLC – wesentlicher Unterschied?", a:"PLEVA: akut, vesiculo-krustös, narbige Abheilung. PLC: chronisch, schuppend, Hypopigmentierung."},
  {s:3, q:"Acrodermatitis enteropathica – Trias?", a:"Pluriperiorifizielle Dermatitis · Diarrhoe · Alopezie. Zinkmangel (SLC39A4-Mutation)."},
  {s:3, q:"Bazex-Syndrom (Acrodermatitis paraneoplastica)?", a:"Palmoplantare honigwabenartige Hyperkeratosen + Paronychie. PEC-Karzinome im oberen Aerodigestivtrakt."},
  {s:3, q:"Phytophotodermatitis – Mechanismus?", a:"Furocoumarine (Limetten, Sellerie) + UVA → ROS und DNA-Bindung. Nicht-immunologisch."},
  // Section 4
  {s:4, q:"Urtikaria-Definition vs Angioödem?", a:"Urtikaria: oberflächliche Dermis, Quaddeln, juckend, < 24 h. Angioödem: tiefe Dermis/Subkutis, schmerzhaft, Tage."},
  {s:4, q:"Hereditäres Angioödem Typ I/II – Defekt?", a:"SERPING1-Mutation. C1-Esterase-Inhibitor vermindert (Typ I) oder dysfunktional (Typ II). C4 niedrig."},
  {s:4, q:"Akuttherapie HAE-Attacke?", a:"C1-INH-Konzentrat i.v. (Berinert), Icatibant s.c. (B2-Rez-Antagonist), Ecallantid (Kallikrein-Inh., USA)."},
  {s:4, q:"Erythema marginatum – Grunderkrankung?", a:"Rheumatisches Fieber nach β-hämolysierenden Streptokokken-A-Pharyngitis (Antigen-Mimikry)."},
  {s:4, q:"Erythema chronicum migrans – Therapie Erwachsene?", a:"Doxycyclin 2 × 100 mg p.o. für 10–14 Tage. Bei SS/Kindern < 8 J: Amoxicillin."},
  {s:4, q:"BSA-Definition SJS/SJS-TEN-Overlap/TEN?", a:"SJS < 10 %, Overlap 10–30 %, TEN > 30 % BSA Epidermolyse."},
  {s:4, q:"DRESS – charakteristisches Trio?", a:"Morbilliformes Exanthem mit Gesichtsödem · Eosinophilie · Organbeteiligung (Hepatitis, Nephritis). HHV-6-Reaktivierung."},
  {s:4, q:"AGEP – Onset und Klinik?", a:"< 4 Tage nach Medikament. Sterile <5 mm Pusteln auf Erythem, Gesicht & Intertrigines, Leukozytose, Abheilung 2 Wochen."},
  {s:4, q:"Antiphospholipidsyndrom – Akronym?", a:"CLOT: Coagulation · Livedo racemosa · Obstetrics (Aborte) · Thrombozytopenie."},
  {s:4, q:"Cryoglobulinämie – Klinik-Merkhilfe?", a:"SKIN: Skin (Livedo racemosa, Akrozyanose) · Kidney injury · Intraarticular inflammation · Nerve (PNP)."},
  {s:4, q:"Kawasaki – Hauptkomplikation?", a:"Koronararterienaneurysmen. Fieber > 5 Tage + 4/5 Kriterien. IVIG 2 g/kg + ASS hochdosiert."},
  {s:4, q:"Pyoderma gangraenosum – wichtigste Assoziationen?", a:"CIBD, RA, Plasmazelldyskrasie, hämatologische Malignome, PASH/PAPA-Syndrome."},
  {s:4, q:"Coombs/Gell Allergie-Typen I bis IV?", a:"I: IgE/Mastzellen (Anaphylaxie) · II: zytotoxisch (Pemphigus) · III: Immunkomplex (Vaskulitis, Serum) · IV: T-Zell (Kontaktdermatitis, AME)."},
  {s:4, q:"SCORTEN-Variablen?", a:"Alter > 40, Malignom, HF > 120, BSA > 10 %, Harnstoff > 10, HCO₃ < 20, Glukose > 14."},
  {s:4, q:"Schnitzler-Syndrom Major-Kriterien?", a:"Chronische Urtikaria + monoklonale IgM-Gammopathie. IL-1-vermittelt → Anakinra/Canakinumab."},
  // Section 5
  {s:5, q:"Pemphigus vulgaris – Antigen Mukosa vs Haut?", a:"Anti-Dsg3 → Mukosa. Anti-Dsg1 zusätzlich → kutane Manifestation. Suprabasale Akantholyse."},
  {s:5, q:"\"Row of tombstones\" – Erkrankung?", a:"Pemphigus vulgaris: basale Keratinozyten verbleiben grabsteinartig auf der Dermisseite nach suprabasaler Akantholyse."},
  {s:5, q:"BP – Hauptantigene?", a:"BP180 (Kollagen XVII, NC16A-Domäne, ~85 %) und BP230 (Plakin, ~15 %)."},
  {s:5, q:"Salt-split-skin Spaltebene?", a:"Lamina lucida. Antigene oberhalb (BP180/230) → Blasendach. Antigene unterhalb (Kollagen VII, Lam332) → Blasenboden."},
  {s:5, q:"Dermatitis herpetiformis Duhring – Auslöser & Therapie?", a:"Glutensensitive Enteropathie. Anti-TG3 (Haut), Anti-TG2 (Darm). Glutenfreie Diät + Dapson."},
  {s:5, q:"Dapson NW – die wichtigsten 4?", a:"Hämolytische Anämie (G6PD!), Methämoglobinämie, Agranulozytose, Dapson-Hypersensitivitätssyndrom."},
  {s:5, q:"LABD – Hauptantigen + häufigster Trigger?", a:"LAD-1 (Spaltprodukt von BP180, 97/120 kDa). Vancomycin ist klassischer Trigger beim Erwachsenen."},
  {s:5, q:"Paraneoplastischer Pemphigus – Antigene?", a:"Envoplakin & Periplakin > Dsg1/3, BP180/230, Desmoplakin, Plektin. IIF positiv auf Rattenblase."},
  {s:5, q:"Anti-Laminin-332-Pemphigoid – Tumorscreening?", a:"Kolonkarzinom & PEC im HNO-Bereich. Tumorsuche obligat bei Diagnose."},
  {s:5, q:"EBA – Antigen?", a:"Auto-IgG gegen Kollagen VII (Ankerfilamente in der Lamina densa)."},
  {s:5, q:"EB hereditaria Klassifikation – 4 Hauptgruppen?", a:"EB simplex (intraepidermal, KRT5/14) · Junktional (Lamina lucida, Lam332) · Dystroph (Sub-LD, COL7A1) · Kindler-Syndrom."},
  {s:5, q:"B-VEC (Vyjuvek) – Wirkprinzip?", a:"Topisch applizierter modifizierter HSV-1, der COL7A1-Gen in Keratinozyten transportiert. Seit 2023."},
  {s:5, q:"SSSS – Pathogenese?", a:"Staph. aureus Exfoliatin A/B → Spaltung Dsg1 → subkorneale Blase. Keine Schleimhaut (keine Dsg1-Expression)."},
  {s:5, q:"4×4-Regel SSSS?", a:"< 4 J alt · 4 Tage nach Infekt · 4 Hautareale · 4 Zeichen (Fieber, Erythem, Blasen, Nikolski+)."},
  {s:5, q:"Incontinentia pigmenti – 4 Stadien & Gen?", a:"Vesikulös → verrukös → hyperpigmentiert → hypopigmentiert. IKBKG-Gen (NEMO) X-chromosomal."},
  // Section 6
  {s:6, q:"Vier Hauptfaktoren der Akne-Pathogenese?", a:"Follikuläre Hyperkeratinisierung · Androgenstimulation der Talgdrüsen · Inflammation · Cutibacterium acnes."},
  {s:6, q:"Acne fulminans – typischer Patient & Trigger?", a:"13–16 J Junge mit Anabolika oder Testosteron. Isotretinoin kann triggern. SAPHO-Syndrom-DD."},
  {s:6, q:"Antikonzeption nach Acitretin – Dauer?", a:"3 Jahre! (Wegen Reesterification zu Etretinat im Fettgewebe.) Isotretinoin/Alitretinoin nur 1 Monat."},
  {s:6, q:"Rosacea-Topika erste Wahl?", a:"Ivermectin 1 % (Soolantra) bei Demodex · Azelainsäure 15 % · Metronidazol-Creme · Brimonidin (kurzfristig Vasokonstriktion)."},
  {s:6, q:"Periorale Dermatitis – wichtigster Trigger?", a:"Topische/inhalative Steroide. Therapie: Steroidstop, Schwarztee, Elidel, Oracea 40 mg."},
  {s:6, q:"Hidradenitis suppurativa Hurley III – Therapie?", a:"Adalimumab oder Secukinumab + chirurgische Sanierung (wide excision). HiSCR ≥ 50 % als Erfolgskriterium."},
  {s:6, q:"PASH-Syndrom?", a:"Pyoderma gangraenosum + Akne + HS. Autoinflammatorisch. Therapie: TNF-α-Inhibitoren, Anakinra."},
  {s:6, q:"Eosinophile pustulöse Follikulitis Ofuji – Therapie 1. Linie?", a:"Indomethacin (NSAR) 50 mg/Tag. Alternativ UVB, Minocyclin, Dapson."},
  {s:6, q:"Pseudofolliculitis barbae – kausale Therapie?", a:"Laser-Haarentfernung (eliminiert das gekrümmte Haarschaft-Problem)."},
  {s:6, q:"Fox-Fordyce Disease – Lokalisation und Trigger?", a:"Apokrine Drüsen-Okklusion. Stark juckende Follikel-Papeln axillär/anogenital/periareolär. Trigger Hitze, Stress; vorausgegangene Laser-Haarentfernung."},
  {s:6, q:"Frey-Syndrom?", a:"Gustatorisches Schwitzen nach N. auriculotemporalis-Verletzung (Parotis-OP). Botox als Therapie."},
  {s:6, q:"Iontophorese – Kontraindikationen?", a:"Schwangerschaft, Schrittmacher, metallisches IUP, PNP, Wunden, Epilepsie, Kinder < 6 J."}
];

const MC = [
  // Section 3
  {s:3, q:"Welche genetische Veränderung liegt der Pityriasis rubra pilaris (familiäre Form) zugrunde?",
    o:["NLRP3-Mutation","CARD14-Mutation","FLG-Loss-of-function","STAT3-Mutation"], c:1,
    e:"CARD14-GoF-Mutation, mit Überexpression von IL-17/IL-23. Auch ILVEN-assoziiert."},
  {s:3, q:"Welcher Subtyp der Psoriasis tritt typisch nach Streptokokken-Pharyngitis bei Kindern auf?",
    o:["Plaque-Psoriasis","Psoriasis pustulosa palmoplantaris","Psoriasis guttata","Psoriasis inversa"], c:2,
    e:"Psoriasis guttata: tropfenförmig, ASLO erhöht in >50 %, gutes Ansprechen auf UVBnb."},
  {s:3, q:"Welches Biologikum blockiert IL-17A UND IL-17F?",
    o:["Ixekizumab","Secukinumab","Bimekizumab","Brodalumab"], c:2,
    e:"Bimekizumab ist das einzige duale Anti-IL-17A/F. Brodalumab blockiert IL-17R."},
  {s:3, q:"Welcher Wirkstoff ist KEINE Erstlinientherapie der atopischen Dermatitis bei Erwachsenen?",
    o:["Topische Kortikosteroide","Tacrolimus 0,1 %","Methotrexat","Emollientien"], c:2,
    e:"MTX ist Reservepräparat. TCS, TCI, Emollientien sind First Line."},
  {s:3, q:"Welche Zellsubpopulation dominiert die akute Phase der atopischen Dermatitis?",
    o:["Th1","Th2","Th17","Treg"], c:1,
    e:"Akute Phase Th2 (IL-4/IL-13/IL-31), chronische Phase Th1-dominiert."},
  {s:3, q:"Welche Medikamentenklasse triggert eine paradoxe palmoplantare pustulöse Psoriasis?",
    o:["Tetracycline","TNF-α-Inhibitoren","Antihistaminika","SSRI"], c:1,
    e:"TNF-α-Inhibitoren können paradoxe pustulöse Reaktionen induzieren."},
  {s:3, q:"Welche Erkrankung gehört NICHT zu den figurierten Erythemen?",
    o:["Erythema annulare centrifugum","Erythema gyratum repens","Erythema chronicum migrans","Erythema nodosum"], c:3,
    e:"Erythema nodosum ist eine septale Pannikulitis, nicht figuriert."},
  {s:3, q:"Welches Allergen ist die häufigste Ursache einer beruflichen allergischen Kontaktdermatitis?",
    o:["Methylisothiazolinon","Nickel","Latex","Methanol"], c:1,
    e:"Nickel führt die Liste der häufigsten Kontaktallergene weltweit an."},
  {s:3, q:"Acrodermatitis enteropathica – betroffene Substanz?",
    o:["Eisen","Zink","Kupfer","Selen"], c:1,
    e:"Zinkmalabsorption durch SLC39A4-Mutation. Therapie: lebenslange Zinksubstitution."},
  {s:3, q:"Welche Erkrankung verursacht das 'Deck Chair Sign'?",
    o:["Pityriasis rubra pilaris","Papuloerythroderma Ofuji","Pemphigus foliaceus","Sézary-Syndrom"], c:1,
    e:"Papuloerythroderma Ofuji mit charakteristischer Aussparung der Hautfalten."},
  // Section 4
  {s:4, q:"Welcher Mediator ist beim hereditären Angioödem zentral?",
    o:["Histamin","Serotonin","Bradykinin","Tryptase"], c:2,
    e:"Bradykinin – daher kein Ansprechen auf Antihistaminika/Steroide. Therapie: C1-INH, Icatibant."},
  {s:4, q:"Welche Therapie ist erste Wahl bei refraktärer chronischer Urtikaria?",
    o:["Methotrexat","Omalizumab","Ciclosporin","Dapson"], c:1,
    e:"Stufe 3 EAACI-Leitlinie: Add-on Omalizumab (Anti-IgE)."},
  {s:4, q:"HLA-B*15:02 ist Risikofaktor für SJS/TEN unter welchem Medikament?",
    o:["Allopurinol","Carbamazepin","Lamotrigin","Phenytoin"], c:1,
    e:"Carbamazepin in Han-Chinesen. Allopurinol-SJS/TEN: HLA-B*58:01."},
  {s:4, q:"DRESS – häufigste virale Reaktivierung?",
    o:["EBV","CMV","HHV-6","HHV-8"], c:2,
    e:"HHV-6 ist klassisch reaktiviert (auch HHV-7, EBV, CMV)."},
  {s:4, q:"Was ist Erstwahl-Therapie der TEN ohne Malignom/Infekt?",
    o:["Hochdosis-Steroide","IVIG oder Ciclosporin","Cyclophosphamid","Plasmapherese"], c:1,
    e:"IVIG 3–5 g/kg blockiert Fas-FasL; Ciclosporin 3–5 mg/kg hemmt Keratinozytenapoptose."},
  {s:4, q:"Welcher Erreger verursacht das Erythema marginatum?",
    o:["Parvovirus B19","Streptokokken Gruppe A","Borrelia burgdorferi","Mycoplasma pneumoniae"], c:1,
    e:"β-hämolysierende Streptokokken Gr. A → rheumatisches Fieber."},
  {s:4, q:"Wie lange muss eine Zecke saugen, bevor Doxycyclin-Prophylaxe sinnvoll ist?",
    o:["> 6 h","> 12 h","> 24 h","> 36 h"], c:3,
    e:"Borrelien benötigen ~36 h, um aus dem Mitteldarm in die Speicheldrüse zu wandern."},
  {s:4, q:"Welche Vaskulitis ist die kindliche Form mit palpabler Purpura, Arthritis, GI-Beschwerden und Nephritis?",
    o:["Polyarteritis nodosa","IgA-Vaskulitis (Henoch-Schönlein)","Kawasaki","Granulomatose mit Polyangiitis"], c:1,
    e:"IgA-Vaskulitis: IgA1-Immunkomplexe. Tetrade: Purpura, Arthralgien, Abdomen, Nephritis."},
  {s:4, q:"Welches Antigen wird bei ANCA-positiver eosinophiler Granulomatose (Churg-Strauss) angegriffen?",
    o:["PR3","MPO","Beta2-Glykoprotein","C1q"], c:1,
    e:"pANCA gegen MPO bei EGPA und MPA. cANCA gegen PR3 bei GPA."},
  {s:4, q:"Welcher Wirkstoff ist bei Triple-positivem APS kontraindiziert?",
    o:["ASS","Vitamin-K-Antagonist","Rivaroxaban","Hydroxychloroquin"], c:2,
    e:"DOAKs (insb. Rivaroxaban) erhöhen das Thromboserisiko bei Triple-positivem APS."},
  // Section 5
  {s:5, q:"Welches Antigen ist beim Pemphigus foliaceus betroffen?",
    o:["Desmoglein 1","Desmoglein 3","Desmocollin 1","BP180"], c:0,
    e:"Anti-Dsg1: kutane Blasenbildung, keine Mukosa (da dort Dsg3-dominiert)."},
  {s:5, q:"Welche Ebene der Akantholyse beim Pemphigus vulgaris?",
    o:["Stratum corneum","Stratum granulosum","Suprabasal","Subepidermal"], c:2,
    e:"Suprabasal – 'row of tombstones'-Phänomen."},
  {s:5, q:"Auf welchem Substrat ist die IIF bei paraneoplastischem Pemphigus typisch positiv?",
    o:["Affenösophagus","Rattenblase","Salt-split-skin","Humanösophagus"], c:1,
    e:"Rattenblase ist hochspezifisch (Plakin-Antikörper)."},
  {s:5, q:"Welche Variable des Schleimhautpemphigoids erfordert obligates Tumorscreening?",
    o:["Anti-BP180","Anti-Laminin-332","Anti-BP230","Anti-Kollagen VII"], c:1,
    e:"Anti-Laminin-332-MMP: Assoziation mit Kolon-Ca und HNO-PEC."},
  {s:5, q:"Welches Medikament induziert klassisch eine lineare IgA-bullöse Dermatose?",
    o:["Penicillin","Vancomycin","Phenytoin","Allopurinol"], c:1,
    e:"Vancomycin ist klassischer Trigger; Klinik kann TEN-ähnlich sein."},
  {s:5, q:"Welche EB-Form hat das höchste SCC-Risiko?",
    o:["EB simplex","Junktionale EB","AR schwere dystrophe EB (Hallopeau-Siemens)","Kindler-Syndrom"], c:2,
    e:"AR DEB schwer (COL7A1-Mutation): aggressive SCCs auf chronischen Wunden."},
  {s:5, q:"Bei Bullosis diabeticorum ist die DIF typischerweise:",
    o:["Lineare IgG entlang DEJ","Granulare IgA in Papillenspitzen","Negativ","Interzelluläre IgG"], c:2,
    e:"Bullosis diabeticorum: subepidermale Blase, DIF negativ."},
  {s:5, q:"Welches Toxin spaltet beim SSSS Desmoglein 1?",
    o:["Toxic-Shock-Toxin-1","Exfoliatin A/B","Panton-Valentine-Leukozidin","Alpha-Toxin"], c:1,
    e:"Exotoxin A/B von Staph. aureus (~5 % aller Stämme)."},
  {s:5, q:"Welche Therapie ist erste Wahl bei DH Duhring?",
    o:["Glutenfreie Diät + Dapson","Methotrexat","Rituximab","Hochdosis-Steroide"], c:0,
    e:"Glutenfreie Diät + Dapson 25–200 mg/Tag (G6PD-Test vor Beginn!)."},
  {s:5, q:"Was ist die typische DIF-Konstellation bei DH?",
    o:["Lineare IgG entlang DEJ","Granuläre IgA in Papillenspitzen","Lineare IgA entlang DEJ","Interzelluläre IgG"], c:1,
    e:"Granuläre IgA-Ablagerungen in den dermalen Papillenspitzen."},
  // Section 6
  {s:6, q:"Welcher Akne-Subtyp gehört zur Akne-Tetrade?",
    o:["Acne mechanica","Acne tarda","Acne conglobata","Acne cosmetica"], c:2,
    e:"Acne conglobata + HS + Perifolliculitis capitis + Pilonidalsinus = Akne-Tetrade."},
  {s:6, q:"Welche Aknetherapie ist in der Schwangerschaft zugelassen?",
    o:["Isotretinoin","Adapalen","Azelainsäure","Doxycyclin"], c:2,
    e:"Azelainsäure ist sicher in SS. Retinoide & Tetracycline kontraindiziert."},
  {s:6, q:"Welcher Akne-Patient sollte endokrinologisch abgeklärt werden?",
    o:["12-jähriger Junge mit Komedonen","Frau, 28 J, mit perimenstrueller Aggravation und Hirsutismus","Acne mechanica eines Sportlers","Klassische Pubertätsakne"], c:1,
    e:"Acne tarda mit Hyperandrogenismus → PCOS, Late-onset CAH, Tumor."},
  {s:6, q:"Welcher Wirkstoff ist erste Wahl bei Demodex-betonter papulopustulöser Rosacea?",
    o:["Metronidazol","Brimonidin","Ivermectin 1 % Creme","Doxycyclin"], c:2,
    e:"Soolantra (Ivermectin) wirkt antiparasitär & antiinflammatorisch."},
  {s:6, q:"Welche Erkrankung manifestiert sich periorifiziell mit Aussparung der Lippen-Haut-Grenze und periorbital?",
    o:["Rosacea","Periorale Dermatitis","Akne","Demodikose"], c:1,
    e:"Periorale Dermatitis mit charakteristischer perioraler Blässe."},
  {s:6, q:"Welcher HiSCR-Wert gilt als Therapieerfolg bei HS?",
    o:["≥ 25 %","≥ 50 %","≥ 75 %","100 %"], c:1,
    e:"HiSCR ≥ 50 % Reduktion der Abszesse + entzündlichen Knoten ohne Zunahme der Fistelgänge."},
  {s:6, q:"Welche systemische Therapie ist seit 2023 für HS in-label zugelassen?",
    o:["Bimekizumab","Secukinumab","Apremilast","Upadacitinib"], c:1,
    e:"Secukinumab (Sunshine/Sunrise-Studie). Adalimumab seit längerem."},
  {s:6, q:"Welche Erkrankung ist KEINE Indikation für Isotretinoin?",
    o:["Acne fulminans","Schwere noduläre Akne","Acne keloidalis nuchae","Psoriasis vulgaris"], c:3,
    e:"Bei Psoriasis nicht – Acitretin bei pustulöser Psoriasis & PRP, nicht Isotretinoin."},
  {s:6, q:"Welche Mutation liegt einem Job-Syndrom (autosomal-dominantes Hyper-IgE-Syndrom) zugrunde?",
    o:["DOCK8","STAT3","WAS","NEMO"], c:1,
    e:"AD Hyper-IgE-Syndrom: STAT3-LoF. AR-Form: DOCK8."},
  {s:6, q:"Erstlinie bei eosinophiler pustulöser Follikulitis Ofuji?",
    o:["Indomethacin","Dapson","Prednisolon","UVB"], c:0,
    e:"Indomethacin 50 mg/Tag (NSAR) – First Line, oft dramatisches Ansprechen."}
];

const MATCH = [
  {s:3, t:"Lichen-Subtypen ↔ Klinik", p:[
    ["Lichen planopilaris","Vernarbende Alopezie mit perifollikulärem Erythem"],
    ["Lichen striatus","Blaschkoide Papeln bei Kindern, Hypopigmentierung"],
    ["Lichen nitidus","Polygonale 1–2 mm Papeln, oft Genital/Volarseite"],
    ["Lichen aureus","Solitäre goldenbraune Pigmentpurpura-Plaque"]
  ]},
  {s:3, t:"Biologikum ↔ Target (atopisches Ekzem & Psoriasis)", p:[
    ["Dupilumab","IL-4Rα (IL-4/IL-13)"],
    ["Lebrikizumab","IL-13"],
    ["Nemolizumab","IL-31"],
    ["Risankizumab","IL-23"],
    ["Secukinumab","IL-17A"],
    ["Bimekizumab","IL-17A + IL-17F"]
  ]},
  {s:3, t:"Topika-Risiko ↔ NW im Säuglingsalter", p:[
    ["Povidon-Jod","Hypothyreose"],
    ["Salicylsäure","Metabolische Azidose"],
    ["Prilocain (EMLA)","Methämoglobinämie"],
    ["Neomycin","Oto-/Nephrotoxizität"]
  ]},
  {s:4, t:"Erreger ↔ Hautmanifestation", p:[
    ["Borrelia burgdorferi","Erythema chronicum migrans"],
    ["Streptokokken Gruppe A","Erythema marginatum"],
    ["HSV","Erythema multiforme (EEM)"],
    ["Glucagonom","Nekrolytisches migratorisches Erythem"]
  ]},
  {s:4, t:"Vaskulitis ↔ Antigen/Marker", p:[
    ["GPA (Wegener)","cANCA / PR3"],
    ["EGPA (Churg-Strauss)","pANCA / MPO + Eosinophilie"],
    ["IgA-Vaskulitis","IgA1-Immunkomplexe"],
    ["Polyarteritis nodosa","ANCA-negativ, HBV-assoziiert"]
  ]},
  {s:4, t:"Medikament ↔ Reaktionstyp", p:[
    ["Vancomycin","Lineare IgA-bullöse Dermatose"],
    ["Allopurinol","DRESS / SJS"],
    ["Naproxen","Pseudoporphyrie"],
    ["Carbamazepin (Han-Chinese)","SJS/TEN bei HLA-B*15:02"]
  ]},
  {s:5, t:"AIBD ↔ Autoantigen", p:[
    ["Pemphigus vulgaris","Desmoglein 3 (+1)"],
    ["Pemphigus foliaceus","Desmoglein 1"],
    ["Bullöses Pemphigoid","BP180 / BP230"],
    ["EBA","Kollagen VII"],
    ["Schleimhautpemphigoid","BP180 / Laminin-332"],
    ["DH Duhring","Epidermale Transglutaminase TG3"],
    ["Lineare IgA-Dermatose","LAD-1 / LABD97 (BP180-Fragmente)"]
  ]},
  {s:5, t:"DIF-Muster ↔ Erkrankung", p:[
    ["Interzelluläres IgG (chicken-wire)","Pemphigus vulgaris"],
    ["Lineares IgG/C3 entlang DEJ","Bullöses Pemphigoid"],
    ["Granuläres IgA in Papillenspitzen","DH Duhring"],
    ["Lineares IgA entlang DEJ","Lineare IgA-Dermatose"]
  ]},
  {s:5, t:"EB-Form ↔ Spaltebene/Gen", p:[
    ["EB simplex","Intraepidermal · KRT5/KRT14"],
    ["Junktionale EB","Lamina lucida · Laminin-332"],
    ["Dystrophe EB","Sub-Lamina-densa · COL7A1"],
    ["Kindler-Syndrom","Mehrere Ebenen · FERMT1/Kindlin-1"]
  ]},
  {s:6, t:"Akneform ↔ Charakteristikum", p:[
    ["Acne fulminans","Systemzeichen, Knochenbeteiligung, oft junge Männer + Anabolika"],
    ["Acne tarda","Frauen ab 25 J, hormonell, PCOS-Abklärung"],
    ["Chlorakne","Halogenierte Aromaten, viele offene Komedonen periokular"],
    ["Acne cosmetica","Kosmetika/Öle als Trigger"],
    ["Acne mechanica","Reibung durch Maske/Helm"]
  ]},
  {s:6, t:"Schweißdrüsenstörung ↔ Klinik", p:[
    ["Frey-Syndrom","Gustatorisches Schwitzen nach Parotis-OP"],
    ["Fox-Fordyce","Juckende Follikelpapeln axillär bei jungen Frauen"],
    ["Miliaria crystallina","Tautropfen-Vesikel, geringe Inflammation"],
    ["Idiopathische palmoplantare Hidradenitis","Schmerzhafte Plantarknoten bei sportlichen Kindern"]
  ]}
];

const CLOZE = [
  {s:3, parts:["Die Psoriasis hat eine bimodale Altersverteilung mit Peaks bei ", "BLANK", " und ", "BLANK", " Lebensjahr."], a:["20-30","50-60"]},
  {s:3, q:"PASI > ", parts:["Schwere Psoriasis liegt ab einem PASI-Wert von > ","BLANK"," vor."], a:["10"]},
  {s:3, parts:["Anti-IL-17-Biologika wirken rasch, sind aber langfristig den Anti-","BLANK","-Biologika unterlegen."], a:["IL-23"]},
  {s:3, parts:["Bei der Psoriasis pustulosa generalisata Typ Zumbusch finden sich Mutationen im ","BLANK","-Gen, das den IL-36-Rezeptor-Antagonisten kodiert."], a:["IL36RN"]},
  {s:3, parts:["Filaggrin-Loss-of-function-Mutationen bei der atopischen Dermatitis liegen auf Chromosom ","BLANK","."], a:["1"]},
  {s:3, parts:["Dupilumab ist ein Antikörper gegen den ","BLANK","-Rezeptor und blockiert IL-4 sowie IL-13."], a:["IL-4Rα"]},
  {s:3, parts:["Klassische Trias der reaktiven Arthritis: ","BLANK",", Arthritis und ","BLANK",". Assoziation mit HLA-","BLANK","."], a:["Urethritis","Konjunktivitis","B27"]},
  {s:3, parts:["Acrodermatitis enteropathica beruht auf einem ","BLANK","-Mangel durch Mutation im ","BLANK","-Gen (ZIP4)."], a:["Zink","SLC39A4"]},
  {s:3, parts:["Die Histologie der atopischen Dermatitis ist akut Th","BLANK","-dominiert, chronisch Th","BLANK","-dominiert."], a:["2","1"]},
  {s:4, parts:["Hereditäres Angioödem Typ I/II beruht auf einer Mutation im ","BLANK","-Gen, das den C1-Esterase-Inhibitor codiert."], a:["SERPING1"]},
  {s:4, parts:["Icatibant ist ein ","BLANK","-Rezeptor-Antagonist und blockiert die Wirkung von Bradykinin."], a:["B2"]},
  {s:4, parts:["Beim hereditären Angioödem ist das Komplement-Komplement ","BLANK"," charakteristisch erniedrigt."], a:["C4"]},
  {s:4, parts:["Erythema chronicum migrans entsteht im Median ","BLANK"," Tage nach dem Zeckenstich."], a:["10"]},
  {s:4, parts:["Eine TEN ist definiert ab > ","BLANK"," % epidermaler Ablösung."], a:["30"]},
  {s:4, parts:["DRESS tritt typischerweise ","BLANK"," bis ","BLANK"," Wochen nach Beginn des auslösenden Medikaments auf."], a:["2","8"]},
  {s:4, parts:["AGEP zeigt sich klassisch innerhalb von < ","BLANK"," Tagen nach Medikamentengabe mit < 5 mm sterilen Pusteln."], a:["4"]},
  {s:4, parts:["Das Antiphospholipidsyndrom-Akronym CLOT steht für ","BLANK",", Livedo racemosa, ","BLANK"," und Thrombozytopenie."], a:["Coagulation","Obstetrics"]},
  {s:4, parts:["Cryoglobulinämie-Klinik-Akronym SKIN: Skin, ","BLANK"," injury, Intraarticular inflammation und ","BLANK","."], a:["Kidney","Nerve"]},
  {s:5, parts:["Pemphigus vulgaris zeigt suprabasale Akantholyse mit dem charakteristischen ","BLANK","-Phänomen."], a:["row of tombstones"]},
  {s:5, parts:["Dsg","BLANK"," ist die prädominante Isoform an Mukosae, Dsg","BLANK"," dagegen am Integument."], a:["3","1"]},
  {s:5, parts:["Beim Salt-split-skin-Test wird die Haut in ","BLANK"," mol/L NaCl gespalten, die Spaltebene ist die Lamina ","BLANK","."], a:["1","lucida"]},
  {s:5, parts:["BP180 entspricht Kollagen Typ ","BLANK","."], a:["XVII"]},
  {s:5, parts:["EBA-Antikörper richten sich gegen Kollagen Typ ","BLANK"," in der Lamina densa."], a:["VII"]},
  {s:5, parts:["DH Duhring zeigt in der DIF granuläre ","BLANK","-Ablagerungen in den dermalen Papillenspitzen."], a:["IgA"]},
  {s:5, parts:["Vor Therapie mit Dapson sollte ","BLANK"," bestimmt werden, um eine schwere Hämolyse zu vermeiden."], a:["G6PD"]},
  {s:5, parts:["SSSS-'4×4-Regel': < ","BLANK"," Jahre, ","BLANK"," Tage nach Infekt, 4 Hautareale, 4 Zeichen."], a:["4","4"]},
  {s:5, parts:["Antikörper bei DH Duhring richten sich gegen die ","BLANK"," Transglutaminase (TG","BLANK","), während Anti-tTG (TG","BLANK",") für die Zöliakie spezifisch ist."], a:["epidermale","3","2"]},
  {s:5, parts:["Incontinentia pigmenti Bloch-Sulzberger beruht auf einer Mutation im ","BLANK","-Gen (NEMO)."], a:["IKBKG"]},
  {s:6, parts:["Die Antikonzeption nach Beendigung von Acitretin (Neotigason) muss ","BLANK"," Jahre fortgeführt werden."], a:["3"]},
  {s:6, parts:["Bei Isotretinoin und Alitretinoin reicht eine Antikonzeption von ","BLANK"," Monat nach Therapieende."], a:["1"]},
  {s:6, parts:["HiSCR ist definiert als ≥ ","BLANK"," % Reduktion der Abszesse und entzündlichen Knoten."], a:["50"]},
  {s:6, parts:["Frey-Syndrom: gustatorisches Schwitzen nach Verletzung des N. ","BLANK","."], a:["auriculotemporalis"]},
  {s:6, parts:["Die idealangestrebte Tagesdosis von Isotretinoin bei schwerer Akne beträgt ","BLANK"," mg/kg Körpergewicht."], a:["0.5"]},
  {s:6, parts:["Doxycyclin (Oracea) bei Rosacea ist in-label nur in der subantimikrobiellen Dosis von ","BLANK"," mg täglich zugelassen."], a:["40"]}
];

const TF = [
  {s:3, st:"Bei Psoriasis ist HLA-Cw6 mit der Typ-I-(early-onset-)Form assoziiert.", c:true,
    e:"Korrekt. Typ I: Beginn < 40 J, positive FA, HLA-Cw6 positiv. Typ II: late-onset, negative FA, HLA-Cw6 negativ."},
  {s:3, st:"Methotrexat ist Erstlinientherapie bei atopischer Dermatitis bei Erwachsenen.", c:false,
    e:"Falsch. First Line: TCS, TCI, Emollientien, UV-Therapie. Bei schwerer AD: Dupilumab, Tralokinumab, Lebrikizumab, JAKi."},
  {s:3, st:"Anti-IL-17-Biologika sind bei Patienten mit chronisch-entzündlicher Darmerkrankung relativ kontraindiziert.", c:true,
    e:"Korrekt. Anti-IL-17 kann CIBD verschlechtern. Bei Pso + CIBD bevorzugt Anti-TNF, Ustekinumab oder IL-23-Blocker."},
  {s:3, st:"Die Psoriasis pustulosa palmoplantaris ist häufiger bei Männern als bei Frauen.", c:false,
    e:"Falsch. Frauen sind häufiger betroffen, oft Nikotinabusus assoziiert."},
  {s:3, st:"Phytophotodermatitis erfordert eine vorgängige Sensibilisierung.", c:false,
    e:"Falsch. Phototoxische, nicht immunologische Reaktion durch Furocoumarine + UVA. Kann jeden treffen."},
  {s:3, st:"Beim Pityriasis rosea ist HHV-6 / HHV-7 als Trigger vermutet.", c:true,
    e:"Korrekt. Aetiologie nicht endgueltig geklaert; HHV-6/7-Reaktivierung wird vermutet."},
  {s:3, st:"Allergische Kontaktdermatitis ist eine Typ-I-Hypersensitivitätsreaktion.", c:false,
    e:"Falsch. Typ-IV-Reaktion (T-Zell-vermittelt). Typ I = Soforttyp (IgE/Mastzellen)."},
  {s:3, st:"Filaggrin-Loss-of-function-Mutationen sind mit Ichthyosis vulgaris assoziiert.", c:true,
    e:"Korrekt. > 50 % der Patienten mit Ichthyosis vulgaris haben atopische Stigmata."},
  {s:4, st:"Beim hereditären Angioödem helfen Antihistaminika, Steroide und Adrenalin.", c:false,
    e:"Falsch. HAE ist Bradykinin-vermittelt – nur C1-INH-Konzentrat, Icatibant, Lanadelumab wirken."},
  {s:4, st:"HLA-B*58:01 ist Risikofaktor für Allopurinol-induziertes SJS/TEN.", c:true,
    e:"Korrekt. Insbesondere bei asiatischen Populationen Screening empfohlen."},
  {s:4, st:"DRESS hat eine Mortalität von ca. 25 %.", c:false,
    e:"Falsch. Mortalität ca. 10 %, hauptsächlich durch Leberinsuffizienz. (TEN: ~25 %.)"},
  {s:4, st:"Erythema multiforme kann in eine TEN übergehen.", c:false,
    e:"Falsch. EEM (auch Major-Form) geht NICHT in TEN über. Pathogenese unterschiedlich (HSV vs Medikament)."},
  {s:4, st:"IgA-Vaskulitis (HSP) wird im Kindesalter meist supportiv behandelt.", c:true,
    e:"Korrekt. NSAR und symptomatisch. Steroide bei Nieren-/GIT-Beteiligung."},
  {s:4, st:"Beim akut hämorrhagischen Ödem des Kleinkindes ist die Prognose schlecht.", c:false,
    e:"Falsch. Selbstlimitierend in 1–3 Wochen, gute Prognose."},
  {s:4, st:"Kawasaki-Syndrom wird mit IVIG 2 g/kg und ASS hochdosiert behandelt.", c:true,
    e:"Korrekt. Reduziert Risiko der Koronararterienaneurysmen."},
  {s:4, st:"Bei Triple-positivem Antiphospholipidsyndrom kann Rivaroxaban anstelle von Vitamin-K-Antagonisten gegeben werden.", c:false,
    e:"Falsch. DOAKs (insb. Rivaroxaban) erhöhen das Thromboserisiko bei Triple-positivem APS."},
  {s:4, st:"Lichen aureus ist eine maligne Entität mit hoher MF-Übergangsrate.", c:false,
    e:"Falsch. Lichen aureus gehört zu den haemorrhagisch-pigmentären Dermatosen, gutartig."},
  {s:5, st:"Pemphigus vulgaris zeigt eine subepidermale Akantholyse.", c:false,
    e:"Falsch. Suprabasale Akantholyse. Subepidermal sind die Pemphigoide, EBA, DH, LABD."},
  {s:5, st:"Beim Pemphigus foliaceus sind die Schleimhäute typischerweise nicht betroffen.", c:true,
    e:"Korrekt. Anti-Dsg1-AK – Mukosae sind Dsg3-dominiert, daher kompensiert."},
  {s:5, st:"Beim bullösen Pemphigoid gehört Eosinophilie zu den typischen Befunden.", c:true,
    e:"Korrekt. Eosinophilie in 50 %, erhöhtes Total-IgE, Th2-Antwort."},
  {s:5, st:"DPP-4-Inhibitoren (Gliptine) sind als Trigger des bullösen Pemphigoids bekannt.", c:true,
    e:"Korrekt. Klassische Auslöser, vor allem bei älteren Diabetikern."},
  {s:5, st:"Bei Lineare IgA-Dermatose der Kindheit beträgt die spontane Remission meist 2–4 Jahre.", c:true,
    e:"Korrekt. Therapie: Dapson; Spontanremission bei vielen Kindern."},
  {s:5, st:"Beim Schleimhautpemphigoid führt Anti-Laminin-332-Positivität zu obligatem Tumorscreening.", c:true,
    e:"Korrekt. Assoziation mit Kolon-CA und HNO-PEC."},
  {s:5, st:"SSSS zeigt typischerweise eine ausgeprägte Schleimhautbeteiligung.", c:false,
    e:"Falsch. SSSS hat KEINE Mukosabeteiligung (Mucosae exprimieren kein Dsg1)."},
  {s:5, st:"Bei DH Duhring kann Iodzufuhr die Erkrankung aggravieren.", c:true,
    e:"Korrekt. Iodid erhöht die Aktivität der TG3 und triggert Schübe."},
  {s:5, st:"EB simplex ist die häufigste hereditäre EB-Form.", c:true,
    e:"Korrekt. Etwa 75–85 % aller EBH (KRT5/KRT14)."},
  {s:5, st:"Bullosis diabeticorum benötigt eine systemische Steroidtherapie.", c:false,
    e:"Falsch. Selbstlimitierend in 2–6 Wochen. Wundpflege."},
  {s:5, st:"Coma-Bullae weisen in der DIF lineare IgG-Ablagerungen auf.", c:false,
    e:"Falsch. DIF ist negativ. Histologisch subepidermale Blasen mit Schweißdrüsennekrose."},
  {s:5, st:"Pemphigoid gestationis zeigt in der DIF lineare C3-Ablagerungen entlang der DEJ.", c:true,
    e:"Korrekt. C3 in 100 %, IgG in 30 %. Antigen ist BP180."},
  {s:5, st:"Akantholysis-Lokalisation beim Pemphigus foliaceus ist suprabasal.", c:false,
    e:"Falsch. Stratum granulosum (oberflächlich), daher fragile Bullae und Corn-flakes-Krusten."},
  {s:6, st:"Bei systemischem Isotretinoin reicht eine Antikonzeption für 1 Monat nach Therapieende.", c:true,
    e:"Korrekt. Acitretin: 3 Jahre wegen Reesterification zu Etretinat."},
  {s:6, st:"Tetracycline sind bei Akne ab dem 6. Lebensjahr zugelassen.", c:false,
    e:"Falsch. Tetracycline sind erst ab dem 9. (oft als > 8.) Lebensjahr indiziert; Risiko für Zahnverfärbungen und Knochenwachstumsstörungen."},
  {s:6, st:"Rosacea wird durch eine Th1-/Th17-vermittelte Immunantwort bei dysreguliertem Cathelicidin/TLR2 vermittelt.", c:true,
    e:"Korrekt. Auch UV-Trigger, Demodex und neurogene Inflammation."},
  {s:6, st:"Bei perioraler Dermatitis sind topische Steroide therapieerstklassig.", c:false,
    e:"Falsch. Steroide sind der Trigger! Therapie: Steroidstop, Schwarztee, Pimecrolimus, Metronidazol, Doxycyclin (Oracea)."},
  {s:6, st:"HiSCR-Erfolgskriterium bei HS ist eine ≥ 50%ige Reduktion der Abszesse und entzündlichen Knoten.", c:true,
    e:"Korrekt. Ohne Zunahme der drainierenden Fistelgänge."},
  {s:6, st:"Bei Hidradenitis suppurativa Hurley I sollten Inzisionen mit Drainage-Lasche bevorzugt werden.", c:false,
    e:"Falsch. Lasche erhöht Fistelbildungs-Risiko. Mini-Deroofing per Punch ist überlegen."},
  {s:6, st:"Acne fulminans kann durch Isotretinoin getriggert werden.", c:true,
    e:"Korrekt. Initial systemische Steroide vorschalten, dann Isotretinoin niedrigdosiert einleiten."},
  {s:6, st:"Soolantra (Ivermectin 1 %) ist erste Wahl bei papulopustulöser Rosacea mit Demodex-Hinweis.", c:true,
    e:"Korrekt. Antiparasitär plus antiinflammatorisch."},
  {s:6, st:"Eosinophile pustulöse Follikulitis Ofuji wird klassisch mit Indomethacin behandelt.", c:true,
    e:"Korrekt. NSAR Indomethacin 50 mg/Tag. Bei HIV-assoziierter Form: ART."},
  {s:6, st:"Bei der primären Hyperhidrose ist die Iontophorese in der Schwangerschaft sicher anwendbar.", c:false,
    e:"Falsch. Schwangerschaft ist eine Kontraindikation der Iontophorese."}
];

const FREETEXT = [
  {s:3, q:"Beschreiben Sie die Pathogenese der atopischen Dermatitis in einem strukturierten Absatz.",
    a:"Loss-of-function-Mutationen im Filaggrin-Gen (Epidermal Differentiation Complex auf Chromosom 1) führen zu einer gestörten Hautbarriere. Erhöhte Aktivität der Proteasen Kallikrein 5/7 baut Desmoglein 1 ab, gleichzeitig fehlt der Inhibitor LEKTI. Eindringende Allergene aktivieren dendritische Zellen mit Th2-Antwort: IL-4 und IL-13 induzieren IgE-Produktion und drosseln zusätzlich Filaggrin. IL-31 vermittelt Pruritus. Saurer pH fällt weg, was die Besiedlung mit S. aureus fördert (Superantigene verstärken Th2). Akute Phase ist Th2-, chronische Phase Th1-dominiert."},
  {s:3, q:"Welche Differentialdiagnosen sollten bei einer Erythrodermie unklarer Ursache abgeklärt werden?",
    a:"Häufig: Psoriasis, atopische Dermatitis, schwere Arzneimittelreaktionen (DRESS, SJS/TEN, AME), kutanes T-Zell-Lymphom (Sézary > MF), allergische Kontaktdermatitis, PRP, paraneoplastisch. Selten: Skabies, GvHD, Pemphigus foliaceus, BP, paraneoplastischer Pemphigus, Ichthyose, Papuloerythroderma Ofuji, chronisch aktinische Dermatitis, SSSS, Hypereosinophiliesyndrom, Lupus, juvenile Dermatomyositis. Diagnostik: BB+Diff, Elektrolyte, Nieren-/Leberparameter, CRP, Total-IgE, Abstriche, wiederholte Hautbiopsien (zum Ausschluss MF), ggf. Lymphknoten-Biopsie, PET."},
  {s:3, q:"Wie würden Sie eine schwere therapieresistente Plaque-Psoriasis bei einer 32-jährigen Patientin mit M. Crohn behandeln?",
    a:"Therapeutika der Wahl sind TNF-alpha-Inhibitoren (Adalimumab, Infliximab) wegen der Doppelindikation Psoriasis und CIBD. Alternativ Ustekinumab (IL-12/23) oder IL-23-Inhibitoren wie Risankizumab/Guselkumab. Anti-IL-17-Inhibitoren (Secukinumab, Ixekizumab, Bimekizumab) sind relativ kontraindiziert, da sie eine paradoxe Verschlechterung der CIBD auslösen können. Bei aktivem Kinderwunsch wäre Certolizumab pegol (Cimzia) bevorzugt, da es nicht plazentagängig ist."},
  {s:4, q:"Erläutern Sie den diagnostischen Algorithmus bei Verdacht auf Pemphigoid gestationis.",
    a:"Klinik: Pruritus mit periumbilical urtikariellen Plaques und Bullae im 2./3. Trimenon oder peripartal. Diagnostik: 1) Hautbiopsie mit Histologie (subepidermale Blase mit eosinophilem Infiltrat). 2) DIF aus läsionsnaher Haut: lineare C3-Ablagerungen entlang DEJ in 100 % positiv, IgG in ca. 30 %. 3) ELISA: Anti-BP180-NC16A-Antikörper. 4) Bei Verdacht ggf. fetomaternale Überwachung wegen erhöhten Risikos für Frühgeburt und SGA. DDx: PUPPP (kein BP180-AK, periumbilical Aussparung), atopic eruption of pregnancy, intrahepatische Cholestase. Therapie: TCS Klasse III–IV, bei schwerem Verlauf systemische Steroide degressiv."},
  {s:4, q:"Beschreiben Sie die diagnostische Aufarbeitung und Akuttherapie eines V.a. SJS/TEN.",
    a:"Anamnese mit allen Medikamenten der letzten 8 Wochen. Klinik: schmerzhafte erythematös-livide Maculae, Bullae, Erosionen, mukosale Beteiligung. Hautbiopsie zur DD-Sicherung (epidermale Nekrose, subepidermale Bullae). Labor: BB+Diff, Elektrolyte, Nieren-/Leberparameter, BGA, Gerinnung. SCORTEN-Score zur Prognoseabschätzung. Therapieprinzipien: 1) Sofortiges Absetzen des Auslösers. 2) Aufnahme auf Intensiv-/Verbrennungsstation. 3) Wundpflege wie Verbrennung. 4) Fluid-/Elektrolytmanagement. 5) Schmerztherapie. 6) Augenkonsil zur Vermeidung von Symblepharon. 7) Antiseptische Mundpflege. 8) Cave Refeeding-Syndrom. 9) Systemische Therapie: IVIG 3-5 g/kg KG (blockiert Fas-FasL) oder Ciclosporin 3-5 mg/kg KG (hemmt Keratinozytenapoptose), nicht beide kombinieren. 10) Augen-, HNO- und Genital-Konsile."},
  {s:5, q:"Vergleichen Sie die Diagnostik und Therapie von Pemphigus vulgaris und bulloesem Pemphigoid.",
    a:"PV: suprabasale Akantholyse ('row of tombstones'), DIF mit interzellulären IgG/C3 ('chicken-wire'), IIF auf Affenösophagus, ELISA Anti-Dsg1/3. Schleimhauterosionen typisch zuerst. Therapie: Rituximab 1 g i.v. Tag 0/14 als First Line plus überbrückend Prednisolon 1 mg/kg KG degressiv über 6 Monate. Alternativen: AZA, MMF, Cyclophosphamid bei schwerem Verlauf. BP: subepidermale Blase, DIF lineare IgG/C3 entlang DEJ, IIF auf Salt-split-skin mit Bindung am Blasendach (BP180/230), ELISA Anti-BP180/BP230. Klinik: pralle Bullae, älterer Patient, oft Pruritus initial. Therapie: TCS Kl. IV bei lokalisiert; sonst Prednisolon 0.5-1 mg/kg degressiv über 6 Monate. Steroidsparend Doxycyclin 200 mg/Tag plus Nicotinamid, alternativ AZA, MMF, MTX. Refraktär: Dupilumab, Omalizumab, Rituximab, IVIG."},
  {s:6, q:"Welche Aspekte spielen bei der Aufklärung einer 19-jährigen Patientin vor Beginn einer systemischen Isotretinoin-Therapie eine Rolle?",
    a:"1) Teratogenität: zwei sichere Kontrazeptionsmethoden (z.B. Hormon + Kondom), monatliche Schwangerschaftstests, 1 Monat Verhütung nach Therapieende. Cave Schwangerschaft: IUFT, Spina bifida, Hydro-/Mikrozephalus, Lippen-Kiefer-Gaumenspalte, Ohranomalien, kardiovaskuläre Fehlbildungen, Nebenschilddrüsen-/Thymus-Fehlbildungen. 2) Mukokutane Trockenheit: Lippenpflege (Vaseline), künstliche Tränen, intensivere Hautpflege, ggf. Cheilitis. 3) Stimmungsveränderungen, depressive Symptome, Suizidgedanken: regelmäßige Erfassung (PHQ-9). 4) Lipidstoffwechsel und Leber: Bestimmung von Lipidpanel und Transaminasen vor Therapie und nach 2 Monaten. 5) Sehprobleme bei Nacht. 6) Keine Tetracyclin-Komedikation (Pseudotumor cerebri). 7) Lasertherapie/Chirurgie 6 Monate nach Therapieende. 8) Kein Blutspenden für 1 Monat nach Therapieende. 9) Triggerung Acne fulminans möglich."}
];


// =========================================================================
// BILDQUIZ – SVG-basierte Erkennungsaufgaben
// =========================================================================
const IMG = [
  {s:3, cap:"Verteilungsmuster bei einem Erwachsenen", q:"Welcher klinische Subtyp passt zu diesem Verteilungsmuster (Streckseiten, Knie/Ellenbogen, Capillitium, sakral)?",
    o:["Atopische Dermatitis (Erwachsenenform)","Plaque-Psoriasis","Pityriasis rosea","Lichen ruber"], c:1,
    e:"Klassische Plaque-Psoriasis: Streckseiten, lumbosakrale Region, Capillitium. AD im Erwachsenenalter eher Beugen.",
    svg:`<svg viewBox="0 0 280 360" xmlns="http://www.w3.org/2000/svg"><ellipse cx="140" cy="50" rx="32" ry="38" fill="#fce7f3" stroke="#9ca3af" stroke-width="2"/><path d="M105,80 L80,180 L80,260 L70,360 L100,360 L110,260 L120,200 L160,200 L170,260 L180,360 L210,360 L200,260 L200,180 L175,80 Z" fill="#fce7f3" stroke="#9ca3af" stroke-width="2"/><path d="M80,90 L40,180 L30,260 L25,290 L42,290 L50,260 L60,200 L80,160 Z" fill="#fce7f3" stroke="#9ca3af" stroke-width="2"/><path d="M200,90 L240,180 L250,260 L255,290 L238,290 L230,260 L220,200 L200,160 Z" fill="#fce7f3" stroke="#9ca3af" stroke-width="2"/><ellipse cx="140" cy="40" rx="14" ry="10" fill="#dc2626" opacity="0.7"/><ellipse cx="40" cy="190" rx="9" ry="7" fill="#dc2626" opacity="0.7"/><ellipse cx="240" cy="190" rx="9" ry="7" fill="#dc2626" opacity="0.7"/><ellipse cx="100" cy="290" rx="11" ry="8" fill="#dc2626" opacity="0.7"/><ellipse cx="180" cy="290" rx="11" ry="8" fill="#dc2626" opacity="0.7"/><ellipse cx="140" cy="220" rx="22" ry="10" fill="#dc2626" opacity="0.6"/></svg>`},
  {s:3, cap:"Stamm-Verteilung mit charakteristischem Muster", q:"7-14 Tage nach 'Herald Patch' breitet sich dieses Muster auf den Stamm aus. Diagnose?",
    o:["Pityriasis rosea (Tannenbaum)","Pityriasis lichenoides chronica","Lues II","Lichen ruber"], c:0,
    e:"Klassisches Tannenbaum-Phänomen entlang der Langer-Linien bei Pityriasis rosea (HHV-6/7).",
    svg:`<svg viewBox="0 0 280 360" xmlns="http://www.w3.org/2000/svg"><path d="M100,80 L80,250 L80,320 L200,320 L200,250 L180,80 Z" fill="#fce7f3" stroke="#9ca3af" stroke-width="2"/><ellipse cx="140" cy="100" rx="14" ry="10" fill="#dc2626" opacity="0.85"/><text x="160" y="98" font-size="10" fill="#374151" font-family="sans-serif">Herald Patch</text><g stroke="#ef4444" stroke-width="2.5" opacity="0.7"><line x1="105" y1="140" x2="135" y2="160"/><line x1="175" y1="140" x2="145" y2="160"/><line x1="100" y1="180" x2="135" y2="200"/><line x1="180" y1="180" x2="145" y2="200"/><line x1="95" y1="220" x2="135" y2="240"/><line x1="185" y1="220" x2="145" y2="240"/><line x1="92" y1="260" x2="135" y2="280"/><line x1="188" y1="260" x2="145" y2="280"/></g><g fill="#ef4444" opacity="0.6"><ellipse cx="120" cy="150" rx="6" ry="3"/><ellipse cx="160" cy="150" rx="6" ry="3"/><ellipse cx="115" cy="190" rx="7" ry="3.5"/><ellipse cx="165" cy="190" rx="7" ry="3.5"/></g></svg>`},
  {s:3, cap:"Klinik bei einem 8 Monate alten Säugling", q:"Welche Befund-Konstellation passt zur infantilen atopischen Dermatitis?",
    o:["Wangen, Streckseiten, Hals – Aussparung der Windelregion","Streng intertriginös","Plaques an Knien","Periorale Pusteln"], c:0,
    e:"Infantile AD: Wangen, Hals, Stirn, Streckseiten – Aussparung der Windelregion und zentrofazialer Areale.",
    svg:`<svg viewBox="0 0 280 320" xmlns="http://www.w3.org/2000/svg"><ellipse cx="140" cy="50" rx="34" ry="38" fill="#fce7f3" stroke="#9ca3af" stroke-width="2"/><path d="M105,80 L85,180 L80,260 L70,310 L110,310 L120,260 L120,200 L160,200 L160,260 L170,310 L210,310 L200,260 L195,180 L175,80 Z" fill="#fce7f3" stroke="#9ca3af" stroke-width="2"/><path d="M85,95 L50,180 L45,250 L60,250 L70,180 L90,140 Z" fill="#fce7f3" stroke="#9ca3af" stroke-width="2"/><path d="M195,95 L230,180 L235,250 L220,250 L210,180 L190,140 Z" fill="#fce7f3" stroke="#9ca3af" stroke-width="2"/><ellipse cx="118" cy="55" rx="10" ry="7" fill="#ef4444" opacity="0.6"/><ellipse cx="162" cy="55" rx="10" ry="7" fill="#ef4444" opacity="0.6"/><ellipse cx="55" cy="180" rx="8" ry="20" fill="#ef4444" opacity="0.6"/><ellipse cx="225" cy="180" rx="8" ry="20" fill="#ef4444" opacity="0.6"/><ellipse cx="100" cy="280" rx="9" ry="14" fill="#ef4444" opacity="0.6"/><ellipse cx="180" cy="280" rx="9" ry="14" fill="#ef4444" opacity="0.6"/><rect x="115" y="200" width="50" height="40" fill="#fff" stroke="#9ca3af" stroke-dasharray="3,3"/><text x="120" y="225" font-size="9" fill="#374151" font-family="sans-serif">Windel frei</text></svg>`},
  {s:4, cap:"Charakteristische Läsion mit drei Zonen", q:"Welche Erkrankung wird durch diese typische 'Targetlaesion' charakterisiert?",
    o:["Erythema chronicum migrans","Erythema multiforme (EEM)","Granuloma annulare","Tinea corporis"], c:1,
    e:"Typisch targetoide Läsion mit drei Zonen – EEM. Trigger meist HSV.",
    svg:`<svg viewBox="0 0 280 220" xmlns="http://www.w3.org/2000/svg"><circle cx="140" cy="110" r="80" fill="#dc2626" opacity="0.35"/><circle cx="140" cy="110" r="55" fill="#fff8e1"/><circle cx="140" cy="110" r="35" fill="#dc2626" opacity="0.85"/><circle cx="140" cy="110" r="14" fill="#7f1d1d"/><text x="50" y="30" font-size="10" fill="#6b7280" font-family="sans-serif">Zone 1: zentrale Nekrose</text><text x="50" y="200" font-size="10" fill="#6b7280" font-family="sans-serif">Zone 3: peripheres Erythem</text></svg>`},
  {s:4, cap:"Anuläres Erythem mit innerer Schuppung", q:"Anuläre Plaques mit zentraler Abblassung und 'trailing scale'. In ca. 50% findet sich welche Assoziation?",
    o:["Tinea (insb. T. pedis)","Lupus erythematodes","Glucagonom","Kawasaki"], c:0,
    e:"Erythema annulare centrifugum: in ca. 50% Tinea-Assoziation. Trailing scale (innen liegende Schuppe) charakteristisch.",
    svg:`<svg viewBox="0 0 280 220" xmlns="http://www.w3.org/2000/svg"><circle cx="140" cy="110" r="80" fill="#fff" stroke="#dc2626" stroke-width="6" opacity="0.7"/><circle cx="140" cy="110" r="71" fill="none" stroke="#fbbf24" stroke-width="3" stroke-dasharray="3,1" opacity="0.85"/><text x="60" y="200" font-size="11" fill="#374151" font-family="sans-serif">Trailing scale = innen liegende Schuppe</text></svg>`},
  {s:4, cap:"Erythem nach Aufenthalt im Schwarzwald", q:"Bei einem Wanderer nach Zeckenstich. Therapie 1. Wahl?",
    o:["Doxycyclin 2 × 100 mg p.o. 10–14 Tage","Cefuroxim 500 mg 4x","Clindamycin","Cotrimoxazol"], c:0,
    e:"Erythema chronicum migrans = klassisches Erstsymptom der Lyme-Borreliose. Doxycyclin ist Erstwahl beim Erwachsenen.",
    svg:`<svg viewBox="0 0 280 220" xmlns="http://www.w3.org/2000/svg"><rect x="0" y="0" width="280" height="220" fill="#fde2cb"/><circle cx="140" cy="110" r="85" fill="#dc2626" opacity="0.25"/><circle cx="140" cy="110" r="60" fill="#fde2cb"/><circle cx="140" cy="110" r="30" fill="#dc2626" opacity="0.4"/><circle cx="140" cy="110" r="6" fill="#7f1d1d"/></svg>`},
  {s:4, cap:"Klinik bei einer 12-Jaehrigen", q:"Palpable Purpura an Unterschenkeln + Bauchschmerzen + Arthralgien + Hämaturie. Diagnose?",
    o:["Cryoglobulinämie","IgA-Vaskulitis (Henoch-Schönlein)","APS","Akut hämorrhagisches Ödem"], c:1,
    e:"Klassische Tetrade: palpable Purpura, Arthralgien, Abdomen, Glomerulonephritis. Postinfektiös (Streptokokken).",
    svg:`<svg viewBox="0 0 280 280" xmlns="http://www.w3.org/2000/svg"><path d="M120,30 L120,240 L130,260 L150,260 L155,240 L155,30 Z" fill="#fde2cb" stroke="#9ca3af"/><g fill="#7c2d12" opacity="0.85"><circle cx="130" cy="100" r="2"/><circle cx="138" cy="105" r="2"/><circle cx="135" cy="115" r="2"/><circle cx="145" cy="120" r="2"/><circle cx="125" cy="130" r="2"/><circle cx="140" cy="135" r="2"/><circle cx="150" cy="142" r="2"/><circle cx="132" cy="148" r="2"/><circle cx="142" cy="155" r="2.5"/><circle cx="125" cy="160" r="2"/><circle cx="148" cy="170" r="2"/><circle cx="135" cy="175" r="2"/><circle cx="128" cy="185" r="2.5"/><circle cx="145" cy="190" r="2"/><circle cx="138" cy="200" r="2"/><circle cx="150" cy="210" r="2.5"/><circle cx="125" cy="218" r="2"/><circle cx="140" cy="225" r="2.5"/><circle cx="148" cy="232" r="2"/><circle cx="135" cy="240" r="2"/></g><text x="170" y="160" font-size="11" fill="#374151" font-family="sans-serif">palpable Purpura</text></svg>`},
  {s:5, cap:"DIF-Befund mit charakteristischem Muster", q:"DIF zeigt netzartige interzelluläre IgG-Ablagerungen ('chicken-wire'). Diagnose?",
    o:["Bullöses Pemphigoid","Pemphigus vulgaris","DH Duhring","Lineare IgA-Dermatose"], c:1,
    e:"Pemphigus vulgaris: interzelluläres IgG/C3-Muster ('chicken-wire pattern') = Korrelat zur suprabasalen Akantholyse.",
    svg:`<svg viewBox="0 0 280 220" xmlns="http://www.w3.org/2000/svg"><rect x="20" y="20" width="240" height="180" fill="#1e293b"/><g stroke="#22d3ee" stroke-width="1.8" fill="none" opacity="0.95"><path d="M40,40 L60,30 L80,40 L80,60 L60,70 L40,60 Z"/><path d="M80,40 L100,30 L120,40 L120,60 L100,70 L80,60"/><path d="M120,40 L140,30 L160,40 L160,60 L140,70 L120,60"/><path d="M160,40 L180,30 L200,40 L200,60 L180,70 L160,60"/><path d="M200,40 L220,30 L240,40 L240,60 L220,70 L200,60"/><path d="M40,60 L40,80 L60,90 L60,70"/><path d="M60,90 L80,80 L80,60"/><path d="M80,80 L100,90 L100,70"/><path d="M100,90 L120,80 L120,60"/><path d="M120,80 L140,90 L140,70"/><path d="M140,90 L160,80 L160,60"/><path d="M160,80 L180,90 L180,70"/><path d="M180,90 L200,80 L200,60"/><path d="M40,80 L60,90 L60,110 L40,120 L40,100"/><path d="M60,110 L80,100 L80,80"/><path d="M80,100 L100,110 L100,90"/><path d="M100,110 L120,100 L120,80"/><path d="M120,100 L140,110 L140,90"/><path d="M140,110 L160,100 L160,80"/></g><line x1="20" y1="170" x2="260" y2="170" stroke="#94a3b8" stroke-width="2" stroke-dasharray="3,3"/><text x="22" y="190" font-size="10" fill="#94a3b8" font-family="sans-serif">DEJ</text><text x="22" y="210" font-size="10" fill="#22d3ee" font-family="sans-serif">interzelluläres IgG/C3</text></svg>`},
  {s:5, cap:"DIF mit linearen Ablagerungen entlang der DEJ", q:"Welche Erkrankung passt zu linearen IgG/C3-Ablagerungen entlang der DEJ?",
    o:["Pemphigus vulgaris","Bullöses Pemphigoid","Lichen ruber","Granuloma annulare"], c:1,
    e:"BP: lineare IgG (insb. IgG1/4) und/oder C3 entlang der DEJ. Salt-split-skin: Bindung am Blasendach (BP180/BP230).",
    svg:`<svg viewBox="0 0 280 220" xmlns="http://www.w3.org/2000/svg"><rect x="20" y="20" width="240" height="180" fill="#1e293b"/><text x="22" y="40" font-size="10" fill="#94a3b8" font-family="sans-serif">Epidermis</text><text x="22" y="195" font-size="10" fill="#94a3b8" font-family="sans-serif">Dermis</text><line x1="30" y1="120" x2="250" y2="120" stroke="#22d3ee" stroke-width="6" opacity="0.95"/><line x1="30" y1="125" x2="250" y2="125" stroke="#22d3ee" stroke-width="2" opacity="0.5"/><text x="100" y="145" font-size="11" fill="#22d3ee" font-family="sans-serif">linear IgG/C3 entlang DEJ</text></svg>`},
  {s:5, cap:"DIF mit granulären Ablagerungen", q:"Granuläre IgA-Ablagerungen in den dermalen Papillenspitzen passen zu welcher Erkrankung?",
    o:["Lineare IgA-Dermatose","Dermatitis herpetiformis Duhring","IgA-Pemphigus","Bullöses Pemphigoid"], c:1,
    e:"DH Duhring: granuläre IgA in den Papillenspitzen. Antigen ist die epidermale Transglutaminase (TG3).",
    svg:`<svg viewBox="0 0 280 220" xmlns="http://www.w3.org/2000/svg"><rect x="20" y="20" width="240" height="180" fill="#1e293b"/><path d="M30,120 Q50,80 70,120 Q90,80 110,120 Q130,80 150,120 Q170,80 190,120 Q210,80 230,120 Q250,80 250,120" fill="none" stroke="#94a3b8" stroke-width="2"/><g fill="#22d3ee"><circle cx="50" cy="98" r="2.5"/><circle cx="55" cy="92" r="2.5"/><circle cx="46" cy="92" r="2"/><circle cx="58" cy="100" r="2"/><circle cx="90" cy="98" r="2.5"/><circle cx="95" cy="92" r="2.5"/><circle cx="86" cy="92" r="2"/><circle cx="98" cy="100" r="2"/><circle cx="130" cy="98" r="2.5"/><circle cx="135" cy="92" r="2.5"/><circle cx="126" cy="92" r="2"/><circle cx="138" cy="100" r="2"/><circle cx="170" cy="98" r="2.5"/><circle cx="175" cy="92" r="2.5"/><circle cx="166" cy="92" r="2"/><circle cx="178" cy="100" r="2"/><circle cx="210" cy="98" r="2.5"/><circle cx="215" cy="92" r="2.5"/></g><text x="22" y="40" font-size="10" fill="#94a3b8" font-family="sans-serif">Epidermis</text><text x="22" y="195" font-size="11" fill="#22d3ee" font-family="sans-serif">granuläre IgA in Papillenspitzen</text></svg>`},
  {s:5, cap:"Histologische Schemazeichnung", q:"Welche Erkrankung zeigt suprabasale Akantholyse mit basalen Keratinozyten als 'row of tombstones'?",
    o:["Bullöses Pemphigoid","Pemphigus vulgaris","DH Duhring","EB simplex"], c:1,
    e:"Pemphigus vulgaris: Akantholyse direkt oberhalb der Basalzellschicht; basale Keratinozyten verbleiben grabsteinartig.",
    svg:`<svg viewBox="0 0 320 220" xmlns="http://www.w3.org/2000/svg"><rect x="20" y="20" width="280" height="180" fill="#fef3c7"/><rect x="20" y="20" width="280" height="20" fill="#fcd34d" opacity="0.6"/><g fill="#a3e635" stroke="#65a30d" stroke-width="1"><circle cx="60" cy="65" r="6"/><circle cx="90" cy="55" r="6"/><circle cx="120" cy="68" r="6"/><circle cx="160" cy="58" r="6"/><circle cx="200" cy="65" r="6"/><circle cx="240" cy="60" r="6"/></g><rect x="30" y="100" width="260" height="20" fill="#fff" stroke="#94a3b8" stroke-dasharray="3,2"/><g fill="#7c2d12"><rect x="35" y="125" width="14" height="22" rx="2"/><rect x="55" y="125" width="14" height="22" rx="2"/><rect x="75" y="125" width="14" height="22" rx="2"/><rect x="95" y="125" width="14" height="22" rx="2"/><rect x="115" y="125" width="14" height="22" rx="2"/><rect x="135" y="125" width="14" height="22" rx="2"/><rect x="155" y="125" width="14" height="22" rx="2"/><rect x="175" y="125" width="14" height="22" rx="2"/><rect x="195" y="125" width="14" height="22" rx="2"/><rect x="215" y="125" width="14" height="22" rx="2"/><rect x="235" y="125" width="14" height="22" rx="2"/><rect x="255" y="125" width="14" height="22" rx="2"/><rect x="275" y="125" width="14" height="22" rx="2"/></g><line x1="20" y1="148" x2="300" y2="148" stroke="#374151" stroke-width="2"/><text x="22" y="170" font-size="10" fill="#374151" font-family="sans-serif">Dermis</text><text x="160" y="115" font-size="10" fill="#dc2626" font-family="sans-serif">Akantholyse-Spalt</text><text x="160" y="180" font-size="11" fill="#7c2d12" font-family="sans-serif">'row of tombstones'</text></svg>`},
  {s:5, cap:"Histologische Schemazeichnung", q:"Subepidermale Blasen mit eosinophilenreichem Infiltrat passen zu welcher Erkrankung?",
    o:["Pemphigus foliaceus","Bullöses Pemphigoid","Erythema multiforme","Lichen ruber"], c:1,
    e:"BP: subepidermale Blase, eosinophile Spongiose und eosinophilenreiches Infiltrat. Th2-Antwort, IgE oft erhöht.",
    svg:`<svg viewBox="0 0 320 220" xmlns="http://www.w3.org/2000/svg"><rect x="20" y="20" width="280" height="60" fill="#fcd34d" opacity="0.6"/><text x="22" y="42" font-size="10" fill="#374151" font-family="sans-serif">Epidermis (intakt)</text><ellipse cx="160" cy="100" rx="120" ry="20" fill="#fff" stroke="#94a3b8" stroke-width="1.5"/><g fill="#f87171"><circle cx="80" cy="100" r="4"/><circle cx="110" cy="98" r="4"/><circle cx="140" cy="105" r="4"/><circle cx="170" cy="98" r="4"/><circle cx="200" cy="103" r="4"/><circle cx="230" cy="100" r="4"/><circle cx="60" cy="140" r="4"/><circle cx="90" cy="150" r="4"/><circle cx="130" cy="145" r="4"/><circle cx="170" cy="155" r="4"/><circle cx="210" cy="148" r="4"/><circle cx="250" cy="142" r="4"/></g><rect x="20" y="120" width="280" height="80" fill="#fde68a" opacity="0.4"/><text x="22" y="195" font-size="10" fill="#374151" font-family="sans-serif">Dermis (Eosinophilen-reich)</text><text x="120" y="105" font-size="10" fill="#dc2626" font-family="sans-serif">subepidermale Blase</text></svg>`},
  {s:3, cap:"Mikroskopischer Befund", q:"'Spaghetti-and-meatballs' im Pilzpräparat. Diagnose?",
    o:["Tinea corporis","Pityriasis versicolor","Candida intertrigo","Trichophyton"], c:1,
    e:"Pityriasis versicolor durch Malassezia furfur: kurze Hyphen + runde Hefen.",
    svg:`<svg viewBox="0 0 280 220" xmlns="http://www.w3.org/2000/svg"><rect x="20" y="20" width="240" height="180" fill="#0f172a"/><g stroke="#fbbf24" stroke-width="2.5" fill="none"><path d="M40,60 L80,80 L120,60"/><path d="M150,90 L190,70 L230,90"/><path d="M50,120 L100,140 L150,120"/><path d="M170,160 L210,140 L250,160"/><path d="M40,180 L80,170 L120,180"/></g><g fill="#f87171"><circle cx="70" cy="65" r="5"/><circle cx="100" cy="75" r="5"/><circle cx="180" cy="80" r="5"/><circle cx="80" cy="135" r="5"/><circle cx="130" cy="125" r="5"/><circle cx="190" cy="155" r="5"/><circle cx="60" cy="175" r="5"/><circle cx="110" cy="170" r="5"/></g><text x="30" y="200" font-size="11" fill="#fbbf24" font-family="sans-serif">'Spaghetti and Meatballs'</text></svg>`},
  {s:5, cap:"Salt-split-skin Befund", q:"Auf Salt-split-skin bindet das IgG am DACH der Blase. Welche Erkrankung passt am besten?",
    o:["EBA","Bullöses Pemphigoid","Anti-Laminin-332-MMP","Bullöser SLE"], c:1,
    e:"Antigene oberhalb der Lamina lucida (BP180, BP230) → Bindung am Blasendach.",
    svg:`<svg viewBox="0 0 320 220" xmlns="http://www.w3.org/2000/svg"><rect x="20" y="20" width="280" height="80" fill="#fcd34d" opacity="0.7"/><text x="30" y="60" font-size="11" fill="#374151" font-family="sans-serif">Epidermis (Blasendach)</text><g fill="#22d3ee"><circle cx="50" cy="95" r="3"/><circle cx="80" cy="95" r="3"/><circle cx="110" cy="95" r="3"/><circle cx="140" cy="95" r="3"/><circle cx="170" cy="95" r="3"/><circle cx="200" cy="95" r="3"/><circle cx="230" cy="95" r="3"/><circle cx="260" cy="95" r="3"/><circle cx="290" cy="95" r="3"/></g><line x1="20" y1="100" x2="300" y2="100" stroke="#22d3ee" stroke-width="3"/><rect x="20" y="100" width="280" height="20" fill="#fff" stroke="#94a3b8" stroke-dasharray="3,2"/><text x="120" y="115" font-size="10" fill="#9ca3af" font-family="sans-serif">Spaltung (Lamina lucida)</text><rect x="20" y="120" width="280" height="80" fill="#fde68a" opacity="0.4"/><text x="30" y="160" font-size="11" fill="#374151" font-family="sans-serif">Dermis (Blasenboden)</text></svg>`},
  {s:5, cap:"Salt-split-skin Befund", q:"Bei welcher Diagnose bindet das IgG am BODEN der gespaltenen Haut?",
    o:["BP","Pemphigoid gestationis","EBA","Anti-p200-Pemphigoid"], c:2,
    e:"EBA: Anti-Kollagen-VII-AK in der Lamina densa → Boden-Muster. Auch Anti-Lam-332-MMP und bullöser SLE.",
    svg:`<svg viewBox="0 0 320 220" xmlns="http://www.w3.org/2000/svg"><rect x="20" y="20" width="280" height="80" fill="#fcd34d" opacity="0.7"/><text x="30" y="60" font-size="11" fill="#374151" font-family="sans-serif">Epidermis (Blasendach)</text><rect x="20" y="100" width="280" height="20" fill="#fff" stroke="#94a3b8" stroke-dasharray="3,2"/><text x="120" y="115" font-size="10" fill="#9ca3af" font-family="sans-serif">Spalt</text><rect x="20" y="120" width="280" height="80" fill="#fde68a" opacity="0.4"/><line x1="20" y1="125" x2="300" y2="125" stroke="#22d3ee" stroke-width="3"/><g fill="#22d3ee"><circle cx="50" cy="130" r="3"/><circle cx="80" cy="130" r="3"/><circle cx="110" cy="130" r="3"/><circle cx="140" cy="130" r="3"/><circle cx="170" cy="130" r="3"/><circle cx="200" cy="130" r="3"/><circle cx="230" cy="130" r="3"/><circle cx="260" cy="130" r="3"/><circle cx="290" cy="130" r="3"/></g><text x="30" y="170" font-size="11" fill="#374151" font-family="sans-serif">IgG bindet am Boden</text></svg>`},
  {s:3, cap:"Klinisches Phänomen", q:"Lineare Anordnung von Plaques entlang einer Kratzspur: Wie heisst dieses Phänomen?",
    o:["Auspitz-Phänomen","Köbner-Phänomen (isomorpher Reizeffekt)","Nikolski-Phänomen","Phänomen des letzten Häutchens"], c:1,
    e:"Köbner-Phänomen: Auftreten der Erkrankung in zuvor verletzter Haut. Klassisch Psoriasis und Lichen ruber.",
    svg:`<svg viewBox="0 0 280 200" xmlns="http://www.w3.org/2000/svg"><rect x="10" y="10" width="260" height="180" fill="#fce7f3" stroke="#9ca3af"/><line x1="40" y1="160" x2="240" y2="40" stroke="#9ca3af" stroke-width="1" stroke-dasharray="2,3"/><g fill="#dc2626" opacity="0.75"><ellipse cx="60" cy="148" rx="9" ry="6" transform="rotate(-30 60 148)"/><ellipse cx="100" cy="124" rx="9" ry="6" transform="rotate(-30 100 124)"/><ellipse cx="140" cy="100" rx="9" ry="6" transform="rotate(-30 140 100)"/><ellipse cx="180" cy="76" rx="9" ry="6" transform="rotate(-30 180 76)"/><ellipse cx="220" cy="52" rx="9" ry="6" transform="rotate(-30 220 52)"/></g><text x="20" y="30" font-size="11" fill="#374151" font-family="sans-serif">Lineare Plaques entlang Kratzspur</text></svg>`},
  {s:6, cap:"Klinik einer akneähnlichen Eruption", q:"Periorale Pusteln mit charakteristischer Aussparung der Lippen-Haut-Grenze. Diagnose?",
    o:["Akne vulgaris","Periorale Dermatitis","Rosacea papulopustulosa","Demodex-Follikulitis"], c:1,
    e:"Periorale Dermatitis: typische Aussparung des Lippenrot-Hautrandes. Trigger: topische/inhalative Steroide.",
    svg:`<svg viewBox="0 0 280 280" xmlns="http://www.w3.org/2000/svg"><ellipse cx="140" cy="140" rx="90" ry="115" fill="#fde2cb" stroke="#9ca3af" stroke-width="2"/><ellipse cx="115" cy="115" rx="9" ry="5" fill="#fff" stroke="#374151"/><ellipse cx="165" cy="115" rx="9" ry="5" fill="#fff" stroke="#374151"/><circle cx="115" cy="115" r="3" fill="#374151"/><circle cx="165" cy="115" r="3" fill="#374151"/><path d="M140,135 L135,165 L145,165 Z" fill="none" stroke="#374151"/><ellipse cx="140" cy="195" rx="22" ry="6" fill="#fda4af"/><g fill="#dc2626" opacity="0.85"><circle cx="105" cy="200" r="2.5"/><circle cx="100" cy="210" r="2.5"/><circle cx="110" cy="218" r="2.5"/><circle cx="170" cy="200" r="2.5"/><circle cx="175" cy="210" r="2.5"/><circle cx="165" cy="218" r="2.5"/><circle cx="118" cy="220" r="2.5"/><circle cx="160" cy="220" r="2.5"/><circle cx="130" cy="225" r="2.5"/><circle cx="150" cy="225" r="2.5"/><circle cx="138" cy="232" r="2.5"/><circle cx="142" cy="232" r="2.5"/></g><ellipse cx="140" cy="195" rx="34" ry="11" fill="none" stroke="#fbbf24" stroke-width="1.5" stroke-dasharray="2,2"/><text x="170" y="195" font-size="9" fill="#92400e" font-family="sans-serif">freie Zone</text></svg>`},
  {s:6, cap:"Hautbefund einer chronisch entzündlichen Erkrankung", q:"Schmerzhafte Knoten, Abszesse und Fisteln in Axillen und Inguinalfalten bei einer 28-jährigen Raucherin. Diagnose?",
    o:["Furunkel","Hidradenitis suppurativa","Hailey-Hailey","Cutaner M. Crohn"], c:1,
    e:"HS: chronisch-rezidivierende Entzündung der pilosebazeö-apokrinen Einheit. RF: Adipositas, Nikotinabusus, CIBD.",
    svg:`<svg viewBox="0 0 280 280" xmlns="http://www.w3.org/2000/svg"><ellipse cx="140" cy="140" rx="90" ry="115" fill="#fde2cb" stroke="#9ca3af"/><g fill="#7f1d1d"><circle cx="100" cy="100" r="9"/><circle cx="180" cy="100" r="9"/><circle cx="92" cy="115" r="7"/><circle cx="188" cy="115" r="7"/><circle cx="105" cy="220" r="9"/><circle cx="175" cy="220" r="9"/><circle cx="120" cy="235" r="7"/><circle cx="160" cy="235" r="7"/></g><g stroke="#7f1d1d" stroke-width="3" fill="none"><path d="M100,100 Q92,108 92,115"/><path d="M180,100 Q188,108 188,115"/><path d="M105,220 Q113,227 120,235"/><path d="M175,220 Q167,227 160,235"/></g><text x="50" y="92" font-size="10" fill="#7f1d1d" font-family="sans-serif">Axilla</text><text x="200" y="92" font-size="10" fill="#7f1d1d" font-family="sans-serif">Axilla</text><text x="50" y="252" font-size="10" fill="#7f1d1d" font-family="sans-serif">Inguinal</text><text x="190" y="252" font-size="10" fill="#7f1d1d" font-family="sans-serif">Inguinal</text></svg>`},
  {s:5, cap:"Schema der dermo-epidermalen Junktionszone", q:"Eine Mutation in KRT5/KRT14 führt zu einer Spaltbildung an welcher Stelle?",
    o:["Subkorneal","Intraepidermal (basal)","Lamina lucida","Sub-Lamina densa"], c:1,
    e:"EB simplex (KRT5/KRT14): intraepidermale Spalte in den basalen Keratinozyten.",
    svg:`<svg viewBox="0 0 320 280" xmlns="http://www.w3.org/2000/svg"><rect x="20" y="20" width="280" height="40" fill="#fcd34d" opacity="0.7"/><text x="30" y="45" font-size="10" fill="#374151" font-family="sans-serif">Stratum corneum</text><rect x="20" y="60" width="280" height="60" fill="#fde68a" opacity="0.7"/><text x="30" y="95" font-size="10" fill="#374151" font-family="sans-serif">Stratum spinosum/granulosum</text><rect x="20" y="120" width="280" height="20" fill="#fef9c3"/><text x="30" y="135" font-size="10" fill="#dc2626" font-family="sans-serif">Basal: KRT5/14 → EBS (Spalt hier)</text><line x1="20" y1="140" x2="300" y2="140" stroke="#374151" stroke-width="2"/><rect x="20" y="140" width="280" height="20" fill="#bbf7d0"/><text x="30" y="155" font-size="10" fill="#374151" font-family="sans-serif">Lamina lucida (Lam332) → JEB</text><line x1="20" y1="160" x2="300" y2="160" stroke="#374151" stroke-width="2"/><rect x="20" y="160" width="280" height="20" fill="#86efac"/><text x="30" y="175" font-size="10" fill="#374151" font-family="sans-serif">Lamina densa</text><rect x="20" y="180" width="280" height="20" fill="#bbf7d0"/><text x="30" y="195" font-size="10" fill="#374151" font-family="sans-serif">Sub-LD (Kollagen VII) → DEB / EBA</text><rect x="20" y="200" width="280" height="60" fill="#fde68a" opacity="0.4"/><text x="30" y="240" font-size="10" fill="#374151" font-family="sans-serif">Dermis</text></svg>`},
  {s:3, cap:"Klassische klinische Lokalisation", q:"Heliotropes Lidödem + Erythem über Knöcheln (Gottron-Papeln) bei 50-Jähriger. Welche Erkrankung?",
    o:["Lichen ruber","Dermatomyositis","Diskoider Lupus","Sklerodermie"], c:1,
    e:"Heliotropes Erythem + Gottron-Zeichen = pathognomonisch für Dermatomyositis. Tumorscreening obligat > 40 J.",
    svg:`<svg viewBox="0 0 280 220" xmlns="http://www.w3.org/2000/svg"><rect x="0" y="0" width="280" height="220" fill="#fde2cb"/><path d="M80,100 L80,180 L130,180 L130,160 Q150,160 150,150 Q150,140 130,140 L130,100 Z" fill="#fed7aa" stroke="#92400e"/><ellipse cx="100" cy="125" rx="9" ry="5" fill="#a855f7" opacity="0.6"/><ellipse cx="115" cy="123" rx="9" ry="5" fill="#a855f7" opacity="0.6"/><ellipse cx="100" cy="155" rx="9" ry="5" fill="#a855f7" opacity="0.6"/><ellipse cx="115" cy="155" rx="9" ry="5" fill="#a855f7" opacity="0.6"/><text x="155" y="135" font-size="10" fill="#374151" font-family="sans-serif">Gottron-Papeln</text><text x="155" y="148" font-size="10" fill="#374151" font-family="sans-serif">über MCP/PIP</text></svg>`},
  {s:3, cap:"Klinisches Phänomen am Schleimhaut-Befall", q:"Welches Phänomen wird angedeutet (feine weisse retikuläre Streifung auf violetter Plaque)?",
    o:["Auspitz-Phänomen","Wickham-Streifung","Köbner-Phänomen","Nikolski-Zeichen"], c:1,
    e:"Wickham-Streifung: feine weisse Streifung auf Lichen-ruber-Papeln (Hyperkeratose und Hypergranulose).",
    svg:`<svg viewBox="0 0 280 200" xmlns="http://www.w3.org/2000/svg"><rect x="0" y="0" width="280" height="200" fill="#fda4af" opacity="0.3"/><ellipse cx="140" cy="100" rx="100" ry="60" fill="#7c3aed" opacity="0.55"/><g stroke="#fff" stroke-width="1.5" fill="none" opacity="0.95"><path d="M70,80 Q90,90 100,75"/><path d="M120,75 L150,90"/><path d="M170,82 Q180,95 200,85"/><path d="M70,110 Q100,120 130,108"/><path d="M150,118 L185,108"/><path d="M90,135 Q110,145 130,130"/><path d="M150,140 Q175,135 200,140"/></g></svg>`}
];

const FLASH_MORE = [
  {s:3, q:"Was ist eine Pityriasis lichenoides Mucha-Habermann?",a:"Febrile ulzeronekrotische Sonderform von PLEVA mit Fieber, ulzeronekrotischen Läsionen, Lymphadenopathie, Arthritis."},
  {s:3, q:"Beim AGEP zeigt das Differentialblutbild typischerweise was?",a:"Leukozytose mit Neutrophilie. Bei DRESS dagegen Eosinophilie + atypische Lymphozyten."},
  {s:3, q:"Was ist Eczema craquelé?",a:"Asteatotisches/Exsikkations-Ekzem: 'porzellanartige' Felder mit feinen Rissen, oft am Schienbein älterer Patienten im Winter."},
  {s:3, q:"Lichen sclerosus genital – SCC-Risiko bei Frauen?",a:"~5% lebenslanges Vulva-Plattenepithelkarzinom-Risiko. Lebenslange dermatologische Verlaufskontrollen."},
  {s:3, q:"Was unterscheidet Lichen planus actinicus vom klassischen LP?",a:"L. ruber actinicus: in sonnenexponierten Arealen, anuläre/melanoderme Plaques, klassisch Pat. aus dem Mittleren Osten."},
  {s:3, q:"Lichen ruber pemphigoides – Antigen?",a:"Kombination LR-Klinik + Auto-AK gegen BPAG2/BP180 (NC16A). Junge Pat. im Vergleich zum klassischen BP."},
  {s:3, q:"Welche Topika sind bei Psoriasis in der Schwangerschaft sicher?",a:"Calcipotriol topisch (limitiert), TCS Klasse I-II in begrenzter Fläche, Emollientien. Acitretin und MTX absolut KI."},
  {s:3, q:"PRP Typ VI – Assoziation?",a:"HIV-assoziiert. Antiretrovirale Therapie als wichtigster Schritt; topisch Retinoide, ggf. UVB."},
  {s:4, q:"Wann denkt man an ein TRAPS-Syndrom?",a:"TNF-Receptor-Associated Periodic Syndrome: rezidivierendes Fieber, migrierendes Erythem, Myalgien, periorbitales Ödem. Therapie IL-1- oder TNF-Inhibitoren."},
  {s:4, q:"Therapie Lyme-Karditis mit AV-Block II/III?",a:"Stationär i.v. Ceftriaxon 2 g/Tag für 14-21 Tage, Telemetrie-Monitoring, ggf. temporärer Pacer."},
  {s:4, q:"FMF (Familiäres Mittelmeerfieber) – Gen?",a:"MEFV-Gen kodiert Pyrin. Therapie: Colchicin lebenslang zur Verhinderung renaler Amyloidose."},
  {s:4, q:"Heerfordt-Syndrom?",a:"Sarkoidose-Manifestation: Uveitis + Parotitis + Fieber + Fazialisparese."},
  {s:4, q:"Kriterien zur Erstdiagnose APS?",a:"Lupus-Antikoagulans, Anti-Cardiolipin-IgG/IgM, Anti-β2GPI-IgG/IgM. ≥ 2 positive Tests im Abstand von ≥ 12 Wochen."},
  {s:4, q:"NRBC (necrolytic acral erythema) – Lokalisation und Trigger?",a:"Akrale Lokalisation mit Schuppung, oft mit Hepatitis-C-Infektion assoziiert."},
  {s:5, q:"Pemphigus vegetans Typ Hallopeau?",a:"Granulomatös-vegetierende Plaques in Intertrigines mit pustulösen Eruptionen. Subform des Pemphigus vulgaris."},
  {s:5, q:"Welcher Test sollte vor Azathioprin obligatorisch sein?",a:"TPMT-Aktivität – bei reduzierter Aktivität schwere Myelosuppression. ~10% Heterozygoten, ~0,3% Homozygoten."},
  {s:5, q:"Bullöse Ichthyose – Vererbung und Gene?",a:"Autosomal-dominant. KRT1 oder KRT10 (epidermolytische Hyperkeratose)."},
  {s:5, q:"Erythropoietische Protoporphyrie (EPP) – Klinik?",a:"FECH-Mutation. Sofort brennende Schmerzen + Erythem nach Sonnenlicht, ohne Bullae. Therapie: Afamelanotid."},
  {s:5, q:"PCT – Hauptursachen?",a:"Alkohol, Östrogene, Hepatitis C, HIV, Eisenüberladung, Nikotinabusus. Reduzierte UROD-Aktivität."},
  {s:5, q:"Mastozytose – wichtigste Mutation?",a:"KIT-D816V-Mutation (Tyrosinkinase). Tryptase im Serum, KMP bei systemischer Form."},
  {s:5, q:"Mastzelldegranulation – klassische Trigger?",a:"NSAR, Opioide, Röntgenkontrastmittel, Alkohol, scharfes Essen, Insektenstiche, mechanische Reibung (Darier-Zeichen +)."},
  {s:5, q:"M. Hailey-Hailey – Gen + Trigger?",a:"ATP2C1 (Calciumpumpe). Trigger: Hitze, Friktion, Schweiß. Therapie: Antiseptika, TCS, Botox, Laser."},
  {s:5, q:"M. Darier – Gen + Klinik?",a:"ATP2A2 (SERCA2). Hyperkeratotische Papeln in seborrhoischen Arealen, V-shaped nail nicks, palmare Pits. Acitretin/Isotretinoin."},
  {s:5, q:"Grover-Disease (transient acantholytic dermatosis)?",a:"Stamm-betonte juckende Papeln/Papulovesikel, oft im Sommer durch Schweiß/Bettlägerigkeit. Histologisch fokale akantholytische Dyskeratose."},
  {s:6, q:"Acne tarda – endokrinologische DDx?",a:"PCOS, Late-onset CAH (21-Hydroxylase-Mangel), androgenproduzierender Tumor."},
  {s:6, q:"Welcher Laser bei flachen erythematösen Aknenarben?",a:"Pulsed Dye Laser (PDL) oder Nd:YAG. Bei atrophen Narben: fraktioniert ablativer/nicht-ablativer Laser."},
  {s:6, q:"Spironolacton in der Akne-Therapie?",a:"Acne tarda bei Frauen, antiandrogene Wirkung. 50-100 mg/Tag. Cave Hyperkaliämie und Schwangerschaft."},
  {s:6, q:"SAPHO-Syndrom – Komponenten?",a:"Synovitis, Akne (insb. fulminans/conglobata), Pustulose (palmoplantar), Hyperostose, Osteitis. Sternoclavikularer Befall klassisch."},
  {s:6, q:"Rosacea fulminans (Pyoderma faciale)?",a:"Junge Frauen, Stress, Schwangerschaft. Explosives Auftreten von Papeln/Pusteln/Nodi auf Erythem im Gesicht."},
  {s:6, q:"Lupus miliaris disseminatus faciei – Bezug?",a:"Wird als Maximalform der granulomatösen Rosacea verstanden. Monomorphe hautfarbene Papeln zentrofazial."},
  {s:6, q:"Ofuji eosinophile pustulöse Follikulitis – Verlauf?",a:"Episoden alle 3-4 Wochen, selbstlimitierend nach 7-10 Tagen. Indomethacin 50 mg/Tag als First Line."},
  {s:6, q:"Welche Hauterkrankung kann nach Laser-Haarentfernung neu auftreten?",a:"Fox-Fordyce Disease (apokrine Gangokklusion mit juckenden axillären Papeln)."}
];

const MC_MORE = [
  {s:3, q:"Welche Mutation liegt der bullösen Ichthyose zugrunde?",
    o:["FLG","KRT1/KRT10","TGM1","ABCA12"], c:1,
    e:"KRT1/KRT10 → epidermolytische Hyperkeratose. FLG → Ichthyosis vulgaris. TGM1 → lamelläre Ichthyose."},
  {s:3, q:"Bei welcher Erkrankung sieht man typisch 'Nappes claires'?",
    o:["Pityriasis rubra pilaris","Atopische Dermatitis","Psoriasis","Lichen ruber"], c:0,
    e:"PRP: 'islands of sparing' (Nappes claires) – Aussparungen normaler Haut innerhalb der Erythrodermie."},
  {s:3, q:"Welcher Wirkstoff ist KEIN topischer Calcineurin-Inhibitor?",
    o:["Pimecrolimus","Tacrolimus","Crisaborol","Ruxolitinib"], c:3,
    e:"Ruxolitinib ist ein topischer JAK-Inhibitor. Crisaborol ist PDE4-I. Pimecrolimus, Tacrolimus = TCI."},
  {s:3, q:"Welcher Filaggrin-Genort liegt der atopischen Diathese zugrunde?",
    o:["Chromosom 1q21 (EDC)","Chromosom 6p21 (HLA)","Chromosom 11","Chromosom 17"], c:0,
    e:"Filaggrin liegt im Epidermal Differentiation Complex auf 1q21."},
  {s:3, q:"Welche Erkrankung ist NICHT mit Köbner-Phänomen klassisch assoziiert?",
    o:["Psoriasis","Lichen ruber","Vitiligo","Atopische Dermatitis"], c:3,
    e:"AD kann durch Reibung verschlechtert werden, klassisches Köbner-Phänomen aber bei Psoriasis, LP, Vitiligo, Vaskulitis."},
  {s:3, q:"Welcher Wirkstoff ist Erstlinientherapie der Skabies bei einem 4-Wochen alten Säugling?",
    o:["Permethrin 5%","Ivermectin oral","Crotamiton","Lindan"], c:0,
    e:"Permethrin 5% topisch ab Geburt zugelassen. Ivermectin oral erst ab 15 kg KG."},
  {s:3, q:"Welcher Marker ist bei Mycosis fungoides am wichtigsten?",
    o:["CD30","CD4+/CD7-","CD68","CD20"], c:1,
    e:"MF: CD4+/CD7- T-Zellklon. Verlust von CD7 ist charakteristisch."},
  {s:3, q:"Welches Medikament ist bei seborrhoischem Ekzem am Capillitium First Line?",
    o:["Hydrocortison-Lotion","Ketoconazol-Shampoo","Clobetasol-Lotion","Cyclosporin"], c:1,
    e:"Ketoconazol-Shampoo (Nizoral) ist Erstwahl. TCS in Reserve."},
  {s:4, q:"Welche Erkrankung wird mit dem Schnitzler-Syndrom verwechselt?",
    o:["CAPS / Muckle-Wells","Mastozytose","Anaphylaxie","HSP"], c:0,
    e:"CAPS (NLRP3-Mutation): Kälteurtikaria, Fieber, Konjunktivitis, Arthralgien, Hörverlust (Muckle-Wells)."},
  {s:4, q:"Welche Vaskulitis ist mit eosinophilem Asthma und MPO-ANCA assoziiert?",
    o:["GPA","EGPA (Churg-Strauss)","MPA","PAN"], c:1,
    e:"EGPA: Asthma + Eosinophilie + ANCA gegen MPO. Therapie: Steroide + Mepolizumab."},
  {s:4, q:"Naproxen ist klassischer Trigger für…?",
    o:["AGEP","Pseudoporphyrie","DRESS","Erythema nodosum"], c:1,
    e:"Pseudoporphyrie ohne Porphyrin-Erhöhung. Klassisch Naproxen, ferner Furosemid, Tetracycline, Voriconazol."},
  {s:4, q:"Welche Komplikation ist beim akuten rheumatischen Fieber am gefährlichsten?",
    o:["Nephritis","Karditis (Mitralinsuffizienz)","Hauterkrankung","Hörverlust"], c:1,
    e:"Karditis mit chronischer Mitralinsuffizienz. Prophylaxe: Penicillin p.o. bis 10 Jahre."},
  {s:4, q:"Trigger DRESS – am häufigsten?",
    o:["Aminopenicillin","Antikonvulsiva, Allopurinol, Sulfonamide","NSAR","Vancomycin"], c:1,
    e:"DRESS: insb. Antikonvulsiva, Allopurinol, Sulfonamide, Minocyclin, Dapson, HAART."},
  {s:4, q:"PUPPP – Charakteristikum?",
    o:["Bullae periumbilical","Stria-betonte juckende Papeln im 3. Trimenon, Bauchnabel ausgespart","Vesikobullae der Hände","Vesikulopusteln Stirn"], c:1,
    e:"PUPPP: pruritische Papeln entlang der Striae mit Aussparung des Bauchnabels."},
  {s:4, q:"Befund: palpable Purpura, Sinusitis, Hämoptysen, Glomerulonephritis und cANCA. Diagnose?",
    o:["IgA-Vaskulitis","GPA (Wegener)","MPA","PAN"], c:1,
    e:"GPA: granulomatöse Vaskulitis kleiner und mittlerer Gefässe. cANCA gegen PR3."},
  {s:4, q:"Welche Vaskulitis ist klassisch bei jungen Frauen aus Asien beschrieben?",
    o:["GZA","Takayasu-Arteriitis","PAN","Kawasaki"], c:1,
    e:"Takayasu: 'pulseless disease' der Aorta und Hauptäste. Tocilizumab (IL-6) als Therapie."},
  {s:5, q:"Welche Erkrankung wird durch Penicillamin als Trigger ausgelöst?",
    o:["BP","Pemphigus vulgaris/foliaceus","DRESS","SJS"], c:1,
    e:"Penicillamin (Thiol-Mechanismus): induziert klassisch Pemphigus foliaceus oder vulgaris."},
  {s:5, q:"Welcher Wirkstoff hemmt beim DH die Neutrophilen-Chemotaxis?",
    o:["Sulfasalazin","Dapson","MMF","Rituximab"], c:1,
    e:"Dapson hemmt MPO und Chemotaxis – Wirkmechanismus bei vielen neutrophilen Dermatosen."},
  {s:5, q:"Welche AIBD ist klassisch mit hochmalignen Lymphomen assoziiert?",
    o:["Lineare IgA-Dermatose","Paraneoplastischer Pemphigus","BP","Pemphigus foliaceus"], c:1,
    e:"PNP: NHL > CLL > Castleman > Thymom > Sarkome. Mortalität 70-90% (Bronchiolitis obliterans)."},
  {s:5, q:"Welche Kombination passt zu pruriginous Plaques periumbilical im 3. Trimenon mit positivem Anti-BP180?",
    o:["PUPPP","Pemphigoid gestationis","AEP","ICP"], c:1,
    e:"Pemphigoid gestationis: Anti-BP180-AK, periumbilical-Beginn (anders als PUPPP)."},
  {s:5, q:"Welche Erkrankung verläuft TEN-ähnlich durch Vancomycin-Triggerung?",
    o:["BP","Lineare IgA-bullöse Dermatose","Pemphigus vulgaris","Sézary"], c:1,
    e:"LABD durch Vancomycin: kann TEN-ähnlich verlaufen. Auto-AK gegen LAD-1."},
  {s:5, q:"Welche kutane Komplikation ist bei CLL klassisch?",
    o:["Bullöse Insektenstichreaktion","Pemphigus vulgaris","Acanthosis nigricans","Necrobiosis lipoidica"], c:0,
    e:"CLL: überschießende Reaktionen auf Insektenstiche, oft bullös."},
  {s:6, q:"Welche Akneform ist mit Anabolika-/Testosteron-Missbrauch assoziiert?",
    o:["Acne mechanica","Acne fulminans","Acne tarda","Chlorakne"], c:1,
    e:"Acne fulminans: junge Männer unter Anabolika. Steroide + niedrigdosiertes Isotretinoin."},
  {s:6, q:"Therapie der akneiformen Eruption durch EGFR-Inhibitoren?",
    o:["Sofortiges Absetzen des EGFR-Inh.","Topisches Clindamycin oder Doxycyclin systemisch","Steroidbolus i.v.","Cyclosporin"], c:1,
    e:"EGFR-induzierte akneiforme Follikulitis: topisches Clindamycin, Doxycyclin systemisch (50-100 mg/Tag)."},
  {s:6, q:"Welche Mutation begünstigt familiäre HS mit frühem Beginn?",
    o:["NLRP3","NCSTN/PSEN1/PSENEN (γ-Sekretase)","FLG","ATP2C1"], c:1,
    e:"γ-Sekretase-Mutationen: schwerere und früher beginnende familiäre HS."},
  {s:6, q:"Welches Phänomen ist bei Morbus Morbihan typisch?",
    o:["Persistierendes festes Oedem oberes Gesicht","Pusteln im Nacken","Phym","Rote Wangen mit Teleangiektasien"], c:0,
    e:"M. Morbihan: persistierendes nicht-eindrückbares Oedem von Stirn, Glabella, Augenlidern, Wangen."},
  {s:6, q:"Welche Erkrankung wird durch Cathelicidin/TLR2 vermittelt?",
    o:["Akne","Rosacea","Lichen ruber","AD"], c:1,
    e:"Rosacea: dysregulierte angeborene Immunantwort mit Cathelicidin/TLR2-Aktivierung."},
  {s:6, q:"Welche Untersuchung ist VOR Beginn von Isotretinoin obligat?",
    o:["MRT Hypophyse","Schwangerschaftstest und Lipid-Status","Knochendichtemessung","Spirometrie"], c:1,
    e:"Schwangerschaftstest, Lipidstatus (TG/Cholesterin), Transaminasen vor Therapie und nach 2 Monaten."},
  {s:6, q:"Welche Therapie ist Erstwahl bei Acne keloidalis nuchae im Frühstadium?",
    o:["Chirurgische Exzision","TCS Kl. III-IV + Tetracycline + Laser-Haarentfernung","Isotretinoin","Lokale Bestrahlung"], c:1,
    e:"AKN: TCS + Tetracycline + Laser-Haarentfernung als Frühtherapie."},
  {s:6, q:"5-Jähriges Mädchen mit Akne. Welche Untersuchung ist obligat?",
    o:["Beobachten","Hyperandrogenismus-Suche, ggf. Knochenalter","Hautbiopsie","Allergietestung"], c:1,
    e:"Mid-childhood acne (1-7 LJ): obligater Ausschluss von Hyperandrogenismus, vorzeitiger Adrenarche, AGS, NN-Tumor."}
];

const TF_MORE = [
  {s:3, st:"Bei Pityriasis rosea ist HSV-2 ein bekannter Trigger.", c:false, e:"Falsch. HHV-6/HHV-7 werden vermutet."},
  {s:3, st:"Acitretin gehört zu den Retinoiden.", c:true, e:"Korrekt. Orales Retinoid (Vitamin-A-Derivat). KI: SS, leberkrank."},
  {s:3, st:"Bimekizumab blockiert sowohl IL-17A als auch IL-23.", c:false, e:"Falsch. Bimekizumab blockiert IL-17A UND IL-17F (nicht IL-23)."},
  {s:3, st:"Tinea pedis kann ein Erythema annulare centrifugum triggern.", c:true, e:"Korrekt. In ca. 50% Tinea-Assoziation."},
  {s:3, st:"Atopische Dermatitis ist primär Th17-vermittelt.", c:false, e:"Falsch. AD ist akut Th2-, chronisch Th1-dominiert."},
  {s:3, st:"Bei einer Erythrodermie sollte regelmäßig eine Hautbiopsie zum Ausschluss MF erfolgen.", c:true, e:"Korrekt. Wiederholte Biopsien sind essentiell."},
  {s:3, st:"Lichen sclerosus genital hat ein erhöhtes SCC-Risiko.", c:true, e:"Korrekt. ~5% lebenslanges Vulva-PEC-Risiko."},
  {s:4, st:"Lupus-Antikoagulans ist ein funktioneller Test für eine Gerinnungsstörung.", c:true, e:"Korrekt. Verlängert die aPTT."},
  {s:4, st:"Behcet-Syndrom ist HLA-B27-assoziiert.", c:false, e:"Falsch. Behcet ist HLA-B51-assoziiert."},
  {s:4, st:"Cryoglobulinämie Typ I verursacht typisch Hyperviskositätssymptome.", c:true, e:"Korrekt. Typ I (monoklonal). Typ II/III (gemischt) verursachen Vaskulitis."},
  {s:4, st:"Doxycyclin-Prophylaxe wird ab Zeckenstich >24 h empfohlen.", c:false, e:"Falsch. Empfehlung ab > 36 h Saugzeit."},
  {s:4, st:"Pemphigoid gestationis hat 100% positive C3 in der DIF.", c:true, e:"Korrekt. C3 in 100%, IgG nur in 30%."},
  {s:4, st:"Erythema nodosum ist eine septale Pannikulitis.", c:true, e:"Korrekt. Histologisch septale Pannikulitis ohne Vaskulitis."},
  {s:4, st:"Naproxen ist klassischer Trigger der Pseudoporphyrie.", c:true, e:"Korrekt. Auch Furosemid, Tetracycline, Voriconazol, Amiodaron."},
  {s:4, st:"GPA-Patienten haben typisch pANCA gegen MPO.", c:false, e:"Falsch. GPA: cANCA gegen PR3. EGPA/MPA: pANCA gegen MPO."},
  {s:5, st:"Pemphigus vulgaris zeigt Anti-Dsg3 in 100% der Fälle.", c:false, e:"Falsch. Anti-Dsg3 ist häufig, aber nicht universell."},
  {s:5, st:"Bei BP zeigt Salt-split-skin Bindung am Blasenboden.", c:false, e:"Falsch. BP180/BP230 sind oberhalb der Spalte → AK binden am Dach."},
  {s:5, st:"Dapson kann eine Methämoglobinämie verursachen.", c:true, e:"Korrekt. < 15% meist asymptomatisch. Antidot: Methylenblau i.v."},
  {s:5, st:"Mycosis fungoides zeigt eine CD4+/CD7- T-Zell-Population.", c:true, e:"Korrekt. CD7-Verlust ist charakteristisch."},
  {s:5, st:"DH Duhring zeigt eine erhöhte Prävalenz bei Patienten mit Zöliakie.", c:true, e:"Korrekt. ~90% der DH-Patienten haben histologisch Zöliakie."},
  {s:5, st:"Pemphigus foliaceus zeigt typisch Schleimhauterosionen.", c:false, e:"Falsch. Anti-Dsg1 → keine Mukosabeteiligung."},
  {s:5, st:"Junktionale EB Herlitz ist meist letal im Säuglingsalter.", c:true, e:"Korrekt. Schwere Mutationen in Laminin-332."},
  {s:5, st:"M. Hailey-Hailey wird durch ATP2A2-Mutation verursacht.", c:false, e:"Falsch. ATP2C1 = Hailey-Hailey. ATP2A2 = M. Darier."},
  {s:5, st:"Die meisten EBA-Patienten haben eine assoziierte M. Crohn.", c:false, e:"Falsch. EBA bei M. Crohn gehäuft, aber nicht in Mehrzahl. Auch SLE, RA, Plasmazelldyskrasie."},
  {s:6, st:"Akne fulminans wird primär mit Isotretinoin behandelt.", c:false, e:"Falsch. Isotretinoin kann Akne fulminans triggern. Initial Steroide, dann Isotretinoin niedrigdosiert."},
  {s:6, st:"HS Hurley III: Adalimumab + Chirurgie ist effektiver als Adalimumab allein.", c:true, e:"Korrekt. Studien zeigen Überlegenheit der Kombination."},
  {s:6, st:"Topische Retinoide sind in der Schwangerschaft erlaubt.", c:false, e:"Falsch. Auch topische Retinoide werden in SS gemieden."},
  {s:6, st:"Cutibacterium acnes ist der korrekte Name für Propionibacterium acnes.", c:true, e:"Korrekt. Umbenennung 2016. Anaerob, spaltet Triglyzeride zu Propionsäure."},
  {s:6, st:"Spironolacton ist erste Wahl bei Acne fulminans.", c:false, e:"Falsch. Spironolacton: Acne tarda bei Frauen. Acne fulminans: Steroide + Isotretinoin niedrigdosiert."},
  {s:6, st:"Ein gestörtes Mikrobiom spielt bei der HS-Pathogenese eine Rolle.", c:true, e:"Korrekt. Veränderte Anaerobier-/Corynebakterien-Dominanz."},
  {s:6, st:"Frey-Syndrom wird mit Antihistaminika behandelt.", c:false, e:"Falsch. Therapie: Botox-Injektionen, topische Anticholinergika."},
  {s:6, st:"Demodex-Folliculitis spricht klassisch auf Soolantra (Ivermectin 1%) an.", c:true, e:"Korrekt. 1x täglich über 4-6 Wochen."},
  {s:6, st:"Bei Acne tarda mit unregelmäßigen Perioden sollte ein PCOS abgeklärt werden.", c:true, e:"Korrekt. PCOS mit Hyperandrogenismus ist wichtige DDx."},
  {s:6, st:"Lupus miliaris disseminatus faciei ist die Maximalform der papulopustulösen Rosacea.", c:false, e:"Falsch. Maximalform der granulomatösen Rosacea."},
  {s:6, st:"Iontophorese ist bei Schrittmachern kontraindiziert.", c:true, e:"Korrekt. Auch ICD und metallisches IUP sind KI."}
];

const CLOZE_MORE = [
  {s:3, parts:["Atopische Dermatitis betrifft ca. ","BLANK"," der Kinder und ","BLANK"," der Erwachsenen in Industrieländern."], a:["10-25%","2-10%"]},
  {s:3, parts:["Bei der Vitiligo erfolgt eine ","BLANK","-vermittelte Zerstörung der Melanozyten."], a:["CD8+-T-Zell"]},
  {s:3, parts:["Eine Systemtherapie der Psoriasis ist indiziert ab BSA > ","BLANK","%, PASI > ","BLANK"," und DLQI > ","BLANK","."], a:["10","10","10"]},
  {s:3, parts:["Cyclosporin wird bei AD ab dem ","BLANK","-Lebensjahr eingesetzt, Beginn mit ","BLANK"," mg/kg KG."], a:["16","2.5"]},
  {s:3, parts:["Lichen ruber: in 75% der Patienten mit kutanen Läsionen findet man eine ","BLANK","-Beteiligung."], a:["enorale"]},
  {s:3, parts:["Topisches Ruxolitinib ist ein ","BLANK","-Inhibitor."], a:["JAK"]},
  {s:3, parts:["Lichen pemphigoides hat Auto-AK gegen ","BLANK","/BP180."], a:["BPAG2"]},
  {s:3, parts:["PRP Typ ","BLANK"," ist HIV-assoziiert."], a:["VI"]},
  {s:3, parts:["Acrodermatitis enteropathica – Mutation im ","BLANK","-Gen (Zinktransporter ZIP4)."], a:["SLC39A4"]},
  {s:4, parts:["DRESS hat eine Mortalität von ca. ","BLANK"," %."], a:["10"]},
  {s:4, parts:["Akut hämorrhagisches Ödem des Kleinkindes: Alter < ","BLANK"," Jahren."], a:["2"]},
  {s:4, parts:["Polyarteritis nodosa (klassisch) ist mit Hepatitis ","BLANK"," assoziiert."], a:["B"]},
  {s:4, parts:["Cryoglobulinämie Typ ","BLANK"," ist monoklonal."], a:["I"]},
  {s:4, parts:["Pemphigoid gestationis hat ","BLANK"," % positive C3 in der DIF."], a:["100"]},
  {s:4, parts:["APS-Laborkriterien: positiv an mind. ","BLANK"," Zeitpunkten im Abstand von ≥ ","BLANK"," Wochen."], a:["2","12"]},
  {s:4, parts:["Doxycyclin-Prophylaxe nach Zeckenstich > 36 h reduziert das EM-Risiko um ca. ","BLANK"," %."], a:["87"]},
  {s:4, parts:["Sweet-Syndrom: Histo zeigt dichtes ","BLANK","-Infiltrat ohne Vaskulitis."], a:["neutrophiles"]},
  {s:5, parts:["PV: Akantholyse direkt ","BLANK"," der Basalzellschicht."], a:["oberhalb"]},
  {s:5, parts:["Lineare IgA-Dermatose der Kindheit: Spontane Remission nach ","BLANK","-","BLANK"," Jahren."], a:["2","4"]},
  {s:5, parts:["Vor AZA-Therapie: Bestimmung der ","BLANK","-Aktivität."], a:["TPMT"]},
  {s:5, parts:["Pemphigoid gestationis tritt im ","BLANK","./","BLANK","-Trimenon oder peripartal auf."], a:["2","3"]},
  {s:5, parts:["Salt-split-skin: Spaltung in der Lamina ","BLANK","."], a:["lucida"]},
  {s:5, parts:["Mastozytose: häufigste Mutation ","BLANK","-D816V."], a:["KIT"]},
  {s:5, parts:["EB simplex: Mutationen in ","BLANK"," oder ","BLANK","."], a:["KRT5","KRT14"]},
  {s:5, parts:["Bullosis diabeticorum: Spontanabheilung in ","BLANK","-","BLANK"," Wochen."], a:["2","6"]},
  {s:5, parts:["PCT: reduzierte hepatische ","BLANK","-Aktivität."], a:["Uroporphyrinogen-Decarboxylase"]},
  {s:6, parts:["Mid-childhood acne tritt im Alter von ","BLANK","-","BLANK"," LJ auf."], a:["1","7"]},
  {s:6, parts:["Bei HS: Secukinumab-Anfangsdosis ","BLANK"," mg s.c."], a:["300"]},
  {s:6, parts:["Adalimumab bei HS: Initialdosis ","BLANK"," mg, dann ","BLANK"," mg alle 2 Wochen."], a:["160","80"]},
  {s:6, parts:["Lasertherapie nach Isotretinoin-Stop: ","BLANK"," Monate Pause."], a:["6"]},
  {s:6, parts:["Apremilast ist ein ","BLANK","-4-Inhibitor."], a:["Phosphodiesterase"]},
  {s:6, parts:["Spironolacton bei Acne tarda: ","BLANK","-","BLANK"," mg/Tag."], a:["50","100"]},
  {s:6, parts:["Rosacea: zentrales antimikrobielles Peptid ist ","BLANK","."], a:["Cathelicidin"]}
];

const MATCH_MORE = [
  {s:3, t:"Atopische Stigmata ↔ Beschreibung", p:[
    ["Hertoghe-Zeichen","Verlust der lateralen Augenbrauen"],
    ["Dennie-Morgan-Falte","Doppelte Lidfalte unteres Augenlid"],
    ["Pityriasis alba","Hypopigmentierte schuppende Wangenflecken"],
    ["Palmare Hyperlinearität","Vermehrte Faltenzeichnung der Handinnenflächen"]
  ]},
  {s:4, t:"AME-Form ↔ Onset/Klinik", p:[
    ["AGEP","< 4 Tage, sterile Pusteln"],
    ["DRESS","2-8 Wochen, Eosinophilie + Organbeteiligung"],
    ["SJS/TEN","7-28 Tage, mukosale Erosionen + Epidermolyse"],
    ["Fixes AME","24 h bei Re-Exposition, gleiche Lokalisation"]
  ]},
  {s:5, t:"Genmutation ↔ Erkrankung", p:[
    ["KIT-D816V","Mastozytose"],
    ["ATP2C1","Hailey-Hailey"],
    ["ATP2A2","M. Darier"],
    ["KRT5/KRT14","EB simplex"],
    ["FECH","Erythropoetische Protoporphyrie"],
    ["IKBKG (NEMO)","Incontinentia pigmenti"]
  ]},
  {s:5, t:"AK ↔ Substrat (IIF)", p:[
    ["Anti-Dsg1/3","Affenösophagus"],
    ["Anti-Plakine (PNP)","Rattenblase"],
    ["Anti-tTG / Anti-eTG","DH Duhring"],
    ["Anti-Kollagen VII","EBA"]
  ]},
  {s:6, t:"Schweregrad HS Hurley ↔ Definition", p:[
    ["Hurley I","Solitäre Abszesse ohne Strangbildung"],
    ["Hurley II","Rezidivierende Abszesse mit Fistulierung lokalisiert"],
    ["Hurley III","Diffuse plattenartige Infiltrate mit Strängen"]
  ]},
  {s:4, t:"Periodisches Fiebersyndrom ↔ Genetik", p:[
    ["FMF","MEFV / Pyrin"],
    ["TRAPS","TNFRSF1A"],
    ["HIDS","MVK (Mevalonatkinase)"],
    ["CAPS","NLRP3 / Cryopyrin"]
  ]}
];

const FREETEXT_MORE = [
  {s:3, q:"Erläutern Sie die Pathogenese der Plaque-Psoriasis.",
    a:"Polygenetische Prädisposition (HLA-Cw6, CARD14, PSORS1). Trigger aktivieren Keratinozyten, die DNA/RNA und Cathelicidin LL-37 freisetzen. Plasmazytoide DCs produzieren IFN-α. DCs in den Lymphknoten via TNF/IL-12/IL-23 differenzieren naive T-Zellen zu Th1/Th17/Th22. Th17 sezerniert IL-17A/F + IL-22 → Hyperproliferation und gestörte Differenzierung der Keratinozyten (Zellteilung in 36 h statt 4 Wochen), Neutrophilen-Chemotaxis (Munro-Mikroabszesse). VEGF-Sekretion → Angiogenese (Auspitz-Phänomen). Teufelskreislauf."},
  {s:4, q:"Beschreiben Sie das diagnostische und therapeutische Vorgehen bei Anaphylaxie.",
    a:"Sofortige Beurteilung der Vitalzeichen, Schweregrad nach Ring & Messmer. Lagerung (Schock vs. sitzend). Adrenalin i.m. 0.01 mg/kg KG (max 0.5 mg) Vorderseite Oberschenkel, Wiederholung alle 5-15 min. O2 6-8 L/min, i.v. Volumen. Antihistaminika (Clemastin) und Glucocorticoide als Add-on. Beta-2-Mimetika bei Bronchospasmus. Bei Atemwegsobstruktion Intubation. Stationäre Beobachtung 6-24 h. Tryptase 1-2 h nach Ereignis. Allergologische Abklärung 4-6 Wochen später. Adrenalin-Autoinjektor + Pass."},
  {s:4, q:"Therapiestrategie bei therapierefraktärer chronischer spontaner Urtikaria?",
    a:"EAACI-Stufentherapie: 1) Standarddosis nicht-sed. H1-Antihistaminikum. 2) bis 4-fache Dosis. 3) Add-on Omalizumab 300 mg s.c. alle 4 Wochen. 4) Ciclosporin als Reserve. Triggervermeidung (NSAR, Codein). Bei NSAR-Intoleranz Montelukast als Add-on. Diagnostik: Total-IgE, Anti-TPO, BB, CRP, autologer Serumtest."},
  {s:5, q:"Differentialdiagnostische Schritte bei Verdacht auf AIBD?",
    a:"1) Klinik: Lokalisation, Schleimhaut, schlaffe vs. pralle Bullae, Vernarbung, Nikolski. 2) Histologie (läsional). 3) DIF aus periläsionaler Haut: IgG/IgA/C3-Muster (interzellulär vs linear vs granulär). 4) IIF (Affenösophagus, Salt-split-skin, Rattenblase bei PNP). 5) ELISA: Anti-Dsg1/3, Anti-BP180/230, Anti-Kollagen VII, Anti-tTG. 6) Bei PNP-Verdacht Tumorsuche. 7) Bei Anti-Lam-332-MMP Koloskopie und HNO."},
  {s:6, q:"Therapie schwerer Hidradenitis suppurativa Hurley III?",
    a:"Multimodal: 1) Lifestyle (Nikotinstopp, Gewicht, atmungsaktive Kleidung, Antiseptika). 2) Adalimumab 160 mg → 80 mg alle 2 Wochen. Bei Versagen Secukinumab 300 mg s.c. (Wo 0/1/2/3/4, dann monatlich), Bimekizumab off-label, Upadacitinib. 3) Antibiotika in Schüben: Doxycyclin 200 mg/Tag oder Clindamycin+Rifampicin. 4) Wide local excision mit Sekundärheilung. Adjuvante Chirurgie + Biologika ist effektiver. 5) Schmerztherapie und psychologische Betreuung. 6) Komorbiditäten."}
];

// Merge MORE arrays if present
if (typeof FLASH_MORE !== 'undefined') FLASH.push(...FLASH_MORE);
if (typeof MC_MORE !== 'undefined') MC.push(...MC_MORE);
if (typeof TF_MORE !== 'undefined') TF.push(...TF_MORE);
if (typeof CLOZE_MORE !== 'undefined') CLOZE.push(...CLOZE_MORE);
if (typeof MATCH_MORE !== 'undefined') MATCH.push(...MATCH_MORE);
if (typeof FREETEXT_MORE !== 'undefined') FREETEXT.push(...FREETEXT_MORE);
if (typeof IMG_MORE !== 'undefined') IMG.push(...IMG_MORE);
